### ISSUE TITLE
Documentation covering the cursor while writing

### ISSUE THREAD

**Issue by Jlchong3** [Saghen/blink.cmp#10]
When the screen is not big enough, for example while working in a splitscreen, the documentation covers what I'm writing.

nvim.cmp behaviour:
![image](https://github.com/user-attachments/assets/47ceece2-72b8-4da8-b4d5-55e7e92eb6a8)

blink.cmp behaviour:
![image](https://github.com/user-attachments/assets/d3031bd8-7b87-4b71-94b8-55a7be2274f3)

**Comment by Saghen** [comment]
Fixed by https://github.com/Saghen/blink.cmp/commit/ba62bda5af9b5f2a8accb102eb4791fab94e2a90
