### ISSUE TITLE
Turn off cmp when in Telescope buffer

### ISSUE THREAD

**Issue by pappasam** [Saghen/blink.cmp#102]
I think this is essentially the same issue that was raised in nvim-cmp a while ago: https://github.com/hrsh7th/nvim-cmp/issues/60

When typing `<C-p>` and `<C-n>` (which, by default, are configured to scroll up and down the telescope window), the `blink.cmp` completion menu comes up. This is not desired behavior.

![telescope-buffer](https://github.com/user-attachments/assets/7922ac20-1416-4c83-8a17-ca4bb171a931)

## Environment

```
NVIM v0.11.0-dev-667+gd9ccd828b
Build type: RelWithDebInfo
LuaJIT 2.1.1724512491
Run "nvim -V1 -v" for more info
```

blink.cmp version: current HEAD (b330b61)

Telescope: current HEAD (df534c3)

**Comment by Biggybi** [comment]
A dirty fix:

[Here](https://github.com/Saghen/blink.cmp/blob/2f1b85bc4f15e2f3660550ef92161a93482f2fd8/lua/blink/cmp/keymap.lua#L53), add `if vim.bo.buftype ~= nil and vim.bo.buftype ~= '' then return end`.
