### ISSUE TITLE
Allow show and select_next keybinds to be the same

### ISSUE THREAD

**Issue by MariaSolOs** [Saghen/blink.cmp#106]
Hello! Very nice plugin :D Loving it so far!

While configuring it I encountered the following issue though: I like to overload `<c-n>` both for triggering completion and for selecting the next item. However if I set `show = '<c-n>'` the `select_next` keybind doesn't work. If I don't modify the `show` keybind then `<c-n>` will open the built-in completion when `blink` hasn't been triggered yet.

Is there a way to support this setup?

**Comment by MariaSolOs** [comment]
In fact: Is it possible to _never_ show the built-in completion menu if the `blink` menu is currently open?

**Comment by Saghen** [comment]
Hey! Thanks for the kind words :) This should be working on `main`, give that a shot and lmk if you're having issues

**Comment by MariaSolOs** [comment]
@Saghen it's indeed working on main, thanks!
