### ISSUE TITLE
'Postfix' snippet doesn't expand correctly

### ISSUE THREAD

**Issue by dmun** [Saghen/blink.cmp#111]
Some language servers like [ols](https://github.com/DanielGavin/ols) have postfix snippets which should behave like the first example in the clip. However typing any character makes the snippet expand incorrectly as shown in the other examples.

https://github.com/user-attachments/assets/1ee3a078-5368-426e-b0a8-60d94f1332a1

**Comment by Saghen** [comment]
Reproduced this but it looks like an issue with `ols` LSP itself as it's returning `len(l)` in the `textEdit`
