### ISSUE TITLE
[question] how to get snippets from lsp

### ISSUE THREAD

**Issue by strash** [Saghen/blink.cmp#112]
Hi, how do I get snippets from lsp?
 
What it looks like with blink:
<img width="484" alt="Screenshot 2024-10-14 at 17 49 02" src="https://github.com/user-attachments/assets/d0f32c1c-71ea-44c6-a079-631555a8be8e">

What it looks like with cmp:
<img width="403" alt="Screenshot 2024-10-14 at 17 50 08" src="https://github.com/user-attachments/assets/8969960f-44d3-49e9-877f-28e2e18f0f93">

I don't have any 3rd-party snippet engines installed, and the only thing about snippets in my config it is this part:
```lua
require("cmp").setup({
...
	snippet = {
		expand = function(args)
			vim.snippet.expand(args.body)
		end
	},
...
})
``` 
And here I guess:
```lua
local capabilities = vim.lsp.protocol.make_client_capabilities()
local cmp_nvim_lsp = require("plugin_loader").load("cmp_nvim_lsp")
if cmp_nvim_lsp ~= nil then
	capabilities = cmp_nvim_lsp.default_capabilities(capabilities)
	capabilities.textDocument.completion.completionItem.snippetSupport = true
end
```

**Comment by Saghen** [comment]
What LSP? There shouldn't be any difference between nvim-cmp and blink.cmp for getting completions

**Comment by strash** [comment]
I thought so too since I don’t use any snippets engine. It’s dartls from lspconfig. I did check the entire list of suggestions and there were no snippets from lsp. So I thought maybe there is something in blink config I could adjust.

**Comment by Saghen** [comment]
Does the `default_capabilities` snippet fix the issue for you? You can see exactly what that's setting here: https://github.com/hrsh7th/cmp-nvim-lsp/blob/main/lua/cmp_nvim_lsp/init.lua#L41

**Comment by strash** [comment]
Not really. That's all I could get:
<img width="360" alt="Screenshot 2024-10-16 at 21 58 49" src="https://github.com/user-attachments/assets/fb0356be-c454-489e-83d4-a47b03cface2">
<img width="249" alt="Screenshot 2024-10-16 at 21 59 22" src="https://github.com/user-attachments/assets/93bd3ef6-6692-4325-a7cf-b752b0ca0423">

Also with all that enabled I get this error (happened in golang project) when trying to commit/accept a suggestion:
<img width="1297" alt="Screenshot 2024-10-16 at 22 06 30" src="https://github.com/user-attachments/assets/fd7910dd-3c0e-448d-ab21-bda81fffe94d">

I should mention that snippets work as expected in lua and go but not in dart. It is if I only enable snippet capabilities.

Thanks for trying to help me!

**Comment by Saghen** [comment]
Ah, this issue might be fixed with https://github.com/Saghen/blink.cmp/commit/abcb2a0dab207e03d382acf62074f639a3572e20 then

**Comment by Saghen** [comment]
Closing as completed, please re-open if you're still having trouble!

**Comment by strash** [comment]
@Saghen everything works now. Thank you!
