### ISSUE TITLE
feature: insert 1st item on accept if nothing was selected

### ISSUE THREAD

**Issue by Rentib** [Saghen/blink.cmp#118]
Currently doing accept while none of the completion items is selected just hides blink. I believe it would make more sense to insert 1st completion item in this situation. I know that there is 'preselect', which kind of achieves that, but it doesnt work in neither 'manual' nor 'auto-insert'.

**Comment by groig** [comment]
A mix between `preselect` and `auto_insert` would be great.

**Comment by Rentib** [comment]
It doesn't work with `auto_insert`, because `accept` gets suppressed or something.
Essentially `select_and_accept` does only `select` part if nothing is selected.
