### ISSUE TITLE
FR: implement cmp's `max_item_count`

### ISSUE THREAD

**Issue by chrisgrieser** [Saghen/blink.cmp#123]
cmp has a useful option for sources, namely `max_item_count`. It limits the number of suggestion for a source. I find this most useful with the buffer source, as it allows you to display buffer results alongside the other suggestions, but limited to say `4`, so the buffer suggestions do not drown the other suggestions.

**Comment by Saghen** [comment]
Closed by https://github.com/Saghen/blink.cmp/commit/49e511235572576478bf6a573b59df990ead6dc3
