### ISSUE TITLE
Visual Bug in the `snippets` documentation window when used alongside `noice.nvim`

### ISSUE THREAD

**Issue by chrisgrieser** [Saghen/blink.cmp#126]
Given this snippet in a snippet file:

```json
"barbaz": {
  "body": "Hello World",
  "prefix": "foobar"
},
```

And using the following noice.nvim config:
```lua
opts = {
	lsp = {
		override = {
			["vim.lsp.util.stylize_markdown"] = true,
		},
	},
},
```

results in a duplicate display of the entry's key (the `barbaz`) when it comes blink.cmp's `snippets` source:

<img alt="Showcase" width=40% src="https://github.com/user-attachments/assets/f57c164d-1601-4b0c-9c0c-3d63d4bd4790">

It should also be noted that `["vim.lsp.util.stylize_markdown"] = true` is the *suggested setup* in noice's readme, meaning a lot of people will have it enabled. (And in fact, the documentation window does much look nicer with it, normally.)

**Comment by Saghen** [comment]
Can you confirm that you're on the latest commit? The documentation rendering no longer uses the `stylize_markdown` since #113

**Comment by chrisgrieser** [comment]
ah yes, I am v.0.3.1, which does not contain that commit. Didn't notice that commit in the commit history.
