### ISSUE TITLE
Flexible keymap support

### ISSUE THREAD

**Issue by AbaoFromCUG** [Saghen/blink.cmp#128]
Thanks for your amazing plugin!

I setup keymap `Super-Tab` which support `snippet forward` and `select next` via `Tab`, which means when I press `Tab`, will check `snippet forward`, `select next` in order, or fallback to normal key(Tab).

Here is my workaround of `blink.cmp` via hacking `require("blink.cmp.keymap").apply_keymap_to_current_buffer`. But I would like a official solution, like[ `nvim-cmp`](https://github.com/hrsh7th/nvim-cmp/wiki/Example-mappings#super-tab-like-mapping)
```lua
    local keymap = require("blink.cmp.keymap")
    local function apply_keymap_to_current_buffer()
        -- skip if we've already applied the keymaps
        for _, mapping in ipairs(vim.api.nvim_buf_get_keymap(0, "i")) do
            if mapping.desc == "blink.cmp" then
                return
            end
        end
        local insert_keys_to_commands = {
            ["<CR>"] = { "accept", "hide" },
            ["<C-Space>"] = { "show" },
            ["<C-d>"] = { "scroll_documentation_down" },
            ["<C-u>"] = { "scroll_documentation_up" },
            ["<Tab>"] = { "snippet_forward", "select_next" },
            ["<Down>"] = { "snippet_forward", "select_next" },
            ["<C-n>"] = { "snippet_forward", "select_next" },
            ["<S-Tab>"] = { "snippet_backward", "select_prev" },
            ["<Up>"] = { "snippet_backward", "select_prev" },
            ["<C-p>"] = { "snippet_backward", "select_prev" },
        }
        local snippet_keys_to_commands = {
            ["<Tab>"] = { "snippet_forward" },
            ["<Down>"] = { "snippet_forward" },
            ["<C-n>"] = { "snippet_forward" },
            ["<S-Tab>"] = { "snippet_backward" },
            ["<Up>"] = { "snippet_backward" },
            ["<C-p>"] = { "snippet_forward" },
        }

        -- insert mode: uses both snippet and insert commands
        for key, commands in pairs(insert_keys_to_commands) do
            keymap.set("i", key, function()
                for _, command in ipairs(commands) do
                    local did_run = require("blink.cmp")[command]()
                    if did_run then
                        return
                    end
                end
                return keymap.run_non_blink_keymap("i", key)
            end)
        end

        -- snippet mode
        for key, commands in pairs(snippet_keys_to_commands) do
            keymap.set("s", key, function()
                for _, command in ipairs(commands) do
                    local did_run = require("blink.cmp")[command]()
                    if did_run then
                        return
                    end
                end
                return keymap.run_non_blink_keymap("s", key)
            end)
        end
    end

    keymap.apply_keymap_to_current_buffer = apply_keymap_to_current_buffer

```

**Comment by Saghen** [comment]
I'd like to support custom keymaps at some point, but your use case seems a bit odd. Perhaps the new `trigger.autocomplete.show_in_snippet = false` option achieves what you're looking for? This avoids triggering the autocomplete window automatically (it can still be triggered manually) inside of a snippet. In which case, the default behavior of `select_next -> snippet forward -> fallback` should work

**Comment by igorlfs** [comment]
Hello! Chiming in because my requirements for a super-tab-like keyset are slightly different. More specifically, my goal is to have `<Tab>` to `select_next -> snippet forward -> fallback`. Or rather, I'd prefer `<Tab>` to always select the next item **if the completion menu is open** (doesn't matter if I'm inside a snippet or not). 

The problem is that no matter what I do, if I configure `<Tab>` to `snippet_forward` and I'm inside a snippet, **it always takes precedence over `select_next`**.

Here's my keymap section:

```lua
keymap = {
    ["<CR>"] = { "accept", "fallback" },
    ["<Tab>"] = {
        "select_next",
        "snippet_forward",
        "fallback",
    },
    ["<S-Tab>"] = {
        "select_prev",
        "snippet_backward",
        "fallback",
    },
    ["<C-space>"] = { "show", "show_documentation", "hide_documentation" },
    ["<C-e>"] = { "hide" },
    ["<C-u>"] = { "scroll_documentation_up", "fallback" },
    ["<C-d>"] = { "scroll_documentation_down", "fallback" },
}
```

With nvim-cmp, I could use something like:

```lua
["<Tab>"] = cmp.mapping(function(fallback)
    if cmp.visible() then
        cmp.select_next_item()
    elseif luasnip.jumpable(1) then
        luasnip.jump(1)
    else
       ...
```

**Comment by Saghen** [comment]
That's bizarre, do you mind create a separate issue for this? I'm not able to reproduce on `main`

**Comment by weilbith** [comment]
Sorry, stupid question from the side:
Can I define my keymaps just manually without the `setup` function of the plugin?

**Comment by Saghen** [comment]
You can but you'll need to handle the fallback yourself and make sure that your keymaps don't get overridden. We apply on `InsertEnter` to avoid i.e. mini.pairs (on <CR>) from overriding blink's binds. The fallback logic is complicated, you can find it in `keymap.lua`

**Comment by weilbith** [comment]
That's no issue. I actually have an abstraction layer for completion (which for example takes care of integration with snippets etc.). So I just connect `blink.cmp` to this "interface" and done.  
I'll just look into the source code to figure out which functions I need to call. When they are publicly accessible in the Lua modules I'm happy. 🙃
