### ISSUE TITLE
Failed to run config using default config

### ISSUE THREAD

**Issue by Slepzs** [Saghen/blink.cmp#134]
{
    "saghen/blink.cmp",
    opts = {
      highlight = {
        use_nvim_cmp_as_default = true,
      },
      -- experimental auto-brackets support
      accept = { auto_brackets = { enabled = true } },

      -- experimental signature help support
      trigger = { signature_help = { enabled = true } },
    },
  },

<img width="931" alt="image" src="https://github.com/user-attachments/assets/3b7a4955-2c40-4137-9806-81227b9dc2d7">

**Comment by chrisgrieser** [comment]
you need to add `version = 'v0.*'`, since only the tagged versions contain the binary needed for blink.cmp. If you leave it out, you will have to build the binary itself, as documented in the readme

**Comment by Saghen** [comment]
Chris's comment is correct as well but this specific error seems to come from running an unsupported neovim version. Try running `nvim --version` to confirm that you're on `v0.10.0+`

**Comment by Saghen** [comment]
Closing as not planned since it seems like an issue with your environment but don't hesitate to comment if you're still having trouble!
