### ISSUE TITLE
Lua LSP's `@param;@return` suggestions not picked up

### ISSUE THREAD

**Issue by chrisgrieser** [Saghen/blink.cmp#135]
The lua LSP has a very useful luadocs annotation, typing `---` in the line before a function will result in a `@param;@return` suggestions that autofills a lot of function annotations for you. 

However, this suggestion does not seem to work for blink.cmp. It's just one suggestion, but a frequently used and important one, since it is the only method to somewhat auto-generate function annotations.

I tried fiddling with `opts.triggers.completion.keyword_regex`, and `-` does work correctly as trigger character (and is already configured as one in the default config), so the fact that the suggestion is triggered via `---` should not be the issue here. Thus, I assume the issue lies with blink.cmp somehow not picking this suggestions from the lua LSP.

**Comment by Saghen** [comment]
We were filtering on the `---` which led to no matches. I've excluded `-` if it comes at the beginning of the keyword, which I don't believe should break other uses cases

**Comment by chrisgrieser** [comment]
Sorry to bother you, but this has not been fixed yet. I just switched to 0.4.0, and there still is no `@param;@return` suggestion when typing `---`.

**Comment by Saghen** [comment]
Sorry about that, got broken again while reworking that code. Should be fixed in v0.4.1
