### ISSUE TITLE
Unable to use local `blink.cmp` using `lazy.nvim` - Error while downloading blink.cmp pre-built binary: Can't download from...

### ISSUE THREAD

**Issue by Drew-Daniels** [Saghen/blink.cmp#137]
I am trying to configure `lazy.nvim` to use a local version of `blink.cmp` so I can test something locally, but I'm getting this error with my configuration:

<img width="1511" alt="image" src="https://github.com/user-attachments/assets/c92b19b3-269c-4fa1-8591-065b23f143f1">

Here is my configuration:

```lua
return require("lazy").setup({
  {
    "saghen/blink.cmp",
    lazy = false,
    dependencies = "rafamadriz/friendly-snippets",
    dir = "~/projects/blink.cmp",
    url = "https://github.com/Saghen/blink.cmp",
    dev = true,
    -- version = "v0.*",
    build = "cargo build --release",
  },
})
```

I have followed the docs [here](https://rust-lang.github.io/rustup/concepts/channels.html#working-with-nightly-rust) to ensure that I have `rustc nightly` installed, and set this as the default:
```sh
❯ rustup default nightly
info: using existing install for 'nightly-aarch64-apple-darwin'
info: default toolchain set to 'nightly-aarch64-apple-darwin'

  nightly-aarch64-apple-darwin unchanged - rustc 1.84.0-nightly (3ed6e3cc6 2024-10-17)
```

I have also tried uncommenting `version`, but I run into the same issue:
```lua
return require("lazy").setup({
  {
    "saghen/blink.cmp",
    lazy = false,
    dependencies = "rafamadriz/friendly-snippets",
    dir = "~/projects/blink.cmp",
    url = "https://github.com/Saghen/blink.cmp",
    dev = true,
    version = "v0.*",
    build = "cargo build --release",
  },
})
```

Looking into why this could be happening, but thought I'd post an issue in case others ran into the same problem

**Comment by Saghen** [comment]
On `lazy.nvim` with `dev = true`, you must manually run `cargo build --release`

**Comment by Drew-Daniels** [comment]
> On `lazy.nvim` with `dev = true`, you must manually run `cargo build --release`

I see - that fixed it, thanks!
