### ISSUE TITLE
Command mode completion

### ISSUE THREAD

**Issue by mcauley-penney** [Saghen/blink.cmp#138]
I use completion to firstly discover things and only secondly to actually help write more easily. Command mode completion helps me discover vim functions and documentation. This feature feels massively important. VSCode obviously has completion for the command palette and Emacs offers this through plugins. It feels like a well-established feature in powerful editors.

**Comment by johnazule** [comment]
I would love to see this aswell, especially migrating from nvim-cmp

**Comment by Saghen** [comment]
Open to contributions for this but I don't have the bandwidth to work on it for the time being. If anyone has insight into how nvim-cmp does this, please lmk!
