### ISSUE TITLE
Feature Request: Options to turn off preselect

### ISSUE THREAD

**Issue by BrianNormant** [Saghen/blink.cmp#14]
I've read the default config and took a look at the code, but I didn't find a way to disable the preselection. The moment the completion window shows, it automatically select the first item.

My usecase is quite simple, I bind the accept to <CR>, so that I don't have to cancel the selection whenever I want to add line, if I want to accept a completion I select it with <Tab> then press <CR>.

with nvim-cmp, you can do this with opts.preselect = cmp.PreselectMode.None

**Comment by calops** [comment]
To expand on this, one behavior I would like to be able to setup: only enable the `accept` binding when there's an active selection. That way, we can use `<Cr>` as the acceptation key without it being annoying whenever we want to insert a newline with the completion menu open.

**Comment by Saghen** [comment]
Closed by #24

**Comment by BrianNormant** [comment]
> To expand on this, one behavior I would like to be able to setup: only enable the `accept` binding when there's an active selection. That way, we can use `<Cr>` as the acceptation key without it being annoying whenever we want to insert a newline with the completion menu open.

That's how it works, If preselect is disabled, The completion menu will shows but no item will be selected. When you want to accept a suggestion, you have to first press the selectnext/prev (Usually bound to tab/S-tab) and press the accept <cr>. But as long as no item is selected, the accept key will work normally.

**Comment by sQVe** [comment]
I'm probably missing something but disabling `preselect` does not seem to work. I have the following in my  config:

```
  windows = {
    autocomplete = {
      preselect = false,
    },
  },

```
