### ISSUE TITLE
Cursor Does Not Move to Next Snippet Placeholder Position When Accepting a Completion Within a Snippet Placeholder Node

### ISSUE THREAD

**Issue by Drew-Daniels** [Saghen/blink.cmp#148]
I noticed an issue when using snippets, like the one I have for `.json` files:

```json
{
  "Property": {
    "body": "\"${1:KEY}\": ${2:VALUE}",
    "prefix": "pr",
    "description": "A JSON Object Property"
  }
}
```

If I am typing within the first snippet node, and see a completion come up that I would like to use, like `language`, if I accept that completion, I exit the snippet, and can't jump to the next node of the snippet.

<img width="352" alt="path  fish json" src="https://github.com/user-attachments/assets/6fd3ab32-23fa-4692-a14a-1f7ccaeddf80">

<br>

<img width="331" alt="image" src="https://github.com/user-attachments/assets/18b276e9-a8e6-4efc-932c-264a64aa413d">

Instead of this, I would expect for me to jump to the next node, like this:

<img width="488" alt="path" src="https://github.com/user-attachments/assets/644e1ab0-a5d9-4b5c-8dff-096404348a05">

**Comment by Saghen** [comment]
I can't handle all cases since accepting a `snippet` completion item will call `vim.snippet.expand` which replaces the current snippet context. However, the buffer source was incorrectly marking its items as snippets which caused the issue for this specific case
