### ISSUE TITLE
Feature request: Insert completion item word while navigating the item list 

### ISSUE THREAD

**Issue by MariaSolOs** [Saghen/blink.cmp#150]
Something nice about built-in completion in (neo)vim is being able to navigate the completion list and having the completion item's `word` inserted without having first to accept the item. This way one can easily continue typing :)

It would be great to have this feature in `blink.cmp` too!

**Comment by Saghen** [comment]
Sounds like you're looking for `windows.autocomplete.selection = 'auto_insert'`

**Comment by MariaSolOs** [comment]
Oh my yes! I missed this in the docs :(
