### ISSUE TITLE
Broken highlights

### ISSUE THREAD

**Issue by idelice** [Saghen/blink.cmp#152]
After enabling this plugin, all my highlights are broken.

I've tried following the instructions to keep nvim-cmp highlights as fallback in case my theme (Cyberdream) doesn't support it:

```lua
    highlight = {
      ns = vim.api.nvim_create_namespace("blink_cmp"),
      use_nvim_cmp_as_default = true,
    },
```

It didn't do anything "different".

How do I keep my highlights _and_ the same time use this plugin?

**Comment by Saghen** [comment]
I can't imagine how this would be caused by `blink.cmp`, you can view the relevant code here https://github.com/Saghen/blink.cmp/blob/main/lua/blink/cmp/init.lua#L89. Perhaps there's an error during startup that's preventing your theme from loading?

**Comment by idelice** [comment]
> I can't imagine how this would be caused by `blink.cmp`, you can view the relevant code here https://github.com/Saghen/blink.cmp/blob/main/lua/blink/cmp/init.lua#L89. Perhaps there's an error during startup that's preventing your theme from loading?

i'm getting no errors whatsoever. 

if i disable blink.cmp, the issue is gone.
if i enable blink.cmp, the issue is there again.

i haven't experienced this with any of the 20+ other plugins, so it's weird.

another thing i've noticed..whenever i'm using this plugin and save my buffer, a notification comes up that asks me if i want to overwrite existing file:


<img width="797" alt="Screenshot 2024-10-21 at 09 53 16" src="https://github.com/user-attachments/assets/98503506-b11e-4ef4-99b3-5085c7f874a0">

if (again) i disable this plugin and save my buffer, this is not showing up anymore.

this is pretty weird

**Comment by idelice** [comment]
Seems like the issue is gone for some reason.. i switched back and fort with LazyVim's minimal repro, and changed my config in order to keep it simple:

``lua
return {
  "saghen/blink.cmp",
  lazy = false, -- lazy loading handled internally
  dependencies = "rafamadriz/friendly-snippets",
  version = "v0.*",
  opts = {
    windows = {
      documentation = {
        auto_show = true,
        auto_show_delay_ms = 50,
      },
      signature_help = {
        border = "border",
      },
    },
    keymap = {
      accept = "<Enter>",
      select_prev = { "<Up>", "<C-k>" },
      select_next = { "<Down>", "<C-j>" },

      -- show_documentation = "<C-space>",
      -- hide_documentation = "<C-space>",
      -- scroll_documentation_up = "<C-b>",
      -- scroll_documentation_down = "<C-f>",
      --
      -- snippet_forward = "<Tab>",
      -- snippet_backward = "<S-Tab>",
    },
  },
}
```

so now i don't get broken highlights nor that confirmation window everytime i want to save/unsave buffer when leaving it
