### ISSUE TITLE
Formatting options

### ISSUE THREAD

**Issue by idelice** [Saghen/blink.cmp#156]
Here's a reference from a Java file:
<img width="511" alt="Screenshot 2024-10-21 at 14 21 45" src="https://github.com/user-attachments/assets/317e65d6-3cbd-41bd-9874-3999a837585f">

I would like to move the ordering of the symbols, text etc. around, and display the return types  instead of package names and what not.

Is there a way to format completion items like you can in nvim-cmp?

**Comment by Saghen** [comment]
You're looking for `windows.autocomplete.draw`

**Comment by idelice** [comment]
Config
```lua
      autocomplete = {
        min_width = 80,
        draw = function(entry)
          print("foo")
         //..
        end,
      },
```

Are you sure that this works? I'm getting:
```
Error executing vim.schedule lua callback: .../projects/blink.cmp/lua/blink/cmp/windows/lib/render.lua:126: attempt to perform arithmetic on a nil value
stack traceback:
	.../projects/blink.cmp/lua/blink/cmp/windows/lib/render.lua:126: in function 'get_max_lengths'
	...rojects/blink.cmp/lua/blink/cmp/windows/autocomplete.lua:274: in function 'draw'
	...rojects/blink.cmp/lua/blink/cmp/windows/autocomplete.lua:73: in function 'open_with_items'
	.../ibrahimdelice/projects/blink.cmp/lua/blink/cmp/init.lua:49: in function <.../ibrahimdelice/projects/blink.cmp/lua/blink/cmp/init.lua:46>
```

**Comment by Saghen** [comment]
Please read the existing draw functions and the function signature :)

**Comment by idelice** [comment]
I'm not sure I understand your documentation correctly.. can you please provide an example on how to use your implementation?

**Comment by JustBarnt** [comment]
@idelice 

```lua
draw = function(ctx)
    -- https://github.com/Saghen/blink.cmp/blob/819b978328b244fc124cfcd74661b2a7f4259f4f/lua/blink/cmp/windows/autocomplete.lua#L285-L349
    -- differentiate LSP snippets from user snippets and emmet snippets
    local icon, source = ctx.kind_icon, ctx.item.source
    local client = source == "LSP" and vim.lsp.get_client_by_id(ctx.item.client_id).name
    if source == "Snippets" or (client == "basics_ls" and ctx.kind == "Snippet") then
        icon = "󰩫"
    elseif source == "Buffer" or (client == "basics_ls" and ctx.kind == "Text") then
        icon = "󰦨"
    elseif client == "emmet_language_server" then
        icon = "󰯸"
    end

    -- FIX highlight for Tokyonight
    local iconHl = vim.g.colors_name:find("tokyonight") and "BlinkCmpKind"
    or "BlinkCmpKind" .. ctx.kind

    return {
        {
            " " .. ctx.item.label .. " ",
            fill = true,
            hl_group = ctx.deprecated and "BlinkCmpLabelDeprecated" or "BlinkCmpLabel",
            max_width = 45,
        },
        { icon .. ctx.icon_gap, hl_group = iconHl },
    }
end,
```

**Comment by idelice** [comment]
> @idelice
> 
> ```lua
> draw = function(ctx)
>     -- https://github.com/Saghen/blink.cmp/blob/819b978328b244fc124cfcd74661b2a7f4259f4f/lua/blink/cmp/windows/autocomplete.lua#L285-L349
>     -- differentiate LSP snippets from user snippets and emmet snippets
>     local icon, source = ctx.kind_icon, ctx.item.source
>     local client = source == "LSP" and vim.lsp.get_client_by_id(ctx.item.client_id).name
>     if source == "Snippets" or (client == "basics_ls" and ctx.kind == "Snippet") then
>         icon = "󰩫"
>     elseif source == "Buffer" or (client == "basics_ls" and ctx.kind == "Text") then
>         icon = "󰦨"
>     elseif client == "emmet_language_server" then
>         icon = "󰯸"
>     end
> 
>     -- FIX highlight for Tokyonight
>     local iconHl = vim.g.colors_name:find("tokyonight") and "BlinkCmpKind"
>     or "BlinkCmpKind" .. ctx.kind
> 
>     return {
>         {
>             " " .. ctx.item.label .. " ",
>             fill = true,
>             hl_group = ctx.deprecated and "BlinkCmpLabelDeprecated" or "BlinkCmpLabel",
>             max_width = 45,
>         },
>         { icon .. ctx.icon_gap, hl_group = iconHl },
>     }
> end,
> ```

Thanks!

**Comment by radutomy** [comment]
> > @idelice
> > ```lua
> > draw = function(ctx)
> >     -- https://github.com/Saghen/blink.cmp/blob/819b978328b244fc124cfcd74661b2a7f4259f4f/lua/blink/cmp/windows/autocomplete.lua#L285-L349
> >     -- differentiate LSP snippets from user snippets and emmet snippets
> >     local icon, source = ctx.kind_icon, ctx.item.source
> >     local client = source == "LSP" and vim.lsp.get_client_by_id(ctx.item.client_id).name
> >     if source == "Snippets" or (client == "basics_ls" and ctx.kind == "Snippet") then
> >         icon = "󰩫"
> >     elseif source == "Buffer" or (client == "basics_ls" and ctx.kind == "Text") then
> >         icon = "󰦨"
> >     elseif client == "emmet_language_server" then
> >         icon = "󰯸"
> >     end
> > 
> >     -- FIX highlight for Tokyonight
> >     local iconHl = vim.g.colors_name:find("tokyonight") and "BlinkCmpKind"
> >     or "BlinkCmpKind" .. ctx.kind
> > 
> >     return {
> >         {
> >             " " .. ctx.item.label .. " ",
> >             fill = true,
> >             hl_group = ctx.deprecated and "BlinkCmpLabelDeprecated" or "BlinkCmpLabel",
> >             max_width = 45,
> >         },
> >         { icon .. ctx.icon_gap, hl_group = iconHl },
> >     }
> > end,
> > ```
> 
> Thanks!

@idelice does this work for you? I've raised an issue yesterday https://github.com/Saghen/blink.cmp/issues/161 which seems quite similar to this one. Tried the code above, but it doesn't work for me (still shows package names instead of return type)

**Comment by idelice** [comment]
> > > @idelice
> > > ```lua
> > > draw = function(ctx)
> > >     -- https://github.com/Saghen/blink.cmp/blob/819b978328b244fc124cfcd74661b2a7f4259f4f/lua/blink/cmp/windows/autocomplete.lua#L285-L349
> > >     -- differentiate LSP snippets from user snippets and emmet snippets
> > >     local icon, source = ctx.kind_icon, ctx.item.source
> > >     local client = source == "LSP" and vim.lsp.get_client_by_id(ctx.item.client_id).name
> > >     if source == "Snippets" or (client == "basics_ls" and ctx.kind == "Snippet") then
> > >         icon = "󰩫"
> > >     elseif source == "Buffer" or (client == "basics_ls" and ctx.kind == "Text") then
> > >         icon = "󰦨"
> > >     elseif client == "emmet_language_server" then
> > >         icon = "󰯸"
> > >     end
> > > 
> > >     -- FIX highlight for Tokyonight
> > >     local iconHl = vim.g.colors_name:find("tokyonight") and "BlinkCmpKind"
> > >     or "BlinkCmpKind" .. ctx.kind
> > > 
> > >     return {
> > >         {
> > >             " " .. ctx.item.label .. " ",
> > >             fill = true,
> > >             hl_group = ctx.deprecated and "BlinkCmpLabelDeprecated" or "BlinkCmpLabel",
> > >             max_width = 45,
> > >         },
> > >         { icon .. ctx.icon_gap, hl_group = iconHl },
> > >     }
> > > end,
> > > ```
> > 
> > 
> > Thanks!
> 
> @idelice does this work for you? I've raised an issue yesterday #161 which seems quite similar to this one. Tried the code above, but it doesn't work for me (still shows package names instead of return type)

I've just quickly tried to see if I could format _anything_ at all.

I haven't added my personal formatting to it yet.. I'll probably do that in the next couple of days when I have more time between my hands.

But I hope I can reach the same formatting level as I've done with nvim-cmp:

![Uploading Screenshot 2024-10-22 at 17.25.22.png…]()

**Comment by radutomy** [comment]
Thanks. If you manage to figure it out, please do post the results here as well :)

**Comment by idelice** [comment]
> Thanks. If you manage to figure it out, please do post the results here as well :)

Here's how i extract the return type from methods and show it on the far right side of the window. the `returnType` variable is doing the magic here:

```lua
        draw = function(ctx)
          local icon = ctx.kind_icon
          local source = ctx.item.source_name
          local client = source == "LSP" and vim.lsp.get_client_by_id(ctx.item.client_id).name
          local returnType = ""

          if source == "LSP" and client == "jdtls" then
            if ctx.kind == "Method" then
              returnType = string.match(ctx.label, "%s*:%s*(%w+)")
            end
          end

          if source == "Buffer" or (client == "jdtls" and ctx.kind == "Text") then
            icon = "󰦨"
          end

          local iconHl = vim.g.colors_name:find("cyberdream") and "BlinkCmpKind" or "BlinkCmpKind" .. ctx.kind

          return {
            {
              icon .. ctx.icon_gap,
              hl_group = iconHl,
            },
            {
              " " .. ctx.label .. " ",
              fill = true,
              hl_group = ctx.deprecated and "BlinkCmpLabelDeprecated" or "BlinkCmpLabel",
              max_width = 80,
            },
            {
              " " .. returnType .. " ",
              fill = true,
            },
          }
        end,
```

Output
<img width="1318" alt="Screenshot 2024-10-28 at 11 52 02" src="https://github.com/user-attachments/assets/9794d53d-070b-439b-901b-a248937bc81f">

**Comment by radutomy** [comment]
Thank you! This looks exactly like what I want - would you mind posting your entire blink.cmp config?
