### ISSUE TITLE
Show return types

### ISSUE THREAD

**Issue by radutomy** [Saghen/blink.cmp#161]
Is there a way to show the return types instead of package names?

For example, in JetBrains Rider I can see the return type on the right, as well as the function's arguments:
![image](https://github.com/user-attachments/assets/dd54d102-c976-4343-a4d2-1be1e8d3b00a)

But in blink.cmp I only get the package name:
![image](https://github.com/user-attachments/assets/9aa8784a-488c-4d4a-ab03-422711be68c2)

**Comment by lopi-py** [comment]
Seems like you are looking for https://github.com/Saghen/blink.cmp/issues/97#issuecomment-2423300134
