### ISSUE TITLE
[bug] matching not working for capital letters

### ISSUE THREAD

**Issue by kaiphat** [Saghen/blink.cmp#162]
![image](https://github.com/user-attachments/assets/bc5382f3-2ac7-4dfe-9edb-4b3e34406d01)

For example with lowercase letters:
![image](https://github.com/user-attachments/assets/8fe12938-2b22-48be-b387-0a46e6e96ecc)

**Comment by Saghen** [comment]
I'm unable to reproduce this, can you provide more info?

![image](https://github.com/user-attachments/assets/12400b5a-761e-4922-a375-fa46e5352c68)

**Comment by kaiphat** [comment]
I found out that it happens if `use_typo_resistance = true`
