### ISSUE TITLE
improvements for fuzzy matching

### ISSUE THREAD

**Issue by kaiphat** [Saghen/blink.cmp#164]
I've came back:)

![image](https://github.com/user-attachments/assets/13d45bd6-1cc6-4178-a628-1b0ebf403cfc)

- `import` should be first because shorter

---

But here is okay

![image](https://github.com/user-attachments/assets/18616a70-4886-4ac1-b311-de90e973f7fe)

**Comment by Saghen** [comment]
It seems to already be prioritizing shorter items on my system. Have you accepted `importScripts` in the past? That would give it a boost unless you set `fuzzy.use_frecency = false`

![image](https://github.com/user-attachments/assets/b9b968da-1e5b-4e43-9f73-e7629b52e233)

**Comment by kaiphat** [comment]
Probably you are right. I thought that `blink` save frecency only inside one nvim session. Thank you!
