### ISSUE TITLE
[bug] snippets in property autocompletion

### ISSUE THREAD

**Issue by kaiphat** [Saghen/blink.cmp#167]
My config:

```lua
		sources = {
			providers = {
				{
					'blink.cmp.sources.snippets',
					name = 'Snippets',
					score_offset = 1,
					opts = {
						friendly_snippets = false,
						search_paths = { vim.fn.stdpath 'config' .. '/snippets' },
						global_snippets = { 'all' },
						extended_filetypes = {},
						ignored_filetypes = {},
					},
				},
				{ 'blink.cmp.sources.lsp', name = 'LSP', score_offset = 0 },
				{ 'blink.cmp.sources.path', name = 'Path', score_offset = 3 },
				{ 'blink.cmp.sources.buffer', name = 'Buffer', fallback_for = { 'LSP' } },
			},
		},
```

When i try to select property i see snippets here:

![image](https://github.com/user-attachments/assets/43ea62f8-076b-4c3c-8ac9-69d821f78c0a)

**Comment by kaiphat** [comment]
Duplicate

**Comment by Saghen** [comment]
This behavior is expected, although with your current configuration with `score_offset = 1` on snippets, the snippets are getting boosted above the LSP results

**Comment by kaiphat** [comment]
But snippets look completely unusable in dot completion... It's weird

**Comment by Saghen** [comment]
Yeah I agree but there isn't a universal solution for it. Eventually I'd like to intelligently disable snippets via treesitter but that's much further down the road

**Comment by kaiphat** [comment]
Okay, thank you!
