### ISSUE TITLE
Allow disabling filetype for treesitter highlighting

### ISSUE THREAD

**Issue by NicoElbers** [Saghen/blink.cmp#171]
I personally don't use the Zig treesitter parser because for me it causes unreasonable delays. However, blink will try to create a parser when showing documentation, creating a very annoying error. 

Therefore I'd personally like for it to be possible to disable certain treesitter filetypes, falling back on regex parsing instead. 

I am not super familiar with Lua development, but I think maybe a pcall on the `get_parser` function may also allow catching the error (and then fall back on regex parsing).

**Comment by Saghen** [comment]
Not falling back to regex for now but this should at least unblock your use case. It might be best to allow treesitter on the documentation window and not on your code. It _should_ be extremely fast on such a small amount of code (3-6ms on my system)
