### ISSUE TITLE
Something wrong with the filter

### ISSUE THREAD

**Issue by niuiic** [Saghen/blink.cmp#172]
Create a lua file. Edit `local path = ""`. In the quotes, type '~/', get path completions, and there is a path named `Documents`. Then type 'D'，completions disapeared.

![image](https://github.com/user-attachments/assets/7a69d439-9465-4e7a-864d-68b0c09b233d)

![image](https://github.com/user-attachments/assets/1dce6c1e-5a5b-4572-bc33-478870e5e9de)

**Comment by Saghen** [comment]
Duplicate #162

**Comment by niuiic** [comment]
Not the same. This also happen in vue files. In quotes, no completions shown.

![image](https://github.com/user-attachments/assets/c7897dbc-e071-4b6b-b235-22e71b3abfce)

**Comment by niuiic** [comment]
Outside of quotes, it works.

**Comment by Saghen** [comment]
Are you using `use_typo_resistance = true`? I'm unable to replicate since https://github.com/Saghen/blink.cmp/commit/722b41b0a7028581004888623f3f79c1d9eab8b8

**Comment by niuiic** [comment]
Just use the default config

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Saghen** [comment]
Have you retested with the above commit?
