### ISSUE TITLE
[bug] autocompletion not working in scenario

### ISSUE THREAD

**Issue by kaiphat** [Saghen/blink.cmp#173]
https://github.com/user-attachments/assets/fdf6636c-0309-4e07-a857-97e7da3e0e20

**Comment by kaiphat** [comment]
I even can't trigger with `keymap.show` calling.

**Comment by sQVe** [comment]
I'm having this issue with TypeScript too.

**Comment by kaiphat** [comment]
Problem looks fixed if to enable `use_typo_resistance = true`
