### ISSUE TITLE
Accept error (missing textEdit.range)

### ISSUE THREAD

**Issue by 3rd** [Saghen/blink.cmp#178]
Hi, I've been hitting this weird issue where `textEdit.range` is nil when selecting a completion.
I never manager to hit it when working with Lua, but when working with TypeScript it's frequent.
Thank you for all the work!

https://github.com/user-attachments/assets/de12ef1d-e3da-4a45-9218-6fa805f558d9

**Comment by Saghen** [comment]
This might be #21

**Comment by 3rd** [comment]
Ah I tried, I just checked `textDocument.completion.completionItem` for all the LSPs.

```
"cssmodules_ls"
{
  commitCharactersSupport = false,
  deprecatedSupport = false,
  documentationFormat = { "markdown", "plaintext" },
  insertReplaceSupport = false,
  preselectSupport = false,
  snippetSupport = false
}
"eslint"
{
  commitCharactersSupport = false,
  deprecatedSupport = false,
  documentationFormat = { "markdown", "plaintext" },
  insertReplaceSupport = false,
  preselectSupport = false,
  snippetSupport = false
}
"tailwindcss"
{
  commitCharactersSupport = false,
  deprecatedSupport = false,
  documentationFormat = { "markdown", "plaintext" },
  insertReplaceSupport = false,
  preselectSupport = false,
  snippetSupport = false
}
"typescript-tools"
{
  commitCharactersSupport = false,
  deprecatedSupport = false,
  documentationFormat = { "markdown", "plaintext" },
  preselectSupport = false,
  snippetSupport = false
}
"ast_grep"
{
  commitCharactersSupport = false,
  deprecatedSupport = false,
  documentationFormat = { "markdown", "plaintext" },
  insertReplaceSupport = false,
  preselectSupport = false,
  snippetSupport = false
}
"lua_ls"
{
  commitCharactersSupport = false,
  deprecatedSupport = false,
  documentationFormat = { "markdown", "plaintext" },
  insertReplaceSupport = false,
  preselectSupport = false,
  snippetSupport = false
}
```

**Comment by Saghen** [comment]
My best guess is the LSP is returning a `itemDefaults.editRange` which I have yet to add support for. Do me a favor and send the output of this snippet at the position where the error occurs:

```
vim.lsp.buf_request_all(
  0,
  'textDocument/completion',
  vim.lsp.util.make_position_params(),
  function(result) vim.print(result) end
)
```

The LSP shouldn't be sending this since we don't advertise support but some LSPs seem to ignore that bit of the spec :smile:

**Comment by 3rd** [comment]
Logged it here: https://gist.ro/blink.txt

The weird part is that it only happens when the completion menu shows up after `.`, but if I type any prefix like `.f|` everything works fine :eyes:

**Comment by Saghen** [comment]
Reproduced it with `typescript-tools` and this looks to be the same as #21. You might want to use `ts_ls` or `vtsls` temporarily

**Comment by Saghen** [comment]
Scratch that, it was surprisingly trivial to workaround this temporarily

**Comment by 3rd** [comment]
Works great, thank you!
