### ISSUE TITLE
BUG: Input word mirrored in statusline

### ISSUE THREAD

**Issue by sQVe** [Saghen/blink.cmp#179]
👋,

There's currently a bug that outputs the current word to the statusline. It is fairly eyecatching and distracting.

![image](https://github.com/user-attachments/assets/038a346a-630d-4388-883d-4439a4a61b11)

**Comment by giuxtaposition** [comment]
For those that want to temporarily fix it themselves while waiting for the official fix:
it's in the `lua/blink/cmp/fuzzy/init.lua` file
Just remove this line: 
```lua
vim.print(string.sub(line, range[1], range[2]))
```

**Comment by Shougo** [comment]
Oh, it is debug log.

**Comment by Saghen** [comment]
Shit, my cave man debugging has been exposed :smile: Sorry about that, I ought to get a pre-commit hook setup
