### ISSUE TITLE
Snippet parsing fails on php files

### ISSUE THREAD

**Issue by alanfzf** [Saghen/blink.cmp#184]
Blink info:
- Commit: c218faf

Video proof:

https://github.com/user-attachments/assets/af1e8991-86b6-4e52-9dfb-90846082c445

**Comment by Saghen** [comment]
Afaict, blink doesn't break the snippet and passes it directly to `vim.snippet.expand`. The built-in `vim.snippet.expand` is throwing the error so either the snippet is invalid or there's a bug upstream
