### ISSUE TITLE
Buffer completion messed up

### ISSUE THREAD

**Issue by Rentib** [Saghen/blink.cmp#185]
![2024-10-24_21:32:33](https://github.com/user-attachments/assets/5c3a6f49-6ba2-4b34-905a-e74ac6345bf2)
`<tab>`
![2024-10-24_21:32:42](https://github.com/user-attachments/assets/0c91cb1d-a9b7-4bea-b651-c3dfa77aa96c)

Instead of getting *rentib* after completion I get *rrentib*. Here I used default configuration of blink provided in the README.
(I don't really know, what to name this issue)

**Comment by Saghen** [comment]
Are you using `main` or a version tag?

**Comment by Rentib** [comment]
Main

**Comment by Rentib** [comment]
Config:
```lua
return {
    'saghen/blink.cmp',
    lazy = false,
    -- dependencies = 'rafamadriz/friendly-snippets',
    build = 'cargo build --release',
    opts = {},
}
```

Steps to reproduce:
- open a lua file
- write a comment with some random word to provide for buffer completion, let's say "buffer"
- write `require("b`
- tab

File:
```lua
-- buffer

require("bu
```
(bu in require must be written by hand - not pasted - for bug to occur)

**Comment by Saghen** [comment]
This appears to be an issue with Lua language server itself so you might want to report it upstream. The `textEdit` doesn't include the final character on the line
