### ISSUE TITLE
Documentation window north of the completion window covers text

### ISSUE THREAD

**Issue by chrisgrieser** [Saghen/blink.cmp#194]
When the documentation window is placed north of the completion window, it covers up the actual text you are currently typing. I assume this is due to an off-by-one error, since placing it one cell further above should fix the issue?

![Pasted image 2024-10-25 at 15 59 56@2x](https://github.com/user-attachments/assets/7ba90799-38b8-4c99-9da5-efc86a7da584)

**Comment by Saghen** [comment]
I'm unable to reproduce on `v0.5.0` but lmk if you're still able to reproduce it, ideally with steps

**Comment by chrisgrieser** [comment]
Well, it still happens with 0.5.0. It happens with the default config, and occurs any time when the autocompletion suggestions are **south** and the documentation window is shown **north**.

Reproduction steps for the conditions to happen:
1. set `scrolloff` to 0 and resize the terminal window so it is smaller to simply things.
2. go to a new line
3. press `<space>` until the cursor is in the middle of the screen.
4. Use `<C-e>` / `<C-y>` to position the viewport in a way that the cursor is in the middle bottom of the viewport.
5. type anything gives suggestions
6. `<C-space>` to open the suggestions. The suggestions must show up south of the cursor.
7.  `<C-space>` again to show the documentation window. If the cursor is positioned correctly in the previous steps, the documentation window should up north.
8. Issue occurs.

![Pasted image 2024-10-30 at 19 25 48@2x](https://github.com/user-attachments/assets/b2c884d9-271e-4fa7-ba99-a5fa7bd23634)
