### ISSUE TITLE
Performance drop in Normal mode

### ISSUE THREAD

**Issue by MinhTran0911** [Saghen/blink.cmp#199]
When I enable blink.cmp, I notice there’s a noticable performance drop in Neovim, especially when moving around in Normal mode, compared to nvim-cmp. I assume completion plugins should only be active in Insert mode. Is there any performance-related configuration that I can tweak?

**Comment by Saghen** [comment]
The plugin shouldn't be doing anything outside of insert mode. Please send profiling data and any other relevant info
