### ISSUE TITLE
Implement `auto_show` on trigger

### ISSUE THREAD

**Issue by haunt98** [Saghen/blink.cmp#204]
### Make sure you have done the following

- [X] I have updated to the latest version of `blink.cmp`
- [X] I have read the README

### Bug Description

First I try to complete line with `c-x c-n`, then I press `<up>`, then I see blink.cmp overlapse with nvim completion.

[![asciicast](https://asciinema.org/a/684865.svg)](https://asciinema.org/a/684865)

### Relevant configuration

```lua
keymap = {
				select_and_accept = { "<CR>" },
			},
			windows = {
				autocomplete = {
					auto_show = false,
				},
			},
			nerd_font_variant = "mono",
```

### neovim version

NVIM v0.10.2

### `blink.cmp` version: branch, tag, or commit

v0.4.1

**Comment by Saghen** [comment]
Seems like we should replace the `autocomplete.auto_show` with a `trigger.completion.auto_show`. I'll use this issue to track it

**Comment by Saghen** [comment]
Closed by https://github.com/Saghen/blink.cmp/commit/11871727278381febd05d1ee1a17f98fb2e32b26
