### ISSUE TITLE
useState snippet error

### ISSUE THREAD

**Issue by AlejandroSanchez90** [Saghen/blink.cmp#207]
### Make sure you have done the following

- [X] I have updated to the latest version of `blink.cmp`
- [X] I have read the README

### Bug Description

I'm trying out blink everything is working properly, but one snippet is giving me this error

```shell
Error executing vim.schedule lua callback: ...10.1/share/nvim/runtime/lua/vim/lsp/_snippet_grammar.lua:177: snippet parsing failed
stack traceback:
	[C]: in function 'assert'
	...10.1/share/nvim/runtime/lua/vim/lsp/_snippet_grammar.lua:177: in function 'parse'
	...lar/neovim/0.10.1/share/nvim/runtime/lua/vim/snippet.lua:417: in function 'expand'
	.../share/nvim/lazy/blink.cmp/lua/blink/cmp/accept/init.lua:30: in function <.../share/nvim/lazy/blink.cmp/lua/blink/cmp/accept/init.lua:6>
	...im/lazy/blink.cmp/lua/blink/cmp/windows/autocomplete.lua:173: in function 'accept'
	.../.local/share/nvim/lazy/blink.cmp/lua/blink/cmp/init.lua:142: in function <.../.local/share/nvim/lazy/blink.cmp/lua/blink/cmp/init.lua:142>
```

this is when I try to use the state snippet for React. Other snippets work perfectly, but this is the one I use the most, and it's not working, I'm using the default blink config

### neovim version

10.1

### `blink.cmp` version: branch, tag, or commit

0.4.1

**Comment by fredrikaverpil** [comment]
Hi @Saghen 👋  and many thanks for this wonderful plugin!

I was wondering if you can give me a pointer on why I'm getting this "snippet grammar" error regardless of whether I use the defaults or whether I set up luasnip:

https://github.com/user-attachments/assets/6f34007f-d46e-407f-abf8-006dc98358e0

I hit enter (`<CR>`) when I choose the snippet (like I do when I accept a completion). I am using the default `expand_snippet = vim.snippet.expand` setting. But I've also tried to replace that with `expand_snippet = require("luasnip").lsp_expand` although it gives me that same error.

I can't quite figure out what I'm doing wrong here 🤔

* My blink config: https://github.com/fredrikaverpil/dotfiles/blob/main/nvim-fredrik/lua/plugins/blink.lua
* My keymaps: https://github.com/fredrikaverpil/dotfiles/blob/197dd0cc8f0aa98c37ab448553c8b5bd09568a19/nvim-fredrik/lua/config/keymaps.lua#L297-L313

**Comment by fredrikaverpil** [comment]
@Saghen hi again, so perhaps there's something afoot with the `err~` snippet (for go). A lot of other snippets works great, but this particular one (which is also very, very useful) does not work. 🤔

**Comment by fredrikaverpil** [comment]
Sorry for the noise. It was an upstream issue, it seems. I filed a PR: https://github.com/rafamadriz/friendly-snippets/pull/522
