### ISSUE TITLE
Navigating suggestions with `<C-n>, <C-p>` does not work properly

### ISSUE THREAD

**Issue by kedom1337** [Saghen/blink.cmp#210]
### Make sure you have done the following

- [X] I have updated to the latest version of `blink.cmp`
- [X] I have read the README

### Bug Description

When navigating between the completion suggestions with `<C-n>, <C-p>` the panel and therefor the selection breaks.
It seems to open another suggestion panel and then navigate in that? This video probably dose a better job at explaining what I mean:
[blink_bug.webm](https://github.com/user-attachments/assets/320a9c62-8a3d-4933-a2d7-ba42557c043d)

### Relevant configuration

```lua
return {
  "saghen/blink.cmp",
  build = "cargo build --release",
  opts = {
    keymap = {
      ["<cr>"] = { "select_and_accept", "fallback" },
    },
    highlight = {
      use_nvim_cmp_as_default = true,
    },
    accept = {
      auto_brackets = { enabled = true },
    },
    trigger = {
      signature_help = { enabled = true },
    },
  },
}
```

### neovim version

NVIM v0.10.2 Build type: RelWithDebInfo LuaJIT 2.1.1725453128 Run "nvim -V1 -v" for more info

### `blink.cmp` version: branch, tag, or commit

main

**Comment by Saghen** [comment]
When not using a preset, you have to define all the keys you'd like to configure. You can copy the preset from the README's default configuration section. I'll make this more clear in the docs

**Comment by kedom1337** [comment]
That makes sense, thanks. It would be cool to have some sort of helper function to merge the preset with your custom overwrites something like in `nvim-cmp`:
```lua
mapping = cmp.mapping.preset.insert({
  ["<cr>"] = cmp.mapping.confirm({
    behavior = cmp.ConfirmBehavior.Replace,
    select = true,
  })
}),

```

I feel like this would be more in line with the "Works out of the box with no additional configuration" goal of the plugins.
