### ISSUE TITLE
"cancel" action that is distinct from "hide"

### ISSUE THREAD

**Issue by djdv** [Saghen/blink.cmp#215]
This might make more sense visually: https://youtu.be/AaoAj_5geOw

With `auto_insert` enabled, if I tab through a selection the text will be inserted automatically into the buffer, and if I hide the selection the text remains.
That seems right to me, but I'd also like an action which cancels the selection and removes the automatically inserted text.
This is especially desirable for multiline snippets.

<details>
<summary>config</summary>

```lua
{
	'saghen/blink.cmp',
	lazy = false, -- lazy loading handled internally
	dependencies = 'rafamadriz/friendly-snippets',
	build = 'cargo build --release',
	---@module 'blink.cmp'
	---@type blink.cmp.Config
	opts = {
		keymap = {
			['<Tab>'] = { 'select_next', 'snippet_forward', 'fallback' },
			['<Down>'] = { 'select_next', 'snippet_forward', 'fallback' },

			['<C-space>'] = { 'show', 'show_documentation', 'hide_documentation' },
			['<C-e>'] = { 'hide' },
			['<C-y>'] = { 'select_and_accept' },

			['<CR>'] = { 'accept', 'fallback' },
			['<Space>'] = { 'accept', 'fallback' },

			['<S-Tab>'] = { 'select_prev', 'snippet_backward', 'fallback' },
			['<Up>'] = { 'select_prev', 'snippet_backward', 'fallback' },
			['<C-p>'] = { 'select_prev', 'fallback' },
			['<C-n>'] = { 'select_next', 'fallback' },

			['<C-b>'] = { 'scroll_documentation_up', 'fallback' },
			['<C-f>'] = { 'scroll_documentation_down', 'fallback' },
		},
		windows = {
			autocomplete = {
				border = 'double',
				selection = 'auto_insert'
			},
		},
		documentation = {
			border = 'double'
		},
		signature_help = {
			border = 'double'
		},
		highlight = {
			use_nvim_cmp_as_default = true
		},
		nerd_font_variant = 'mono',
		accept = { auto_brackets = { enabled = true } },
		trigger = { signature_help = { enabled = true } }
	}
}
```

</details>

**Comment by Shougo** [comment]
It seems builtin `<C-e>` feature instead of `<C-y>`.

**Comment by djdv** [comment]
>It seems builtin `<C-e>` feature instead of `<C-y>`.

with `windows = { autocomplete = { selection = 'auto_insert' } }` the text is inserted into the buffer without invoking `<C-y>`.
Pressing `<C-e>` at this point will hide the popup menu, but the inserted text will remain.


While using cmp, I had separate triggers for [`cmp.close`](https://github.com/hrsh7th/nvim-cmp/blob/29fb4854573355792df9e156cb779f0d31308796/doc/cmp.txt#L172-L173) and [`cmp.abort`](https://github.com/hrsh7th/nvim-cmp/blob/29fb4854573355792df9e156cb779f0d31308796/doc/cmp.txt#L175C2-L176).

**Comment by djdv** [comment]
I realized something related to this. There's some feature/overlap with "abort" and how selection cycling could be handled.

With the default cycle config
`windows = { autocomplete = { cycle = { from_bottom = true, from_top = true, } } },`
cycling through the popup menu can wrap around the end of the list, back to the first item.

In [hrsh7th/nvim-cmp](https://github.com/hrsh7th/nvim-cmp), my config was set up so that wrapping around the list reverted you back to the state you were in pre-selection, but without hiding the popup menu.
That is to say, moving selection to the next item while on the last item, is equivalent to "abort" without closing the menu.

Note that what I type in this video is `fmt.Print` and that gets restored when I tab past `fmt.Println` and does not hover me over suggestion 1.
Going through the suggested items in both directions you can see I wrap around to an invisible 0th entry representing the state I was initially in.

[tab cycling.webm](https://github.com/user-attachments/assets/dbb202c2-a819-41c7-8683-3175a616620c)


Maybe it's worth filing a separate request for different cycle handling, but in either case, either of these features would solve the issue of getting stuck in the selection menu.
Both of these features seem like they would depend on the same underlying code centered around abort's ability to restore the state.

**Comment by Saghen** [comment]
#389 should match the behavior of nvim-cmp for wrapping around and https://github.com/Saghen/blink.cmp/commit/c58b3a8ec2cd71b422fbd4b1607e924996dfdebb added a `cancel` command
