### ISSUE TITLE
disable icons

### ISSUE THREAD

**Issue by hatredholder** [Saghen/blink.cmp#216]
add a `none` option to the `nerd_font_variant` to disable icons completely

**Comment by Saghen** [comment]
You might be looking for `windows.autocomplete.draw = 'minimal'` or you can override the `draw` function using one of these as reference

https://github.com/Saghen/blink.cmp/blob/6f0fc86f8fbb94ae23770c01dc2e3cf9e1886e99/lua/blink/cmp/windows/autocomplete.lua?plain=1#L332-L382

**Comment by adiSuper94** [comment]
> You might be looking for `windows.autocomplete.draw = 'minimal'` 

This no longer works. I'd love an easy way turn icons off.
@Saghen

**Comment by Saghen** [comment]
https://cmp.saghen.dev/configuration/completion.html#menu-draw

**Comment by Miyelsh** [comment]
@Saghen, silly question but what is the default draw columns? I see the example for comparable to nvim-cmp.

**Comment by saghen** [comment]
You can find it in the reference documentation: https://cmp.saghen.dev/configuration/reference#completion-menu-draw
