### ISSUE TITLE
Deselects after quickly pressing keys

### ISSUE THREAD

**Issue by jorgebef** [Saghen/blink.cmp#219]
### Make sure you have done the following

- [X] I have updated to the latest version of `blink.cmp`
- [X] I have read the README

### Bug Description

After using the plugin for some time, I've noticed that when using certain LSPs if a key is pressed and very quickly after the key assigned to `select_next` is pressed, instead of respecting the normal order of key presses, it acts as if the order of the presses is reversed.

My wild guess is that it is due to some async info coming in from the LSP and thus only happening in slower LSPs (typescript-language-server is the usecase I've noticed), for example, I've actively tried making it bug in lua_ls, but was not able to reproduce.

I attach a short video to illustrate, I hope it can show what I mean.

Steps to reproduce:
- Type usual part of string to trigger completion (e.g. in JSX, the string "classNa")
- Type one more letter and immediately afterwards the key set up as `select_next` (e.g. "m" and then "Tab")
- Visually, first the letter is typed, then first entry is selected, then deselected.
- 
If auto_insert is set, the visual effect is even more jarring as the insert is actually typed but when pressing `accept` the fallback happens instead of the intended action due to nothing being selected, and `select_and_accept` selects the first option and accepts due to nothing being selected.
[blink-cmp.webm](https://github.com/user-attachments/assets/febc5ae7-425d-4311-be6a-f8747b8ee6fb)

### Relevant configuration

```lua
keymap = {
      ["<C-space>"] = { "show", "hide" },
      ["<C-p>"] = { "select_prev", "fallback" },
      ["<C-n>"] = { "select_next", "fallback" },
      ["<CR>"] = { "accept", "fallback" },
      ["<Tab>"] = { "select_next" },
      ["<S-Tab>"] = { "select_prev" },
    },
```

### neovim version

NVIM v0.10.2

### `blink.cmp` version: branch, tag, or commit

commit 6f0fc86

**Comment by Saghen** [comment]
> My wild guess is that it is due to some async info coming in from the LSP and thus only happening in slower LSPs 

Your wild guess is on the dot :smile: If the item changes position after the new data comes in, would you expect the item to remain selected, or would you expect for your position within the list to be maintained?

**Comment by jorgebef** [comment]
> > My wild guess is that it is due to some async info coming in from the LSP and thus only happening in slower LSPs
> 
> Your wild guess is on the dot 😄 If the item changes position after the new data comes in, would you expect the item to remain selected, or would you expect for your position within the list to be maintained?

IMO, the selected item should remain selected.
I'm basing my decision on what `nvim-cmp` feels like, which is the de-facto standard plugin for completion right now.
Absolutely fantastic plugin by the way, love it!

**Comment by ste-goldstein** [comment]
I'm having this issue with blink-cmp + pyright LSP.
Is there any setting that I should be looking into ?
