### ISSUE TITLE
fuzzy failed with status 2

### ISSUE THREAD

**Issue by idelice** [Saghen/blink.cmp#22]
Sometimes, I'm receiving follow error when typing:

```
Error executing vim.schedule lua callback: ...al/share/nvim/lazy/blink.cmp/lua/blink/cmp/fuzzy/ffi.lua:377: fuzzy failed with status 2
stack traceback:
	[C]: in function 'error'
	...al/share/nvim/lazy/blink.cmp/lua/blink/cmp/fuzzy/ffi.lua:377: in function 'fuzzy'
	...l/share/nvim/lazy/blink.cmp/lua/blink/cmp/fuzzy/init.lua:44: in function 'filter_items_with_cache'
	.../.local/share/nvim/lazy/blink.cmp/lua/blink/cmp/init.lua:47: in function <.../.local/share/nvim/lazy/blink.cmp/lua/blink/cmp/init.lua:46>
```

**Comment by sam-carter-mcgrand** [comment]
Having the same issue, for reference the source of the error in rust seems to be
`panicked at lua/blink/cmp/fuzzy/ffi.rs:54`
`Result::unwrap()` on an `Err` value: PoisonError`

Not sure if it matters, but my lsp is `metals` and `nvim-metals` for scala

**Comment by lopi-py** [comment]
I'm having this issue when I use `clangd`
repro steps:
- `nvim main.cpp`
- wait 1 sec so clangd loads
- type `int ma`
- get the error

**Comment by Saghen** [comment]
I've fixed the issue from sam-carter-mcgrand in particular. If you're still running into issues, lmk and I'll re-open this
