### ISSUE TITLE
Ctrl-b/f dont seem to do anything in terms of scrolling documentation

### ISSUE THREAD

**Issue by Rishabh672003** [Saghen/blink.cmp#222]
### Make sure you have done the following

- [X] I have updated to the latest version of `blink.cmp`
- [X] I have read the README

### Bug Description

Pressing <C-f> or <C-b> doesn't seem to scroll documentation at all

https://github.com/user-attachments/assets/6801495f-5cf5-4607-986b-d336563d4fd4

### Relevant configuration

```lua
require("blink.cmp").setup({
    keymap = "default",
    -- experimental auto-brackets support
    accept = { auto_brackets = { enabled = true } },
    -- experimental signature help support
    trigger = { signature_help = { enabled = true } },

    windows = {
      documentation = {
        auto_show = true,
      },
    },
  })
```

### neovim version

NVIM v0.10.2

### `blink.cmp` version: branch, tag, or commit

v0.5.0

**Comment by Saghen** [comment]
It doesn't scroll because the entire documentation is already being shown in your examples
