### ISSUE TITLE
Assigning <CR> to accept makes me unable to enter new lines.

### ISSUE THREAD

**Issue by LasEmil** [Saghen/blink.cmp#224]
### Make sure you have done the following

- [X] I have updated to the latest version of `blink.cmp`
- [X] I have read the README

### Bug Description

I have a specific keymap configuration for autocompletion that I use on every editor/completion plugin. I use `<CR>` to accept autocompletion, but I disable automatic selection with `autocomplete = { selection = "manual"}` so I can select the completion myself.

With the newest release (0.5.0) if I set up the `["<CR>"] = { "accept" }` keymap it prevents the editor from creating new lines. It was working correctly with previous version and previous keymap configuration schema.

### Relevant configuration

```lua
opts = {
			keymap = {
				["<C-space>"] = { "show", "show_documentation", "hide_documentation" },
				["<CR>"] = { "accept" },
				["<C-e>"] = { "hide" },

				["<C-y>"] = { "select_and_accept" },

				["<Up>"] = { "select_prev", "fallback" },
				["<Down>"] = { "select_next", "fallback" },
				["<C-k>"] = { "select_prev", "fallback" },
				["<C-j>"] = { "select_next", "fallback" },

				["<C-b>"] = { "scroll_documentation_up", "fallback" },
				["<C-f>"] = { "scroll_documentation_down", "fallback" },

				["<Tab>"] = { "snippet_forward", "fallback" },
				["<S-Tab>"] = { "snippet_backward", "fallback" },
			},
			windows = {
				autocomplete = {
					selection = "manual",
				},
				documentation = {
					auto_show = true,
				},
			}
```

### neovim version

NVIM v0.10.1

### `blink.cmp` version: branch, tag, or commit

0.5.0

**Comment by sQVe** [comment]
@LasEmil You need to add the `fallback` to your `CR` binding.

**Comment by LasEmil** [comment]
@sQVe You are right, sorry, I was translating the configuration to a new keymap schema in a hurry.
