### ISSUE TITLE
Autocomplete intermittently stops working - .zshrc

### ISSUE THREAD

**Issue by jasmine-nguyen** [Saghen/blink.cmp#229]
### Make sure you have done the following

- [X] I have updated to the latest version of `blink.cmp`
- [X] I have read the README

### Bug Description

Sometimes when I hit tab in .zshrc file, autocomplete does not work. It does not select the selected option. In [this video](https://imgur.com/a/x5B2212), you can see when I hit tab when "tokyo.omp.json" is selected, it just inserts a blank space. In the middle of the video, when I tried to use up/down to move to the next suggestion, it jumps to the next line.

However, the next minute when I tried again, [it works](https://imgur.com/a/DiPqSDw). 

I have been trying a dozen times to see if I can catch a pattern, but it's pretty random. Happy to provide more details if needed.

Thanks @Saghen .
### Relevant configuration

```lua
return {
	"saghen/blink.cmp",
	event = { "LspAttach", "InsertCharPre" },
	version = "v0.*",
	opts = {
		accept = { auto_brackets = { enabled = true } },
		highlight = {
			use_nvim_cmp_as_default = true,
		},
		keymap = "super-tab",
		nerd_font_variant = "mono",
		windows = {
			autocomplete = {
				border = "single",
			},
			documentation = {
				auto_show = true,
				border = "single",
			},
		},
		trigger = {
			completion = {
				show_in_snippet = false,
			},
			signature_help = { enabled = true },
		},
	},
}
```

### neovim version

NVIM v0.10.2 Build type: Release LuaJIT 2.1.1727870382 

### `blink.cmp` version: branch, tag, or commit

"branch": "main", "commit": "917026450f5fa051cda9c538b517f0cf28ceec6f" },

**Comment by Saghen** [comment]
That's bizarre, my best guess would be that the lazy loading would mean we're missing the initial `InsertEnter` or one of your other plugins adds keymaps on `InsertEnter`, overriding blink's keymaps

**Comment by jasmine-nguyen** [comment]
Hey @Saghen , I think I found the pattern of the issue. This is the steps when it works: 

- Keep the .zshrc file open
- In another tab, make a change to the one of the plugins, forcing neovim to reload (when it says # Config Change Detected. Reloading...   )
- In the tab where .zshrc open, hit enter to accept the config change
- Try the autocomplete again, it works
- Save .zshrc file, exit.
- Open file again, try autocomplete, it does not work.

I have a recording [here](https://imgur.com/9uPkGZ1), hopefully it helps. If you need more info, let me know. Thank you @Saghen .
