### ISSUE TITLE
source doesn't complete if source it is fallback for is not enabled

### ISSUE THREAD

**Issue by stefanboca** [Saghen/blink.cmp#231]
### Make sure you have done the following

- [X] I have updated to the latest version of `blink.cmp`
- [X] I have read the README

### Bug Description

If a provider has a `fallback_for` on a source that is not in `enabled_providers`, that provider will not show any completions. For instance, in the config below, I was no longer getting any LSP completions.

### Relevant configuration

```lua
sources = {
  completion = {
    enabled_providers = { "lsp" }
  },
  providers = {
    lazydev = { name = "LazyDev", module = "lazydev.integrations.blink" },
    lsp = { fallback_for = { "lazydev" } },
  }
}
```

### neovim version

NVIM v0.11.0-dev+1068-g8df682250 Build type: RelWithDebInfo LuaJIT 2.1.1720049189

### `blink.cmp` version: branch, tag, or commit

88f1c20

**Comment by folke** [comment]
Just noticed as well.  See PR
