### ISSUE TITLE
Invalid keymap 'enter' error

### ISSUE THREAD

**Issue by Rhelvetican** [Saghen/blink.cmp#236]
### Make sure you have done the following

- [X] I have updated to the latest version of `blink.cmp`
- [X] I have read the README

### Bug Description

![image](https://github.com/user-attachments/assets/81c63cfd-a45c-4d6e-8485-ea032b4db078)

When I use the 'Enter' keymap it shows that error.

### Relevant configuration

```lua
{
		"saghen/blink.cmp",
		lazy = false,

		opts = {
			keymap = "enter",

			highlight = {
				use_nvim_cmp_as_default = true,
			},

			nerd_font_variant = "mono",

			windows = {
				documentation = {
					auto_show = true,
				},
			},
		},
	},
```

### neovim version

NVIM v0.10.2 Build type: Release LuaJIT 2.1.1713484068 Run "nvim -V1 -v" for more info

### `blink.cmp` version: branch, tag, or commit

main

**Comment by ilias777** [comment]
I have the same issue.

**Comment by larpon** [comment]
Same issue just installed via LazyVim just now

**Comment by stefanboca** [comment]
This looks like you're using an old version. `keymap.lua:83` in v0.5.0 is the line printing the error message you're getting (on the latest main, this message is on line 132, not 83)

**Comment by Saghen** [comment]
Thanks for confirming stefan!

**Comment by folke** [comment]
For LazyVim users, I just explicitely added `version=false` for now.
Will revert back to `version = '*'` at some point.
