### ISSUE TITLE
Errors when inserting on the first line of a file

### ISSUE THREAD

**Issue by eero-lehtinen** [Saghen/blink.cmp#240]
### Make sure you have done the following

- [X] I have updated to the latest version of `blink.cmp`
- [X] I have read the README

### Bug Description

Autocomplete window just crashes when trying to complete on the first line of a file. On other lines it is fine.

```
Error executing vim.schedule lua callback: ...im/lazy/blink.cmp/lua/blink/cmp/windows/autocomplete.lua:149: Invalid 'window': Expected Lua number 
stack traceback: 
        [C]: in function 'nvim_win_set_cursor' 
        ...im/lazy/blink.cmp/lua/blink/cmp/windows/autocomplete.lua:149: in function 'open_with_items' 
        .../.local/share/nvim/lazy/blink.cmp/lua/blink/cmp/init.lua:57: in function <.../.local/share/nvim/lazy/blink.cmp/lua/blink/cmp/init.lua:51> 
```

### neovim version

NVIM v0.11.0-dev-1035+g50e63c817

### `blink.cmp` version: branch, tag, or commit

main (055b9435358f68ae26de75d9294749bd69c22ccc)

**Comment by andrewferrier** [comment]
+1. Confirmed I see this issue also. Occurs only on the first line of files.

**Comment by andrewferrier** [comment]
I haven't had time to fully bisect it, but it looks like the problem was introduced between b0815e4 (where it works) and 055b943 (where it doesn't).
