### ISSUE TITLE
Add end tabstop to snippet if it doesn't exist

### ISSUE THREAD

**Issue by Rishabh672003** [Saghen/blink.cmp#246]
### Make sure you have done the following

- [X] I have updated to the latest version of `blink.cmp`
- [X] I have read the README

### Bug Description

as you can see expanding of `tyf` into `type name func()` and then tabbing through them, after the last tab after func() it should have left the snippet expansion, but instead it goes back to the first placeholder again
same with html expansion of `label`

https://github.com/user-attachments/assets/c0fac8e6-2ff4-4498-a8b6-ff3d633ceeeb

### Relevant configuration

```lua
keymap = "default",
-- experimental auto-brackets support
accept = { auto_brackets = { enabled = true } },
-- experimental signature help support
trigger = { signature_help = { enabled = false } },

windows = {
  documentation = {
    auto_show = true,
  },
},
```

### neovim version

NVIM v0.10.2

### `blink.cmp` version: branch, tag, or commit

v0.5.1

**Comment by Rishabh672003** [comment]
also i am getting this error sometimes with minimal config 
![image](https://github.com/user-attachments/assets/785a6c26-a507-4cb4-9838-e72ee71b7aae)

**Comment by Saghen** [comment]
The `snippet_forward` command does:

```lua
if not vim.snippet.active({ direction = 1 }) then return end
vim.schedule(function() vim.snippet.jump(1) end)
```

It seems likely that this an issue with either friendly-snippets or the built in snippets

**Comment by Rishabh672003** [comment]
@Saghen i investigated some more and found the root of the issue, its the absence of $0 i.e. an end point, and yes that happens just with `vim.snippet.expand`


https://github.com/user-attachments/assets/d4a09acc-8bb9-4125-b467-431539efd28c

**Comment by Rishabh672003** [comment]
i guess a resolved item can be checked if they have a `$0`, and if not one can be inserted to the end of the snippet i think that would be the easiest solution, other than changing the whole friendly-snippets to nvim-snippets

**Comment by Rishabh672003** [comment]
@Saghen sorry for bothering you so much, but should i report this somewhere else, or you looking into it?

**Comment by Saghen** [comment]
Yeah seems reasonable. Do you happen to know if `$0` can have any weird formatting that would cause that `string.find` to fail. I.e. other tabstops can do `${1:placeholder}` and other regex matching

**Comment by Rishabh672003** [comment]
yeah that snippet would need to be extended for placeholders and choices but not much i think
I read the [specs](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#snippet_syntax) there are only two possibilities either "$0" or ${0:random}/${0|random1,random2|} where both are same for a simple regex in the later case, i am assuming we arent checking if the snippet is valid or not, so this should just work

```lua
if not string.find(item.textEdit.newText, '%$0') and not string.find(item.textEdit.newText, '%${0') then
  item.textEdit.newText = item.textEdit.newText .. '$0'
end
```

**Comment by Rishabh672003** [comment]
Some of my discoveries while testing things

nesting of placeholders dont even work in neovim, still that regex will work in this case also
![image](https://github.com/user-attachments/assets/1bc3fb2b-1204-4e27-b72a-e1d5b8c94b63)

I dont think $0 can be even used for placeholders

https://github.com/user-attachments/assets/0912b849-ee7e-44bb-ab22-b2878cefbdc5

**Comment by Rishabh672003** [comment]
I found an issue with this, tabstop only works when $0 is at a some spaces away from the previous placeholder, but this leaves trailing white-spaces in the file

https://github.com/user-attachments/assets/4b5bc785-d16a-45cd-a990-7907368a79e3

also pressing tab continuously inserts random characters, when no tabstop or one with no spaces


https://github.com/user-attachments/assets/9bf01054-89ca-45f0-988e-73c9891af5c5

**Comment by Saghen** [comment]
> I found an issue with this, tabstop only works when $0 is at a some spaces away from the previous placeholder, but this leaves trailing white-spaces in the file

Ah yeah, I'll wait for a fix on the neovim side for that

> also pressing tab continuously inserts random characters, when no tabstop or one with no spaces, this is because of blink because doesnt happens with `nvim --clean`

I'm unable reproduce this, have you run into this on a fresh config with just blink?

**Comment by Rishabh672003** [comment]
it must some other plugin causing this, sorry for the noise

**Comment by Rishabh672003** [comment]
@Saghen I was tinkering with this in the core snippet engine, i somehow managed to fix this

https://github.com/user-attachments/assets/4d24aaa8-0506-4553-85f2-1ea27dc288d4

somehow my solution is so good now snippets don't even require $0 to end 😂 

https://github.com/user-attachments/assets/6fbd7585-a053-46bc-aa69-45f3ec148e93

I have no idea if my changes are any good but i can try making a pr to neovim

**Comment by Rishabh672003** [comment]
I talked about this with the author of mini.nvim and this is what he said, letting you know bcz i found it interesting

> I am frequently finding myself being annoyed when I reach $0 but notice that there was a typo earlier and I can not easily go back.
> My current approach is to allow wrapping by default and stop whole session if user started typing at 0 index. Plus stop session if exiting into Normal mode if all nodes are visited.

**Comment by Rishabh672003** [comment]
@Saghen you can close this issue if you want, its a issue with neovim itself so, we just have to wait for them to fix it
