### ISSUE TITLE
show documentation when expanding snippets is broken

### ISSUE THREAD

**Issue by Rishabh672003** [Saghen/blink.cmp#247]
### Make sure you have done the following

- [X] I have updated to the latest version of `blink.cmp`
- [X] I have read the README

### Bug Description

As you can see when i try to trigger, i know there is no docs to show for those completion but it shouldnt error out, this happens automatically when `auto_show = true` for documentation

this doesnt happen with 0.5.0 so might be a regression

https://github.com/user-attachments/assets/d75cd481-30d9-481e-a247-6a5b0ff070b1

### Relevant configuration

```lua
keymap = "default",
-- experimental auto-brackets support
accept = { auto_brackets = { enabled = true } },
-- experimental signature help support
trigger = { signature_help = { enabled = false } },

windows = {
  documentation = {
    auto_show = false,
  },
},
```

### neovim version

NVIM v0.10.2

### `blink.cmp` version: branch, tag, or commit

v0.5.1

**Comment by bwafi** [comment]
I also found the same issue, but only occurs with the Go-Lang
