### ISSUE TITLE
Purpose of show_on_insert_on_trigger_character

### ISSUE THREAD

**Issue by sQVe** [Saghen/blink.cmp#25]
Hey, 👋🏼

_First and foremost, great job with this plugin and its performance; it's a breath of fresh air!_

I would appreciate some further insights on what the `show_on_insert_on_trigger_character` option is meant to do.

The behavior of the completion menu is different when trying to expand a `{}` via **append** or **insert**. The attached screen recording shows the issue nicely, where I expand the block with **insert** first, without getting a completion, and then with **append**.

This behavior feels off, and it is only there if I enable `show_on_insert_on_trigger_character`. If I disable it, the behavior of append/insert is consistent.

https://github.com/user-attachments/assets/f3dcd2e8-cd16-4c07-9073-5825595dc705

**Comment by Saghen** [comment]
`luals` seems special in that it uses the trigger character to determine whether to show items. There was a tricky edge case where append was causing a double request to the LSP, one with and one without the trigger character. I've opened a separate issue (#79) which will avoid showing the menu in this case
