### ISSUE TITLE
Default behavior of `select_next`/ `select_prev` 

### ISSUE THREAD

**Issue by neochrome** [Saghen/blink.cmp#256]
First off - thanks for you hard work going into this plugin!

I've noticed that when configured to display the autocompletion window automatically (`windows.autocomplete.auto_show = false`) the completion menu shows automatically when I trigger a `select_prev` / `select_next` - which I have bound to `<down>` and `<up>` respectively. This is not desirable (for me) and I think a better behavior would be to just do the same as when `windows.autocomplete.auto_show = true`: https://github.com/Saghen/blink.cmp/blob/main/lua/blink/cmp/init.lua#L176.
I guess one reason for this is that the keybinds are "always active" in that they trigger even if the autocomplete window is not shown? What do you think would be the best approach?

**Comment by Saghen** [comment]
Yeah this behavior is confusing, I'm tracking a fix over on #204
