### ISSUE TITLE
ghost text: invalid 'col' out of range

### ISSUE THREAD

**Issue by mirsella** [Saghen/blink.cmp#257]
### Make sure you have done the following

- [X] I have updated to the latest version of `blink.cmp`
- [X] I have read the README

### Bug Description

this only happens on large rust project, where rust analyzer is slow to give response. there is a lot of "rust-analyzer: -32802: server cancelled the request". there is completion after like 500ms when rust analyzer give the response.
the problem might not be much the late response, but maybe also rust analyzer returning big function / types which are sometimes bigger than the screen 
```
  Error  10:32:04 notify.error rust-analyzer: -32802: server cancelled the request
   Error  10:32:05 msg_show.lua_error Error executing vim.schedule lua callback: ...nvim/lazy/blink.cmp/lua/blink/cmp/windows/ghost-text.lua:61: Invalid 'col': out of range
stack traceback:
	[C]: in function 'nvim_buf_set_extmark'
	...nvim/lazy/blink.cmp/lua/blink/cmp/windows/ghost-text.lua:61: in function 'show_preview'
	...nvim/lazy/blink.cmp/lua/blink/cmp/windows/ghost-text.lua:15: in function 'callback'
	...im/lazy/blink.cmp/lua/blink/cmp/windows/autocomplete.lua:313: in function 'emit_on_select'
	...im/lazy/blink.cmp/lua/blink/cmp/windows/autocomplete.lua:157: in function 'open_with_items'
	.../.local/share/nvim/lazy/blink.cmp/lua/blink/cmp/init.lua:57: in function <.../.local/share/nvim/lazy/blink.cmp/lua/blink/cmp/init.lua:51>
```

### Relevant configuration

```lua
windows = {
        ghost_text = {
          enabled = true,
        },
      },
```

### neovim version

NVIM v0.10.2 Build type: RelWithDebInfo LuaJIT 2.1.1727870382

### `blink.cmp` version: branch, tag, or commit

d3e1c92

**Comment by stefanboca** [comment]
I'm also getting this on `textEdit`s where `range.end.character` is at the end of a line (equivalent to the length of the line + 1, which I believe is perfectly reasonable according to the LSP spec because the end character is excluded from the range).

**Comment by mirsella** [comment]
@lopi-py the problem seems to be resolved for me.
use the main version instead of release, and maybe `cargo build --release`

**Comment by stefanboca** [comment]
@Saghen I'm working on compat (trying to get supermaven working) and I'm getting this issue again.

![image](https://github.com/user-attachments/assets/5a5abad6-1b7c-42ea-8923-6ab0bfd81117)

**Comment by stefanboca** [comment]
Although this might be because supermaven also inserts its own virtual text. In a bit I'll try disabling supermaven's ghost text, and I'll let you know if this still occurs.

**Comment by stefanboca** [comment]
Here's a minimal repro. In the file:
```python
pr|
```
(where `|` is the cursor)

the completion item that triggers the error is
```lua
 {
  cmp = {
    kind_hl_group = "CmpItemKindSupermaven",
    kind_text = "Supermaven"
  },
  cursor_column = 2,
  documentation = {
    kind = "markdown",
    value = '```python\nprint("hello")\n```'
  },
  dup = 0,
  insertTextFormat = 1,
  kind = 1,
  label = 'print("hello")',
  score = 100,
  score_offset = 0,
  source_id = "supermaven",
  source_name = "supermaven",
  textEdit = {
    insert = <1>{
      ["end"] = {
        character = 3,
        line = 0
      },
      start = {
        character = 0,
        line = 0
      }
    },
    newText = 'print("hello")',
    replace = <table 1>
  }
}
```
