### ISSUE TITLE
Snippet gets "stuck" in certain situations

### ISSUE THREAD

**Issue by rawhat** [Saghen/blink.cmp#264]
### Make sure you have done the following

- [X] I have updated to the latest version of `blink.cmp`
- [X] I have read the README

### Bug Description

I've noticed this happening mostly in this particular situation, so I don't know how "general" it is.  If I select an LSP completion for a React component prop, I get the associated "bracket" inserted as well (either quotes or brackets, depending).  If I swap over from the quotes to a bracket, the plugin enters snippet mode.  I'm not sure if that's even expected, but I'm fine with it.  If I then type something and press `<Tab>`, it doesn't complete the snippet.  It seems to get "stuck" until something happens?  I can't quite tell what triggers exiting the snippet.

Here is an example:

https://github.com/user-attachments/assets/068944c6-56c0-4a80-922c-77a8da58e6b6

Not sure what's going on, but any help would be appreciated 😄 

### Relevant configuration

```lua
opts = {
		highlight = {
			use_nvim_cmp_as_default = true,
		},
		keymap = {
			preset = "super-tab",
		},
		sources = {
			completion = {
				enabled_providers = { "lsp", "path", "snippets", "buffer", "lazydev" },
			},
			providers = {
				lsp = { fallback_for = { "lazydev" } },
				lazydev = { name = "LazyDev", module = "lazydev.integrations.blink" },
			},
		},
		trigger = {
			completion = {
				show_in_snippet = false,
			},
		},
		windows = {
			autocomplete = {
				draw = "minimal",
			},
			documentation = {
				auto_show = true,
			},
		},
	},
```

### neovim version

NVIM v0.11.0-dev-1092+g0da4d89558

### `blink.cmp` version: branch, tag, or commit

main

**Comment by Saghen** [comment]
This seems like an issue with the built-in snippets rather than with blink.cmp. Are you able to reproduce this by using the built-in `vim.snippet.expand` and `vim.snippet.jump`?

**Comment by rawhat** [comment]
Oh interesting, I didn't think about that... the only alternative nvim app I have is based on https://gist.github.com/MariaSolOs/2e44a86f569323c478e5a078d0cf98cc and I'm not totally sure how to replicate what's happening here with that 🤔 

I tried just making a keymap for `vim.snippet.expand` and used tab within it with the setup I'm using from that gist, and it seemed to have no issue.  Just for clarity, like: 

- type the prop that's a string type
- `<C-n>` to accept the LSP completion
- put in open bracket
- call `vim.snippet.expand` with a keybind in insert mode
- press tab to to jump through snippet

That seemed to work fine 😕 I did also try adding `nvim-autopairs` to the mix, since I'm using that as well.  It didn't seem to change anything other than placing the brackets and my cursor after them 😬

**Comment by Saghen** [comment]
Yeah, it looks like this is an issue with the built-in snippets. I was able to reproduce by creating two keybinds:

```
vim.snippet.expand('test = "$1"')
```
```
if vim.snippet.active({ direction = 1 }) then
  vim.snippet.jump(1)
end
```

and the behavior was the same. Lmk if you find a way around this though, I also find this behavior pretty confusing :smile:
