### ISSUE TITLE
GIT_DIR GIT_WORK_TREE environment variable affect blink.cmp

### ISSUE THREAD

**Issue by Bahex** [Saghen/blink.cmp#274]
### Make sure you have done the following

- [X] I have updated to the latest version of `blink.cmp`
- [X] I have read the README

### Bug Description

I use the bare git repo method for managing my dotfiles, which means I have these environment variables set
```env
GIT_DIR=$HOME/.dotfiles.git
GIT_WORK_TREE=$HOME
```

Apparently this affects blink.cmp's download mechanism.

It might be necessary to set these environment variables or use git's `--git-dir` and `--work-tree` arguments in any git command the plugin executes to to prevent collisions with user environment.

### neovim version

NVIM v0.10.2

### `blink.cmp` version: branch, tag, or commit

v0.5.1

**Comment by Saghen** [comment]
Closed by #275
