### ISSUE TITLE
Slow LSP prevents popuplating using other sources

### ISSUE THREAD

**Issue by Ajaymamtora** [Saghen/blink.cmp#278]
If I have a massive typescript project open, and I have these sources:

```lua
    sources = {
      -- list of enabled providers
      completion = {
        enabled_providers = { 'lsp', 'path', 'snippets', --[[ 'ripgrep', ]] 'buffer' },
      },

```

Then nothing comes up until the LSP has finished initialising which takes a long time. nvim-cmp doesnt have this issue, it will immediately suggest stuff from the buffer source for example.

Please can this be resolved?

**Comment by zjykzk** [comment]
one source is finished, it's conent is showed in the completion window automatically is prefered

**Comment by JakeTompkins** [comment]
I'd like to see this as well.

**Comment by Saghen** [comment]
Combining into #312
