### ISSUE TITLE
Expose snippet reload function, enables integration with plugins like nvim-scissors

### ISSUE THREAD

**Issue by chrisgrieser** [Saghen/blink.cmp#28]
I am the maintainer of [nvim-scissors](http://github.com/chrisgrieser/nvim-scissors), and would like to implement a hot-reload-support for blink.cmp. To be able to do that, blink.cmp needs to expose some sort of function that reloads a snippet file inside `providers → 'blink.cmp.sources.path' → opts.searchpaths.`.

snippet engines usually expose such functionality, so other plugins can properly integrate with them, e.g. `require("luasnip.loaders").reload_file(path)` for luasnip: https://github.com/L3MON4D3/LuaSnip/blob/master/DOC.md#loaders

It would be great for blink.cmp to also expose such a function.

**Comment by jose-elias-alvarez** [comment]
It looks like the way snippets are loaded makes it pretty tricky to do this cleanly, but it's currently possible to bust the cache in a highly undocumented way:

```lua
local reset_snippets_cache = function()
    local snippets_provider = vim.iter(require("blink.cmp").sources.providers):find(function(provider)
        return provider.name == "Snippets"
    end)
    if not snippets_provider then
        return
    end
    -- could theoretically scope this to a filetype, but not much point
    snippets_provider.module.cache = {}
end
```

I could imagine exposing a `reset()` method, but I'm not sure if it would see much use beyond this specific case. Happy to put in a PR if there's agreement on an approach.

**Comment by Saghen** [comment]
`require('blink.cmp').sources.reload()` should do the trick

**Comment by chrisgrieser** [comment]
Thank you!

**Comment by chrisgrieser** [comment]
Unfortunately, it appears the reload function is not working. `require('blink.cmp').sources.reload()` does not reload the snippets if there are changes. There is also no error of any kind, it just silently does nothing.

**Comment by Saghen** [comment]
Sorry about that, it got broken during the sources rework. Fixed in https://github.com/Saghen/blink.cmp/commit/407f2d526fd07b651a8a7330df2c4fd05b32a014

**Comment by chrisgrieser** [comment]
thank you
