### ISSUE TITLE
Bug: Alignment of documentation & completion window is off

### ISSUE THREAD

**Issue by chrisgrieser** [Saghen/blink.cmp#29]
![Pasted image 2024-10-08 at 14 03 29](https://github.com/user-attachments/assets/d8b64974-64f7-4d1b-8390-be7c01366de4)

![Pasted image 2024-10-08 at 14 06 27](https://github.com/user-attachments/assets/c1483b69-99f9-4ea7-9a5e-c2d3bdc261de)

top image is blink.cmp, bottom one is nvim-cmp. With blink.cmp, when using `border = "single"` for the windows, the alignment is off-by one vertically and horizontally.

**Comment by 0xJWLabs** [comment]
is it all border or just single?

**Comment by sieuwerts** [comment]
> is it all border or just single?

I had the same issue for other borders as well.
