### ISSUE TITLE
Syntax for file wrong after snippet suggestion

### ISSUE THREAD

**Issue by danjessen** [Saghen/blink.cmp#295]
### Make sure you have done the following

- [X] I have updated to the latest version of `blink.cmp`
- [X] I have read the README

### Bug Description

Using LazyVim I've enabled the new blink extra. I'm experiencing issues when interacting with Friendly snippets. Normal suggestions / copilot suggestions work fine. But when selecting a friendly snippet the syntax for the file gets changed. Setting it manually afterwards, restores / fixes the bug.

https://github.com/user-attachments/assets/4b988652-1a35-4e5d-a0e3-3d28031c14f8

I'm running smarty a template language written in PHP. I'm not using treesitter highlighting. Just vim / regex based. Since this works the best for this language in my experience.

My snippets are in vscode format.

### neovim version

NVIM v0.11.0-dev-4072+g2377443cd-Homebrew

### `blink.cmp` version: branch, tag, or commit

75cadbcd2657ed01326ca2b0e5e4d78a77127ca3

**Comment by Saghen** [comment]
What in the world :joy: This seems to have been fixed at some point between `v0.5.1` and `main`. I'll be cutting a new release soon

**Comment by Saghen** [comment]
Scratch that, I was just able to reproduce on `main`. There's some ghosts in my code...
