### ISSUE TITLE
potentially use mlua and luarocks to build rust code

### ISSUE THREAD

**Issue by benlubas** [Saghen/blink.cmp#3]
Hey this project was brought to my attention recently and it seems really cool. I'm wondering if you're aware of [mlua](https://github.com/mlua-rs/mlua) and the [luarocks build backend](https://github.com/mlua-rs/luarocks-build-rust-mlua) for it. 

I'd imagine this could allow you to very easily distribute this plugin on luarocks, and users would then be able to pull from luarocks and build the plugin themselves. For an example of a neovim plugin that uses mlua, there's [benlubas/neorg-se](https://github.com/benlubas/neorg-se).

I'd be happy to submit a PR if this seems interesting.

**Comment by Saghen** [comment]
I'm very interested! Especially considering the library I'm using isn't maintained anymore and distributing pre-built binaries was a bit of a pain. I noticed on your neorg-se project that lazy.nvim requires extra external dependencies for this to work. Is that an unavoidable issue?

**Comment by benlubas** [comment]
ahh, that's actually left over from the past. I should remove that from the readme. The build will work fine with lazy, as long as you setup the github workflow correctly.

**Comment by benlubas** [comment]
And I'll work on a PR later today

**Comment by Saghen** [comment]
Sounds great, main thing I'd like to see is how it handles the pre-built binaries since asking people to have a nightly toolchain installed isn't ideal

**Comment by benlubas** [comment]
oh true I forgot about nightly :/

I'm not sure that it can do prebuilt binaries. But it might be able to. I'll remember to test with that

**Comment by calops** [comment]
It's a crutch, but wouldn't it be possible, through github actions, to maintain a nightly release with prebuilt binaries for the latest commit on `main`?

**Comment by Saghen** [comment]
Where would the artifacts be stored? Afaik github actions artifacts have a 30 day expiry

**Comment by mrcjkb** [comment]
> Where would the artifacts be stored? Afaik github actions artifacts have a 30 day expiry

You could use GitHub pages.
We do that with our [rocks-binaries](https://github.com/nvim-neorocks/rocks-binaries) project (which both rocks.nvim and lazy.nvim can pull from).

**Comment by calops** [comment]
I'm not talking about hosting github action artifacts, but releasing these assets in an actual github release (like you're doing already, but only for whole versions).

But yeah, github pages could work as well.

**Comment by mrcjkb** [comment]
If you end up using `mlua` instead of FFI (which would remove the luajit dependency), it might make sense to extract that into its own library with its own release cycle.

**Comment by calops** [comment]
> If you end up using `mlua` instead of FFI (which would remove the luajit dependency), it might make sense to extract that into its own library with its own release cycle.

That does sound like the best strategy here.
