### ISSUE TITLE
builtin buffer provider could be shadowed by lsp, thus ignoring words from comments in suggestions

### ISSUE THREAD

**Issue by xiaket** [Saghen/blink.cmp#303]
### Make sure you have done the following

- [X] I have updated to the latest version of `blink.cmp`
- [X] I have read the README

### Bug Description

First off, I really appreciate the effort into this plugin. The performance is sooo impressive! Kudos!

I would like to report that the buffer provider has not included the words from the comments, is that intentional?

Way to reproduce this issue:

1.  Run `echo "# uuid is a library used by this module" >> a.py && nvim a.py`.
2. enter `uu`, my expected behavior(also the behavior in cmp IIRC) is `uuid` will show up, but it is not.

### Relevant configuration

```lua
{
    "saghen/blink.cmp",
    -- lazy loading handled internally
    lazy = false,
    -- use a release tag to download pre-built binaries
    version = "v0.*",

    opts = {
      -- 'enter' for mappings similar to 'super-tab' but with 'enter' to accept
      keymap = { preset = "enter" },

      -- experimental auto-brackets support
      accept = { auto_brackets = { enabled = true } },

      -- experimental signature help support
      trigger = { signature_help = { enabled = true } },
    },
  },
```

### neovim version

v0.10.2

### `blink.cmp` version: branch, tag, or commit

master

**Comment by xiaket** [comment]
After some digging, it looks like removing the line [here](https://github.com/Saghen/blink.cmp/blob/6516736e15eb0ca0120df2dc11528cb2d257092e/lua/blink/cmp/config.lua#L365) would force the use of buffer even when lsp is available and resolve the issue.

**Comment by xiaket** [comment]
I've changed my config to be:

```
      sources = {
        -- list of enabled providers
        completion = {
          enabled_providers = { "lsp", "path", "snippets", "buffer" },
        },

        -- table of providers to configure
        providers = {
          buffer = {
            name = "Buffer",
            module = "blink.cmp.sources.buffer",
            score_offset = -3,
          },
        },
      },
```

And the completion looks good to me now. Thanks! Please feel free to close this issue. :)

**Comment by Saghen** [comment]
Sounds good! I've created #311 which might make this a bit more intuitive. 

Fyi, you can enable-disable the `fallback_for` behavior by passing a function in its place. You could check the current LSP and only disable the `fallback_for` for the misbehaving LSPs.

```
fallback_for = function()
  local clients = vim.lsp.get_clients({ bufnr = 0 })
  for _, client in pairs(clients) do
    if client.name == 'lua_ls' then return {} end
  end
  return { 'lsp' }
end
```
