### ISSUE TITLE
attempting to call _str_byteindex_enc a nil value

### ISSUE THREAD

**Issue by Euro20179** [Saghen/blink.cmp#307]
### Make sure you have done the following

- [X] I have updated to the latest version of `blink.cmp`
- [X] I have read the README

### Bug Description

It appears that `vim.lsp.util._str_byteindex_enc` has been removed in the latest commits of neovim, (im not sure which, and i'm too lazy to check), downgrading to neovim 10 has solved the issue.

### neovim version

v0.11.0-dev-1123+g0eae0bc804

### `blink.cmp` version: branch, tag, or commit

HEAD

**Comment by yCroma** [comment]
In my environment, I've had the following problems.
I will share them once.
I found a similar issue on Telescope. 
- [fix: vim.str_byteindex argument order #3345](https://github.com/nvim-telescope/telescope.nvim/pull/3345/commits/4d04fc97e70a03f93ca8ca4c454d64e9a5c16f84)

I'll try to see if I can fix it by following the rules of this repository if there are any.

Let me know if you have any reference links or commits.
Or I'll try to be good about it.

### neovim version
```
❯ nvim -v
NVIM v0.11.0-dev-671+g3a61f05dd
Build type: RelWithDebInfo
LuaJIT 2.1.1724512491
Run "nvim -V1 -v" for more info
```

### happend
```
nvim/lazy/blink.cmp/lua/blink/cmp/lib/text_edits.lua:73: bad argument #2 to 'str_byteindex' (number expected, got string)
```

### Lsp Warning
```
This function expects a maximux of 3 argument(s) but instead it is receiving 4
```

**Comment by yCroma** [comment]
Thanks for letting me know.
I updated neovim and it fixed it!
