### ISSUE TITLE
Move cursor to the first parameter in expanded snippet?

### ISSUE THREAD

**Issue by linrongbin16** [Saghen/blink.cmp#309]
### Feature Description

Hi, I found the "expand snippet" behavior moves cursor to the "body" (I am not sure how to describe this place) instead of "parameters".

For example, in following screen recording, I expand the "while-do-end" lua snippet, and when I accept the snippet, the cursor will go to the "body" of the while:

https://github.com/user-attachments/assets/cdb83b33-84a3-474f-b576-94da62147466

Can I place the cursor at the first parameter, i.e. the `true`?

OS: Windows 10 64-bit
Neovim version: 0.10.2
Blink.cmp version: 0.5.1

**Comment by Saghen** [comment]
@bnwa You're running into a different issue. Can you test this on `main`, and if the issue is still occurring, include reproduction steps in a separate issue? 

@linrongbin16 For some reason I can't reproduce this. Are you running into this on a fresh/minimal config (i.e. `nvim -U NONE`)

**Comment by linrongbin16** [comment]
hi @Saghen , you are right, it should be some conflicting issue with my own configs.

I have below configs:

```lua
-- ctrl/cmd-?
if vim.fn.exists("$VIMRUNTIME/mswin.vim") > 0 then
  vim.cmd([[source $VIMRUNTIME/mswin.vim]])
end
if vim.fn.has("mac") > 0 and vim.fn.exists("$VIMRUNTIME/macmap.vim") > 0 then
  vim.cmd([[source $VIMRUNTIME/macmap.vim]])
end
```

It was going to enable the Windows keys (CTRL-C to copy, CTRL-V to paste, CTRL-S to save, etc), after remove these lines, everything is good now.
