### ISSUE TITLE
Bug: `time` snippet is not autofilled

### ISSUE THREAD

**Issue by NicoElbers** [Saghen/blink.cmp#32]
The `time` snippet (and similar such snippets) are auto filled to the current time. However using blink.cmp, this does not happen:

Using blink: 
![image](https://github.com/user-attachments/assets/92711bc3-b6fe-4fdc-8859-e6a0d1de21a0)
![image](https://github.com/user-attachments/assets/eae9fdb7-bef6-4a44-97f1-01a990af4a73)

Using cmp:
![image](https://github.com/user-attachments/assets/808f136b-353d-4805-b7da-42dd439315a7)
![image](https://github.com/user-attachments/assets/481ae9b0-9573-4e61-afae-d0b572d471ed)

**Comment by chrisgrieser** [comment]
duplicate of #27

**Comment by NicoElbers** [comment]
Ah mb
