### ISSUE TITLE
bug: inconsistent autocompletion UI

### ISSUE THREAD

**Issue by idelice** [Saghen/blink.cmp#322]
### Make sure you have done the following

- [X] I have updated to the latest version of `blink.cmp`
- [X] I have read the README

### Bug Description

Here are some examples on how inconsistent the UI becomes:

### First part: typing `String` and then `Stringu` 
<img width="983" alt="Screenshot 2024-11-12 at 14 55 27" src="https://github.com/user-attachments/assets/c5dbd705-d27f-44c3-a05f-63bda45c1fff">

<img width="984" alt="Screenshot 2024-11-12 at 14 55 33" src="https://github.com/user-attachments/assets/114c458d-f93f-43eb-b058-414e5c256ac2">

### Second part: typing `a` and then `abb`
<img width="1417" alt="Screenshot 2024-11-12 at 14 55 55" src="https://github.com/user-attachments/assets/b4b114e4-ac8b-4f80-8870-6e66aac790cf">

<img width="1467" alt="Screenshot 2024-11-12 at 14 55 50" src="https://github.com/user-attachments/assets/fd1a52a4-679b-4fff-bbff-73261c7b51c3">

The distance between label and description(?) changes based on what it shows. 

What's going on?

### neovim version

0.10.1

### `blink.cmp` version: branch, tag, or commit

9822c6b40ad9

**Comment by idelice** [comment]
> Are you on the default config? And what is neovim 0.11.1?

It should obviously be 0.10.1. I've updated the description

And no, this is my config:
```lua
return {
  "saghen/blink.cmp",
  dev = true,
  dir = "~/projects/blink.cmp",
  -- build = "cargo build --release",
  lazy = false, -- lazy loading handled internally
  dependencies = "rafamadriz/friendly-snippets",
  -- version = "v0.*",
  opts = {
    accept = {
      auto_brackets = {
        enabled = true,
      },
    },
    windows = {
      autocomplete = {
        border = "rounded",
        min_width = 80,
        draw = {
          components = {
            label = {
              width = { fill = true, max = 60 },
              text = function(ctx)
                return ctx.label
              end,
            },
            label_description = {
              width = { fill = true, max = 90 },
              text = function(ctx, package)
                local source = ctx.item.source_id
                local client = source == "lsp" and vim.lsp.get_client_by_id(ctx.item.client_id).name

                local formattedPackage
                if source == "lsp" and client == "jdtls" then
                  if ctx.kind == "Constructor" then
                    if ctx.item.detail ~= nil and ctx.item.detail ~= "" then
                      formattedPackage = ctx.item.detail:match("^[^%(]*")
                    end
                  end
                end

                if package then
                  return package
                elseif formattedPackage then
                  return formattedPackage
                elseif ctx.label_description ~= nil and ctx.label_description ~= "" then
                  return ctx.label_description
                else
                  return ""
                end
              end,
            },
          },
        },
      },
      documentation = {
        auto_show = true,
        auto_show_delay_ms = 50,
        border = "rounded",
      },
      signature_help = {
        border = "rounded",
      },
    },
    keymap = {
      ["<Tab>"] = { "accept" },
      ["<C-k>"] = { "select_prev" },
      ["<C-j>"] = { "select_next" },
    },
  },
}
```

**Comment by Saghen** [comment]
It's because you added `fill = true` to the `label_description`. This is your 7th issue that's effectively not an issue so please read the documentation and try to fix these issues on your own. I'm not tech support :smile:

**Comment by idelice** [comment]
> It's because you added `fill = true` to the `label_description`. This is your 7th issue that's effectively not an issue so please read the documentation and try to fix these issues on your own. And when you do post issues, please follow the template. I'm not tech support 😄

https://github.com/Saghen/blink.cmp/issues/156 is the one issue that's not an actual issue, I agree, so I don't know where you get the number 7 from.

And you really think I haven't tried removing `fill = true` to see what happens before creating this issue? Cmon man 😆
