### ISSUE TITLE
Issue with Snippet has multiple placeholders for tabstop $1

### ISSUE THREAD

**Issue by Nirajgns** [Saghen/blink.cmp#335]
### Make sure you have done the following

- [X] I have updated to the latest version of `blink.cmp`
- [X] I have read the README

### Bug Description

Most snippets work fine, but  snippets that have multiple tabstops  with same name shows this error :

...r/neovim/0.10.2_1/share/nvim/runtime/lua/vim/snippet.lua:430: Snippet has multiple placeholders for tabstop $1.

snippet example: rafce,rafc
 

### Relevant configuration

```lua
return {
  "saghen/blink.cmp",
  event = "InsertEnter",
  version = "v0.*",
  opts_extend = {
    "sources.completion.enabled_providers",
    "sources.compat",
  },
  dependencies = {
    "rafamadriz/friendly-snippets",
  },

  opts = {
    highlight = {
      use_nvim_cmp_as_default = true,
    },
    nerd_font_variant = "normal",
    windows = {
      autocomplete = {
        border = "rounded",
        winblend = 40,
      },
      documentation = {
        auto_show = true,
        border = "rounded",
        winblend = 40,
        min_width = 1,
        min_height = 1,
      },
      signature_help = {
        auto_show = true,
        border = "rounded",
        winblend = 40,
      },
      ghost_text = {
        enabled = false,
      },
    },

    -- experimental auto-brackets support
    accept = { auto_brackets = { enabled = true } },

    trigger = { signature_help = { enabled = true } },
    sources = {
   
      compat = {},
      completion = {
        -- remember to enable your providers here
        enabled_providers = { "lsp", "path", "snippets", "buffer" },
      },
    },

    keymap = {
      preset = "enter",
    
    },
  },

}
```

### neovim version

0.10.2

### `blink.cmp` version: branch, tag, or commit

0.5.1

**Comment by Saghen** [comment]
Hey there, this is an issue with the built-in snippets although I believe it's behaving as intended. The tabstops should be increasing like $1, $2, $3, ...

**Comment by Nirajgns** [comment]
but the snippet works fine with nvim-cmp and luasnip. should i try using blink.cmp with luasnip?

**Comment by enkyuan** [comment]
seconding this issue. came across it not too long ago after updating blink.cmp.

**Comment by ajatkj** [comment]
I have added below to my `blink` config and tabstops are working as they used to work with `nvim-cmp`

```lua
require("luasnip.loaders.from_vscode").lazy_load()
```
