### ISSUE TITLE
Support for epwalsh/obsidian.nvim

### ISSUE THREAD

**Issue by TZProgrammer** [Saghen/blink.cmp#338]
### Feature Description

I do not believe epwalsh/obsidian.nvim currently works with blink.cmp. I am not sure if this feature request should be made in this project or in obsidian.nvim, but please let me know if support for this plugin is planned.

**Comment by Saghen** [comment]
Ayy a fellow Canadian! This should be made in the obsidian.nvim repo although you may be able to get it working with https://github.com/saghen/blink.compat
