### ISSUE TITLE
A method to update to the latest pre-built release

### ISSUE THREAD

**Issue by stevenxxiu** [Saghen/blink.cmp#339]
### Feature Description

I use *lazy.nvim*. I'm used to installing the latest commit for every plugin.

*blink.cmp* requires me to build the plugin each time with *Rust*. This is inconvenient for machines with limited resources, including say *Termux* when that gets supported.

Could there be an option to always install the latest pre-built release, instead of manually updating the `version` key each time?

**Comment by Saghen** [comment]
Hey there, you can set the version to "0.*" which will update to any version < 1.0 https://lazy.folke.io/spec#spec-versioning
