### ISSUE TITLE
Support uppercase keymaps like <C-E>

### ISSUE THREAD

**Issue by ayoubelmhamdi** [Saghen/blink.cmp#342]
### Feature Description

In Vim, the `CTRL`+`keymap` doesn't distinguish between uppercase/lowercase when using `CTRL`. If this is the case, could you please support keys like `<C-Y>` in addition to `<C-y>`?

```lua
return {
  'saghen/blink.cmp',
  opts = {
    keymap = {
      preset = 'default',
      ['<C-Y>'] = { 'hide' },
    }
  }
}
```

**Comment by Saghen** [comment]
It's impossible to do this in terminal environments as far as I'm aware

**Comment by ayoubelmhamdi** [comment]
i mean, the `<C-Y>` is equivalent to `<C-y>` in Terminal environment, but this plugin confused when we use `<C-Y>`

**Comment by Saghen** [comment]
Ahh I misunderstood, I'm not able to reproduce this issue though
