### ISSUE TITLE
Luasnip not expanding

### ISSUE THREAD

**Issue by NicolasGB** [Saghen/blink.cmp#345]
### Make sure you have done the following

- [X] I have updated to the latest version of `blink.cmp`
- [X] I have read the README

### Bug Description

First of all thanks for the plugin and your work, this looks as such a nice approach to cmp!

I am used to some snippets with nvim-cmp and luasnip and just saw that using luasnip should be possible, I tried mapping the expansion as mentioned in the docs but it doesn't seem to work. 

Maybe it's a misconfiguration on my side, please let me know if this is the case, otherwise there might be a bug.

Here's a small video showing the non-expansion of the snippets:

https://github.com/user-attachments/assets/d2229faf-1b6d-465e-8e3d-0fb98c0734df

I select and press <CR> since i'm using the "enter" keymap but nothing happens, tab does nothing either.

### Relevant configuration

```lua
{
        accept = {
          expand_snippet = require("luasnip").lsp_expand,
          auto_brackets = {
            enabled = true,
          },
        },
        highlight = {
          use_nvim_cmp_as_default = true,
        },
        keymap = { preset = "enter" },
        windows = {
          autocomplete = {
            -- Better highlights and roudnded text
            border = "rounded",
            winhighlight = "Normal:NormalFloat,FloatBorder:FloatBorder,CursorLine:Visual,Search:None",

            -- Avoid directly inserting on enter
            selection = "auto_insert",

            -- Similar to nvim cmp visually
            draw = {
              columns = { { "label", "label_description", gap = 1 }, { "kind_icon", "kind", gap = 1 } },
            },
          },
          documentation = {
            border = "rounded",
            auto_show = true,
          },
        },
        sources = {
          completion = {
            enabled_providers = { "lsp", "path", "buffer", "luasnip" },
          },
          providers = {
            luasnip = {
              name = "luasnip",
              module = "blink.compat.source",

              score_offset = -3,

              opts = {
                use_show_condition = false,
                show_autosnippets = true,
              },
            },
          },
        },
      }
```

### neovim version

v0.11.0-dev-1189+g989a37a594

### `blink.cmp` version: branch, tag, or commit

main, commit: 91ea929

**Comment by alienman5k** [comment]
Same is happening for me, this does not seem to work as it is not even able to find the snippets defined by LuaSnip in the first place.

**Comment by NicolasGB** [comment]
Yeah, adding the source like in my config makes them appear though.

Since blink is so good and I used luasnips mainly for my custom snippets, I ported them to the friendly-snips format and it works like a charm.

**Comment by alienman5k** [comment]
Too bad in my case I have very complex snippets that are not just possible to port as they depend on getting info from OS and other tools where I have custom lua code to generate content or placeholders or choices.

**Comment by Saghen** [comment]
Thanks for the example on how to set it up @NicolasGB! I've [added support for `execute`](https://github.com/Saghen/blink.cmp/commit/653b2629e1dab0c6d0084d90f30a600d601812a1) which the `luasnip` source depends on and added an example on how to set it all up in the README. I don't use luasnip myself so lmk if anything should be changed there

**Comment by ahmedelgabri** [comment]
I came here for the same problem, @Saghen any idea when there will be a new release `v0.x`?
