### ISSUE TITLE
Add a way to disable completion for comments

### ISSUE THREAD

**Issue by Leonard-Pat** [Saghen/blink.cmp#353]
### Feature Description

I wish there was an flag to disable completion for comments. 
i tried:
```lua
completion = {
-- Disable completion in comments using treesitter
should_show = function()
	local context = vim.treesitter.get_node()
	if not context then
		return true
	end
	local type = context:type()
	return type ~= "comment" and type ~= "line_comment" and type ~= "block_comment"
end,
},
```
but unfortunately this doesn't seem to work.
Maybe a flag might help

**Comment by Saghen** [comment]
Hey there, the `enabled_providers` parameter accepts a function like `fun(ctx: blink.cmp.Context): string[]`. Returning an empty array when inside a comment should disable the menu

**Comment by windowsrefund** [comment]
Greets. Is the comment above still valid? I don't see any reference to `enabled_providers` in the [reference documentation](https://cmp.saghen.dev/configuration/reference.html) and this would be a really nice option to have available. FYI, it is possible via `nvim-cmp` as detailed [here](https://github.com/hrsh7th/nvim-cmp/wiki/Advanced-techniques#disabling-completion-in-certain-contexts-such-as-comments).

If the above is still valid, can anyone show a working example? Thanks in advance.

**Comment by Saghen** [comment]
Check out https://cmp.saghen.dev/recipes.html#dynamically-picking-providers-by-treesitter-node-filetype

**Comment by windowsrefund** [comment]
So good! Thanks. I missed that in the docs.
