### ISSUE TITLE
Completion fails to render on line with multi-byte characters

### ISSUE THREAD

**Issue by leaysgur** [Saghen/blink.cmp#357]
### Make sure you have done the following

- [X] I have updated to the latest version of `blink.cmp`
- [X] I have read the README

### Bug Description

It seems that accepting completion fails to render properly when there are multi-byte characters on the same line, before the cursor.

https://github.com/user-attachments/assets/969e2080-8128-4224-8840-540fe40cea6b

The error is caused by the following lines of code:  

- https://github.com/Saghen/blink.cmp/blob/main/lua/blink/cmp/accept/text-edits.lua#L6
  - https://github.com/neovim/neovim/blob/v0.10.2/runtime/lua/vim/lsp/util.lua#L483

This issue is reproducible with Neovim version `0.10.2`.

After updating to Neovim version `v0.11.0-dev-1205+g07db909eb5`, the error no longer occurs. 
However, it still exhibits incorrect behavior. 

https://github.com/user-attachments/assets/107e1012-9749-4268-a3f5-1dfd89b31b28

it duplicates some characters.

### Relevant configuration

```lua
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not (vim.uv or vim.loop).fs_stat(lazypath) then
    local lazyrepo = "https://github.com/folke/lazy.nvim.git"
    vim.fn.system({ "git", "clone", "--filter=blob:none", "--branch=stable", lazyrepo, lazypath })
end
vim.opt.rtp:prepend(lazypath)

vim.g.mapleader = " "
vim.g.maplocalleader = "\\"

require("lazy").setup({
    {
        "saghen/blink.cmp",
        version = "v0.*",
        opts = {
            keymap = {
                ["<CR>"] = { "accept", "fallback" },
                ["<Tab>"] = { "select_next", "fallback" },
                ["<Down>"] = { "select_next", "fallback" },
                ["<S-Tab>"] = { "select_prev", "fallback" },
                ["<Up>"] = { "select_prev", "fallback" },
            },
            trigger = { signature_help = { enabled = true } },
            windows = { autocomplete = { selection = "manual" } },
        },
    },
})
```

### neovim version

0.10.2, 0.11.x

### `blink.cmp` version: branch, tag, or commit

0.5.1

**Comment by s-cerevisiae** [comment]
Somehow I can't reproduce this problem on two of my devices. Is your content in UTF-8 or other encodings like SJIS?

**Comment by leaysgur** [comment]
This reproduction was created using only the above config as `init.lua` and blank buffer.
So the encoding should be the default, utf8?

**Comment by leaysgur** [comment]
When I tried to use `main` instead of `v0.5.1`, the problem did not seem to occur.

So I'm going to close this and wait for the next release. Thanks for your support! 😉
