### ISSUE TITLE
No brackets rust macros? 

### ISSUE THREAD

**Issue by pwnwriter** [Saghen/blink.cmp#359]
### Make sure you have done the following

- [X] I have updated to the latest version of `blink.cmp`
- [X] I have read the README

### Bug Description

I've enabled auto-brackets but yet there's no brackets around macros like `println` `print` or so. 

<img width="736" alt="Screenshot 2024-11-21 at 2 38 14 PM" src="https://github.com/user-attachments/assets/0e167a99-b6e9-4d91-ae16-f627bb118591">
 

### Relevant configuration

```lua
{
    "saghen/blink.cmp",
    event = { "LspAttach", "InsertCharPre" },
    version = "v0.*",
    opts = {
      highlight = {
        use_nvim_cmp_as_default = true,
      },
      nerd_font_variant = "mono",

      accept = { auto_brackets = { enabled = true } },
      trigger = { signature_help = { enabled = true } },

      keymap = {
        ["<CR>"] = { "select_and_accept", "fallback" },
        ["<C-n>"] = { "select_next", "fallback" },
        ["<C-p>"] = { "select_prev", "fallback" },
        ["<C-y>"] = { "scroll_documentation_down" },
        ["<C-e>"] = { "scroll_documentation_up" },
      },

      windows = {
        autocomplete = {
          border = "single",
        },
        documentation = {
          auto_show = true,
          border = "single",
          auto_show_delay_ms = 100,
        },
      },
    },
  }
```

### neovim version

NVIM v0.10.2 Build type: Release LuaJIT 2.1.1713773202 Run "nvim -V1 -v" for more info

### `blink.cmp` version: branch, tag, or commit

  "blink.cmp": { "branch": "main", "commit": "75cadbcd2657ed01326ca2b0e5e4d78a77127ca3" },

**Comment by Saghen** [comment]
The auto brackets were explicitly disabled for `rust` due to them being inaccurate too often. You can force enable them with `force_allow_filetypes = { 'rust' }`. Lmk if it's working well for you though and I'll remove it from the blocklist

**Comment by pwnwriter** [comment]
#### Works flawlessly, I think you can remove it. but yes I'd want the brackets to be also shown in the completion menu(items). it it's possible? 

----




<img width="326" alt="Screenshot 2024-11-21 at 4 25 25 PM" src="https://github.com/user-attachments/assets/7adf6188-0c70-47a1-9886-7edafa2cb478">

<br>

<img width="293" alt="Screenshot 2024-11-21 at 4 25 53 PM" src="https://github.com/user-attachments/assets/8baa5b8d-3dda-4518-82e8-f2bd78ed5686">

**Comment by AstrickHarren** [comment]
I think in my case there are extra parenthesis for derive macros
