### ISSUE TITLE
Cursor inserts at wrong position after accepting completion, then never works again.

### ISSUE THREAD

**Issue by oysandvik94** [Saghen/blink.cmp#360]
### Make sure you have done the following

- [X] I have updated to the latest version of `blink.cmp`
- [X] I have read the README

### Bug Description

Sometimes, relatively often, accepting completions just stop working.

It starts by my completion being filled, but the cursor is placed before the word instead of after.
After that, accepting completions just dont work anymore.
I accept completions with tab, so after the cursos thing happens, when I press tab with the completion window open, it just inserts the tab character instead.

I dont get any error messages, so I'm not sure where to start looking. Any tips on how to debug would be great.

### Relevant configuration

```lua
return {
	"saghen/blink.cmp",
	lazy = false, -- lazy loading handled internally
	-- optional: provides snippets for the snippet source
	dependencies = "rafamadriz/friendly-snippets",
	enabled = true,
	build = "cargo build --release",
	opts = {
		-- experimental auto-brackets support
		accept = { auto_brackets = { enabled = true } },

		-- experimental signature help support
		trigger = { signature_help = { enabled = true } },
		keymap = {
			["<Tab>"] = { "accept" },
			["<Down>"] = { "select_next", "show" },
			["<Up>"] = { "select_prev", "show" },
		},
		windows = {
			documentation = {
				min_width = 10,
				max_width = 60,
				max_height = 20,
				border = "padded",
				winhighlight = "Normal:BlinkCmpDoc,FloatBorder:BlinkCmpDocBorder,CursorLine:BlinkCmpDocCursorLine,Search:None",
				-- which directions to show the documentation window,
				-- for each of the possible autocomplete window directions,
				-- falling back to the next direction when there's not enough space
				direction_priority = {
					autocomplete_north = { "e", "w", "n", "s" },
					autocomplete_south = { "e", "w", "s", "n" },
				},
				auto_show = true,
				auto_show_delay_ms = 200,
				update_delay_ms = 50,
			},
		},
	},
}
```

### neovim version

NVIM v0.11.0-dev-1207+g534544cbf7

### `blink.cmp` version: branch, tag, or commit

        branch main         commit dcb83d6

**Comment by soifou** [comment]
You need to append `fallback` action to your keymaps:

```lua
["<Tab>"] = { "accept", "fallback" },
["<Down>"] = { "select_next", "show", "fallback" },
["<Up>"] = { "select_prev", "show", "fallback" },
```

**Comment by oysandvik94** [comment]
I think that helped, I will try a bit more on Monday and close the issue if I dont get any more issues.

**Comment by oysandvik94** [comment]
I still get the issue sadly. Maybe I'll try building locally and debugging it.

**Comment by oysandvik94** [comment]
I found that it was related to Luasnip.

Adding the expand_snippet thing from the config solved it for me:

```lua
      expand_snippet = function(snippet)
        require("luasnip").lsp_expand(snippet)
      end,
```
