### ISSUE TITLE
Sorting is too aggressive instead of favoring "closest" match

### ISSUE THREAD

**Issue by Tesohh** [Saghen/blink.cmp#365]
### Make sure you have done the following

- [X] I have updated to the latest version of `blink.cmp`
- [X] I have read the README

### Bug Description

I recently switched to blink.cmp as nvim-cmp feels too slow.
One thing i miss from nvim-cmp is how good the completions were as they favored the "closest" item.

Here is an example from nvim-cmp using clangd:
<img width="886" alt="image" src="https://github.com/user-attachments/assets/65cf064f-c13a-4dd0-ad68-29a33b00c73b">
the results are almost perfect as you can see.

Here is the same example but in blink:
<img width="682" alt="Screenshot 2024-11-23 at 14 04 18" src="https://github.com/user-attachments/assets/23a59d4e-6993-4518-8f8c-f75cac2e906c">

it picks out some functions, but then the types are in alphabetical order which doesn't really make much sense.

I also recreated a similar scenario in fzf and as you can see it picks out int correctly.
<img width="166" alt="Screenshot 2024-11-23 at 14 08 12" src="https://github.com/user-attachments/assets/47651075-8d5a-41c1-b2ea-a457b9a85049">

(i will add more examples when i have time)

### Relevant configuration

```lua
opts = {
		keymap = { preset = "enter" },
		highlight = {
			use_nvim_cmp_as_default = true,
		},
		nerd_font_variant = "mono",
		sources = {
			completion = {
				enabled_providers = { "lsp", "path", "snippets", "buffer" },
			},
		},
		accept = { auto_brackets = { enabled = false } },
		trigger = { signature_help = { enabled = true } },
	},
```

### neovim version

v0.10.2

### `blink.cmp` version: branch, tag, or commit

v0.5.1e

**Comment by Saghen** [comment]
There was a bug causing us to always fuzzy match on the label, which broke the prefix bonus for this specific LSP since it includes a space. We're also now using the hints that LSPs provide for sorting. Hopefully the sorting looks a bit better on `main` now (you'll need to `cargo build --release` if you want to test)

**Comment by leet0rz** [comment]
> There was a bug causing us to always fuzzy match on the label, which broke the prefix bonus for this LSP since it includes a space/dot icon. We're also now using the hints that LSPs provide for sorting. Hopefully the sorting looks a bit better on `main` now (you'll need to `cargo build --release` if you want to test)

So main has better sorting and all the matches with _ or __ first will not appear first compared to what should show up? Should I just wait for a stable release on this for the sorting to be fixed? Thanks.
