### ISSUE TITLE
Wrong mode when accept lsp candidate within dartls

### ISSUE THREAD

**Issue by curtainp** [Saghen/blink.cmp#366]
### Make sure you have done the following

- [X] I have updated to the latest version of `blink.cmp`
- [X] I have read the README

### Bug Description

nvim enter wrong mode when accept from lsp candidate within dartls, `select mode` is the expected mode, but there is still in `insert mode` when I accept lsp candidate within dartls, following is the demo:

![tmp](https://github.com/user-attachments/assets/70192aa3-4ad1-4c5b-a1b2-d905c47082c5)

### Relevant configuration

```lua
{
  'saghen/blink.cmp',
  event = { 'LspAttach' },
  dependencies = 'rafamadriz/friendly-snippets',
  version = 'v0.*',
  opts = {
    keymap = {
      ['<TAB>'] = {
        'select_next',
        'snippet_forward',
        'fallback',
      },
      ['<S-TAB>'] = {
        'select_prev',
        'snippet_backward',
        'fallback',
      },
      ['<C-e>'] = {
        'hide',
        'fallback',
      },
      ['<CR>'] = {
        'accept',
        'fallback',
      },
      ['<C-b>'] = { 'scroll_documentation_up', 'fallback' },
      ['<C-f>'] = { 'scroll_documentation_down', 'fallback' },
    },
    nerd_font_variant = 'mono',
    windows = {
      documentation = {
        auto_show = true,
        auto_show_delay_ms = 50,
      },
    },
  },
  opts_extend = { 'sources.completion.enabled_providers' },
}
```

### neovim version

NVIM v0.11.0-dev-4352+g0e2f92ed79-Homebrew Build type: Release LuaJIT 2.1.1731601260

### `blink.cmp` version: branch, tag, or commit

v0.5.1

**Comment by Saghen** [comment]
Much of the accept code has been reworked in `v0.6.0`, can you try replicating the issue there? If you're still running into the issue, it would also be helpful if you could test on nvim `v0.10`

**Comment by curtainp** [comment]
> Much of the accept code has been reworked in `v0.6.0`, can you try replicating the issue there? If you're still running into the issue, it would also be helpful if you could test on nvim `v0.10`

Yeah, I retry the latest version `v0.6.1` and neovim stable version `v0.10`, but unfortunately, none of them worked.😥️

**Comment by Saghen** [comment]
You'll want to report this upstream to `neovim` since we're using `vim.snippet.expand` internally for this. Using `${0:placeholder}` seems quite odd though
