### ISSUE TITLE
Shift-enter mappings being ignored

### ISSUE THREAD

**Issue by cameron1024** [Saghen/blink.cmp#367]
### Make sure you have done the following

- [X] I have updated to the latest version of `blink.cmp`
- [X] I have read the README

### Bug Description

Firstly, thanks for the awesome plugin!

Apologies in advance if I've misunderstood the way keybinds are managed. I've found that, in certain files (in particular markdown and typst, but possibly others), the completion window appears after typing common punctuation characters, and so I'd like to be able to press shift+enter to dismiss the window and enter a newline. 

But with the configuration I have below, shift+enter behaves exactly the same as just enter by itself (i.e. it accepts the suggestion). Is there a different approach I should be using?

Thanks :grin: 

### Relevant configuration

```lua
{
    keymap = {
      preset = "enter",
      ['<Tab>'] = { "select_next", "fallback" },
      ['<S-Tab>'] = { "select_prev", "fallback" },
      ['<C-j>'] = { "select_next", "fallback" },
      ['<C-k>'] = { "select_prev", "fallback" },
      ['<C-c>'] = { "hide", "fallback" },
      ['<S-CR>'] = { "fallback" },
    },
    // ...
  }
```

### neovim version

NVIM v0.11.0-dev Build type: Release LuaJIT 2.1.1713773202 Run "nvim -V1 -v" for more info

### `blink.cmp` version: branch, tag, or commit

v0.5.1

**Comment by Saghen** [comment]
Thanks for the kind words! :) Do you mind retesting this on the latest release (`v0.6.1` as of writing), and if the bug persists, trying on neovim 0.10? The outputs of `:imap <CR>` and `:imap <S-CR>` would also be helpful

**Comment by Saghen** [comment]
Closing for now since this seems likely be an issue with your config but lmk if you're still running into this on a fresh config

**Comment by cameron1024** [comment]
Sorry, just got back to this - I realised the whole issue was actually a tmux issue - when I was checking to see kitty could actually handle `<S-CR>`, I was checking in a terminal window that wasn't running tmux, but was testing blink inside tmux, which was stopping the keybinding from working at all. The filetype-specific trigger characters seems like a very useful change in the meantime though :grin: Thanks for your effort
