### ISSUE TITLE
how to set transparent of window

### ISSUE THREAD

**Issue by shouyierban** [Saghen/blink.cmp#377]
### Feature Description

Hi  @Saghen I tried to set `winblend = "pumblend",`, But neovim prompts the following error message：
```
Error executing vim.schedule lua callback: ...m-data/lazy/blink.cmp/lua/blink/cmp/windows/lib/init.lua:100: Invalid value for option 'winblend': expected number, got string "pumblend"
stack traceback:
	[C]: in function 'nvim_set_option_value'
	...m-data/lazy/blink.cmp/lua/blink/cmp/windows/lib/init.lua:100: in function 'open'
	...ta/lazy/blink.cmp/lua/blink/cmp/windows/autocomplete.lua:117: in function 'open_with_items'
	...ta/Local/nvim-data/lazy/blink.cmp/lua/blink/cmp/init.lua:57: in function <...ta/Local/nvim-data/lazy/blink.cmp/lua/blink/cmp/init.lua:51>
``` 
### Here is the effect after setting, and I like it very much
![Quicker_20241125_144540](https://github.com/user-attachments/assets/bcd46984-a8a8-4a41-bd65-274c1cefc3bf)

by the way, if i set winblend to a number, it did not work

**Comment by a1401358759** [comment]
@shouyierban Hi, I have the same problem, how did you solve it?

**Comment by scottmckendry** [comment]
From https://github.com/scottmckendry/cyberdream.nvim/issues/147

>The problem was solved, I added winblend = 0 to the config file, and then it worked fine. Before this I had been using the default configuration and did not add winblend = 0 to my config file.

**Comment by a1401358759** [comment]
@scottmckendry I don't know why my `Pmenu` was added to the background, but I can't find it in my nvim configuration
