### ISSUE TITLE
parsing `friendly-snippets` fails because neovim doesnt support nested placeholders

### ISSUE THREAD

**Issue by Rishabh672003** [Saghen/blink.cmp#381]
### Make sure you have done the following

- [X] I have updated to the latest version of `blink.cmp`
- [X] I have read the README

### Bug Description

expanding snippets like these results in blink giving an error, that it failed to parse, because neovim doesnt  supports nested placeholders

```lua
-- this is the snippet expanded version of `ir`
if err != nil {
	${1:return ${2:nil, }${3:err}}
}
```

https://github.com/user-attachments/assets/07b1865f-861b-432d-9cac-6bd5982d2f6e

my 2 cents: I dont think it will be easy to detect this in snippets, so i think a better way would be to wrap the `accept.expand_snippet` call in a pcall

### neovim version

NVIM v0.10.2

### `blink.cmp` version: branch, tag, or commit

v0.6.1

**Comment by Saghen** [comment]
I think I prefer erroring here since the alternative would be to fail silently which would be a bit confusing. Fyi, you might want to use `Luasnip` in the meantime since it supports nested placeholders afaik

**Comment by Rishabh672003** [comment]
@Saghen idk why or how it fixed itself, really nice lol

https://github.com/user-attachments/assets/86ec987e-29ed-4786-8b2f-8b3064b0d58d
