### ISSUE TITLE
feature: select nth item in the completion list, and number items

### ISSUE THREAD

**Issue by theol0403** [Saghen/blink.cmp#382]
### Feature Description

Thank you for this incredible plugin! I am honestly blown away by the modularity, structure, and expressive configuration you've built into this. 

I am requesting the feature of showing item numbers inside the completion window - should not be too hard with your `components` system, and additionally a command to "select nth item". 

Example (with cmp): 
![image](https://github.com/user-attachments/assets/39aabfdf-0d6f-4a27-b695-646678e586bd)

Benefits of displaying item numbers:
- ability to quickly count number of times to hit Down/C-n/Tab 
- ability to provide context for a "select nth item" command/keybind
- support people with screen readers

This has been implemented in this PR to nvim-cmp: https://github.com/hrsh7th/nvim-cmp/pull/1491

Related:
- https://github.com/hrsh7th/nvim-cmp/issues/1112
- https://github.com/hrsh7th/nvim-cmp/pull/1491#issuecomment-2400578284
- https://github.com/hrsh7th/nvim-cmp/discussions/1482

**Comment by max397574** [comment]
what I think this would require
1. allow confirming items based on visible position
2. pass position in the window to the ctx used for components

**Comment by Saghen** [comment]
Here's how I configured it locally

```lua
keymap = {
  preset = 'default',
  ['<A-1>'] = { function(cmp) cmp.accept({ index = 1 }) end },
  ['<A-2>'] = { function(cmp) cmp.accept({ index = 2 }) end },
  ['<A-3>'] = { function(cmp) cmp.accept({ index = 3 }) end },
  ['<A-4>'] = { function(cmp) cmp.accept({ index = 4 }) end },
  ['<A-5>'] = { function(cmp) cmp.accept({ index = 5 }) end },
  ['<A-6>'] = { function(cmp) cmp.accept({ index = 6 }) end },
  ['<A-7>'] = { function(cmp) cmp.accept({ index = 7 }) end },
  ['<A-8>'] = { function(cmp) cmp.accept({ index = 8 }) end },
  ['<A-9>'] = { function(cmp) cmp.accept({ index = 9 }) end },
},
completion.menu.draw = {
  columns = { { 'item_idx' }, { 'kind_icon' }, { 'label', 'label_description', gap = 1 } },
  components = {
    item_idx = {
      text = function(ctx) return tostring(ctx.idx) end,
      highlight = 'BlinkCmpItemIdx'
    }
  }
}
```

**Comment by cxwx** [comment]
why not supported yet?

**Comment by FIREBAT-66** [comment]
What does <A-1> actually correspond to in terms of the physical keymap?

**Comment by max397574** [comment]
not sure if there are default ones
see the comment just above yours to see how it can be setup

**Comment by logrusx** [comment]
Can this work in command mode too?

EDIT:
Actually it can https://cmp.saghen.dev/modes/cmdline.html :

```lua
cmdline = {
  keymap = { preset = 'inherit' },
  completion = { menu = { auto_show = true } },
},
```

**Comment by cyb3rkun** [comment]
is it possible to select an item based on index without accepting it?
I'd like to be able to select item without accepting it automatically pls
