### ISSUE TITLE
LSP completion is not triggered with zk.nvim

### ISSUE THREAD

**Issue by ahmedelgabri** [Saghen/blink.cmp#385]
### Make sure you have done the following

- [X] I have updated to the latest version of `blink.cmp`
- [X] I have read the README

### Bug Description

When using https://github.com/zk-org/zk-nvim completion is not working at all, not even triggered. The LSP is attached and everything is working fine, but completion is not.

As far as I understand completion should be part of the LSP provider, but it's not working.

I tried `[[]]` wiki-links, `[]()` normal Markdown links and <kbd>CTRL</kbd>+<kbd>SPC</kbd>, none triggered completions. Buffer & path completion is working fine though.

### Relevant configuration

```lua
sources = {
completion = {
	enabled_providers = {
		'lsp', -- <-- should be coming as part of LSP provider
		'luasnip',
		'path',
		'snippets',
		'buffer',
		'lazydev',
		'emoji',
	},
},
```

### neovim version

v0.10.2

### `blink.cmp` version: branch, tag, or commit

v0.6.1

**Comment by Saghen** [comment]
I'm not able to replicate on the latest release (`v0.7.1`). It seems to work on my machine inside of a `[[]]`

```lua
{
  'zk-org/zk-nvim',
  config = function()
    require('zk').setup({
      picker = 'telescope',
      lsp = {
        -- `config` is passed to `vim.lsp.start_client(config)`
        config = {
          cmd = { 'zk', 'lsp' },
          name = 'zk',
        },

        -- automatically attach buffers in a zk notebook that match the given filetypes
        auto_attach = {
          enabled = true,
          filetypes = { 'markdown' },
        },
      },
    })
  end,
}
```

**Comment by ahmedelgabri** [comment]
Finally, managed to look into this deeply, it was an issue on my side. One machine had a wrong version of `zk`, now everything is working fine. Thanks!
