### ISSUE TITLE
Allow utf-8 trigger characters

### ISSUE THREAD

**Issue by mikavilpas** [Saghen/blink.cmp#388]
### Feature Description

Currently it's not possible to trigger a search with https://github.com/mikavilpas/blink-ripgrep.nvim if the last character of the current word is a special character:

https://github.com/user-attachments/assets/1ebbf977-a5fc-425f-830f-728ae3d07776

I noticed the implementation seems to allow a list of characters that are allowed to trigger a search - maybe this is the cause of the issue (I have not defined the ö character to be a trigger character):

https://github.com/mikavilpas/blink.cmp/blob/f1b8abe2ca7f8b369c8cd48ddfb991a690d20345/lua/blink/cmp/sources/lib/init.lua?plain=1#L71-L86

However, utf-8 contains a very large amount of possible characters 😄 I think it's a very bad idea to list all of them - I think it will not perform well. Do you think it would be possible to allow sources to define if the character is acceptable with a function?

Because lua regexes do not apparently support utf-8 either, I think they will not work. Alternatively, chatgpt gave me `vim.lpeg.R("\128\255")` which seems to match many unicode characters well (there are examples in the [tests](https://github.com/mikavilpas/blink-cmp-rg.nvim/blob/1cfaf8db14fdba802886a7bd30c1ae49dba93a91/spec/blink-ripgrep/get_prefix_spec.lua?plain=1#L105-L129))

**Comment by fmoralesc** [comment]
This happens with the buffer source too. The culprit is the code that gets the candidate words, which uses a regex that only detects sequences of ASCII characters (see #130 ). I am currently modifying blink locally to use the regex `[\p{Latn}][\p{Latn}-]{2,31}[\p{Latn}]`, which captures any latin-based word (and includes hyphens).
