### ISSUE TITLE
Blink overrides existing insert-mode bindings

### ISSUE THREAD

**Issue by julienvincent** [Saghen/blink.cmp#39]
I'm just raising [my comment](https://github.com/Saghen/blink.cmp/issues/20#issuecomment-2400305846) from #20 into a new issue for better tracking.

As of ecb3510 blink now replaces insert-mode keybindings in the buffer even when it isn't active / currently completing.

An example of why this causes a problem is that this breaks `map_cr = true` behaviour from `nvim-autopairs`:

When I am editing with nvim-autopairs I expect the following behaviour:

```rust
fn main() {|}
// Press <Cr>
fn main() {
  |
}
```

But this is broken with the following blink config:

```lua
require("blink.cmp").setup({
  keymap = {
    accept = { "<Cr>" },
  },
})
```

Ideally we can find a way to both allow `<Cr>` to accept without swallowing existing `<Cr>` mappings on the buffer.

This behaviour pairing works fine on `nvim-cmp`, so it should at least be possible.

---

P.S Awesome plugin btw, sorry for making so much noise :)

**Comment by Saghen** [comment]
> sorry for making so much noise :)

Don't be! You've been super helpful

**Comment by julienvincent** [comment]
It works! Thanks!

**Comment by benfrain** [comment]
First time blink user so possibly I'm doing something wrong here but I still seem to see this same issue using nvim-autopairs.

If I enter `<CR>` here: `const operator () => {|}` nothing happens. In fact, pressing <cr> anywhere in Insert mode does nothing.

My config:

```lua
  {
    "saghen/blink.cmp",
    lazy = false, -- lazy loading handled internally
    -- optional: provides snippets for the snippet source
    dependencies = "rafamadriz/friendly-snippets",

    -- use a release tag to download pre-built binaries
    version = "v0.5.0",
    opts = {
      keymap = {
        ["<CR>"] = { "select_and_accept" },
      },
      highlight = {
        use_nvim_cmp_as_default = true,
      },
      nerd_font_variant = "normal",
      accept = { auto_brackets = { enabled = true } },
      trigger = { signature_help = { enabled = true } },
    },
  },
```

Is there anything obvious I have wrong here?

**Comment by Saghen** [comment]
You're missing the `"fallback"` command after your `"select_and_accept"`
