### ISSUE TITLE
Signature window doesn't appear after inserting function from completion list

### ISSUE THREAD

**Issue by bartekjaszczak** [Saghen/blink.cmp#393]
### Make sure you have done the following

- [X] I have updated to the latest version of `blink.cmp`
- [X] I have read the README

### Bug Description

The signature window doesn't appear immediately when I'm selecting function from the completion list. The function and its parameters are inserted correctly and the cursor jumps to the first parameter, but the signature window doesn't appear until I trigger it manually by deleting pre-inserted brackets and type the left bracket again (or insert a comma after first argument).

The behaviour is identical no matter whether the `nvim-autopairs` plugin is enabled or not.

### Relevant configuration

```lua
accept = { auto_brackets = { enabled = true } },
signature = {
  enabled = true,
  trigger = {
    show_on_insert_or_trigger_character = true,
  },
},
windows = {
  autocomplete = {
    border = "rounded",
    selection = "manual",
  },
  documentation = {
    border = "rounded",
    auto_show = true,
  },
  signature_help = {
    border = "rounded",
  }
}
```

### neovim version

NVIM v0.10.2

### `blink.cmp` version: branch, tag, or commit

main

**Comment by Saghen** [comment]
Fyi, on main, the configuration was reworked

**Comment by bartekjaszczak** [comment]
Thanks a lot! I'll double check the config.
