### ISSUE TITLE
No equivalent to `autocomplete.auto_show` in reworked config

### ISSUE THREAD

**Issue by jungomi** [Saghen/blink.cmp#402]
### Make sure you have done the following

- [X] I have updated to the latest version of `blink.cmp`
- [X] I have read the README

### Bug Description

With the reworked config it is no longer possible to disable automatically triggering the completion. I only want to trigger the completion with the key mapping on demand, not having it constantly pop up.

Before the rework, this was achieved by setting `autcomplete.auto_show = false`, but I have not found anything that could do the same in the new config.

### Relevant configuration

```lua
-- Config prior to rework
windows = {
  autocomplete = {
    auto_show = false,
  },
}
```

### neovim version

NVIM v0.10.2

### `blink.cmp` version: branch, tag, or commit

main

**Comment by Saghen** [comment]
Setting both `show_on_keyword = false` and `show_on_trigger_character = false` should effectively be equivalent to `auto_show`. The only caveat is completions will no longer be prefetched so there will be a delay on opening

**Comment by jungomi** [comment]
Thanks, that works great.

Prefetching would certainly be nice to have as well. I'd personally want the `ghost_text` to be tied to the `menu`, meaning that the prefetching should be completely in the background without having activated anything. But I guess you mean that both `menu` and `ghost_text` support the `auto_show` configuration independently.

I'm sure you will find an appropriate solution, just to give you my use case, as that seems to be the minority: I want everything to be hidden while prefetching happens in the background, then press the key map to show everything (`menu` + `ghost_text` + `documentation`).
This is exactly what I have got with the current config (without having the prefetching, as you mentioned).

That being said, I definitely see the appeal to have `ghost_text` alone, which would allow you to accept the first suggestion without opening the menu or open the menu to select another candidate. Now that I have written this out, I actually think that I might be using this, if it were implemented.

**Comment by jungomi** [comment]
I just realised that with these new settings it is impossible to narrow down the results once the completion is triggered, as it immediately closes the menu when typing any character.

## Expected Behaviour

- Trigger completion with key mapping
- Type to fuzzy match completion results (keeps menu open)
- Accept / Cancel / Hide to finish completion, which hides the menu

Essentially, from the time of triggering the completion with the key mapping it should temporarily behave as `show_on_keyword = true` until the menu is closed by one of the actions, or the keyword has been finished (e.g. when opening a parenthesis). 

That is also how it functioned previously.
