### ISSUE TITLE
LSP does not show type docs

### ISSUE THREAD

**Issue by shawnyu5** [Saghen/blink.cmp#403]
### Make sure you have done the following

- [X] I have updated to the latest version of `blink.cmp`
- [X] I have read the README

### Bug Description

Take the following code in Go:

```go
package main

// Person a person
type Person struct {
	// Name of the person
	Name string
	// Age of the person
	Age int
}

func main() {
	p := Person{
		Name: "Shawn",
		Age:  10,
	}

}
```

When typing in the fields of the Person struct, I expect when I hover over a struct field in the drop down menu, it would show the documentation of that field, as observed when using cmp:

![cmp](https://github.com/user-attachments/assets/526f296e-db35-40cb-b990-27dd5a6d1c7b)

Using blink:

![blink](https://github.com/user-attachments/assets/e4b1bbe2-2c39-4c91-a092-3cff1e4bb432)

### Relevant configuration

```lua
The LSP source config, taken from the docs:


				lsp = {
					name = "LSP",
					module = "blink.cmp.sources.lsp",

					--- *All* of the providers have the following options available
					--- NOTE: All of these options may be functions to get dynamic behavior
					--- See the type definitions for more information
					enabled = true, -- whether or not to enable the provider
					transform_items = nil, -- function to transform the items before they're returned
					should_show_items = true, -- whether or not to show the items
					max_items = nil, -- maximum number of items to return
					min_keyword_length = 0, -- minimum number of characters to trigger the provider
					fallback_for = {}, -- if any of these providers return 0 items, it will fallback to this provider
					score_offset = 0, -- boost/penalize the score of the items
					override = nil, -- override the source's functions
				},
```

### neovim version

NVIM v0.11.0-dev-1247+g5897994cb7

### `blink.cmp` version: branch, tag, or commit

v0.6.1

**Comment by Saghen** [comment]
Sounds like you're looking for `{ completion = { documentation = { auto_show = true } } }`

**Comment by shawnyu5** [comment]
Ooo mb, shoulda looked at the docs more closely. Thanks for the quick response!
