### ISSUE TITLE
Accept doesn't work if the completion item is matched

### ISSUE THREAD

**Issue by lopi-py** [Saghen/blink.cmp#41]
![image](https://github.com/user-attachments/assets/15453ae1-140a-4707-861f-6f1c70f213f7)
If the text I typed is exactly the same as the first completion item, the accept keymap won't do nothing

**Comment by 3rd** [comment]
If accepting the completion triggers an auto-import, it will do it every time the accept key is pressed adding multiple imports.

**Comment by davawen** [comment]
Nice job!
Thank you! ❤️
