### ISSUE TITLE
Completion menu does not close with "auto_insert"

### ISSUE THREAD

**Issue by Lun4m** [Saghen/blink.cmp#415]
### Make sure you have done the following

- [X] I have updated to the latest version of `blink.cmp`
- [X] I have read the README

### Bug Description

The completion menu stays open after pressing a special character, for example, space or `(`.
Moreover, if I keep typing with the menu open, the auto inserted text gets trimmed to the only the letters I typed before selecting the item. But this also seems to depend on the character you type (?).

![GIF 01-12-2024 19-45-59](https://github.com/user-attachments/assets/6ae144f0-2de0-410f-9c09-3ec29ecc0d01)

### Relevant configuration

```lua
keymap = {
  ["<C-e>"] = { "hide", "fallback" },
  ["<CR>"] = { "accept", "fallback" },

  ["<Tab>"] = { "select_next", "fallback" },
  ["<S-Tab>"] = { "select_prev", "fallback" },

  ["<C-j>"] = { "snippet_forward", "fallback" },
  ["<C-k>"] = { "snippet_backward", "fallback" },

  ["<C-b>"] = { "scroll_documentation_up", "fallback" },
  ["<C-d>"] = { "scroll_documentation_down", "fallback" },
},

completion = {
  list = {
    selection = "auto_insert",
  },
}
```

### neovim version

NVIM v0.10.1 Build type: Release LuaJIT 2.1.1713484068

### `blink.cmp` version: branch, tag, or commit

1f6a8e2

**Comment by s-cerevisiae** [comment]
I suspect that the auto inserted text is getting cancelled when completion is triggered for the second time.
