### ISSUE TITLE
`menu.lua:68`: Cursor position outside buffer

### ISSUE THREAD

**Issue by stefanboca** [Saghen/blink.cmp#416]
### Make sure you have done the following

- [X] I have updated to the latest version of `blink.cmp`
- [X] I have read the README

### Bug Description

Got this error somehow:
![image](https://github.com/user-attachments/assets/df33c6da-c1f6-4f21-8fd2-db6d110932f6)
I wasn't doing anything unusual, but I can't reproduce this.

raw text:
```
 Error executing vim.schedule lua callback: ...lazy/blink.cmp/lua/blink/cmp/completion/windows/menu.lua:68: Cursor position outside buffer
stack traceback:
	[C]: in function 'nvim_win_set_cursor'
	...lazy/blink.cmp/lua/blink/cmp/completion/windows/menu.lua:68: in function 'open'
	...lazy/blink.cmp/lua/blink/cmp/completion/windows/menu.lua:55: in function 'open_with_items'
	...re/nvim/lazy/blink.cmp/lua/blink/cmp/completion/init.lua:40: in function 'callback'
	.../nvim/lazy/blink.cmp/lua/blink/cmp/lib/event_emitter.lua:28: in function 'emit'
	...re/nvim/lazy/blink.cmp/lua/blink/cmp/completion/list.lua:73: in function 'show'
	...re/nvim/lazy/blink.cmp/lua/blink/cmp/completion/init.lua:32: in function <...re/nvim/lazy/blink.cmp/lua/blink/cmp/completion/init.lua:29>
```

### Relevant configuration

```lua
menu = {
  winblend = vim.o.pumblend,
  draw = {
    columns = { { "kind_icon" }, { "label", "label_description", gap = 1 }, { "kind" } },
  },
},
```

### neovim version

NVIM v0.11.0-dev+1261-gab9cfc4dc Build type: RelWithDebInfo LuaJIT 2.1.1720049189

### `blink.cmp` version: branch, tag, or commit

main (4559ec5)

**Comment by s-cerevisiae** [comment]
Encountered the same thing here, maybe it has something to do with window size or triggering completion at the right edge of the screen.
