### ISSUE TITLE
multiple placeholders for a tabstop

### ISSUE THREAD

**Issue by enkyuan** [Saghen/blink.cmp#418]
### Make sure you have done the following

- [X] I have updated to the latest version of `blink.cmp`
- [X] I have read the README

### Bug Description

when i try to accept a snippet (in the screenshot it's typescript) a notification error appears saying that there are multiple placeholders for a tabstop position, i.e., $1. not exactly sure what's the issue and i've done my fair share of googling.
<img width="1424" alt="Screenshot 2024-12-01 at 23 55 14" src="https://github.com/user-attachments/assets/25d9dffc-30d7-41f3-b571-1403ee5b8a78">

### Relevant configuration

```lua
sources = {
      completion = {
        enabled_providers = { 'lsp', 'path', 'snippets', 'buffer' },
      },
},
```

### neovim version

NVIM v0.10.2

### `blink.cmp` version: branch, tag, or commit

main

**Comment by enkyuan** [comment]
@Saghen a dupe of this issue was closed ~2 wks ago but i'm pretty sure it hasn't been resolved. let me know if there's a sure solution to this problem

**Comment by enkyuan** [comment]
i'm pretty sure this applies to typescript snippets for react, etc. only...my guess is that the plugin might be conflicting with another plugin but i'm using blink with cmp...

**Comment by Saghen** [comment]
Linking #335 for visibility

https://github.com/neovim/neovim/blob/master/runtime/lua/vim/snippet.lua#L490

This an intentional decision by the built-in snippets. `nvim-cmp` handles this because it uses it's own snippet parsing logic, where as blink uses the built-in snippet parsing. The typescript react snippets should be changed to have increasing tabstops

**Comment by enkyuan** [comment]
@Saghen slightly confused by your response...i don't have a configuration for the typescript react snippets...so how can i change them to have increasing tabstops?

**Comment by Saghen** [comment]
The snippets likely come from [friendly-snippets](https://github.com/rafamadriz/friendly-snippets) or your LSP
