### ISSUE TITLE
[FEAT] Rewrite in rust

### ISSUE THREAD

**Issue by a-usr** [Saghen/blink.cmp#422]
### Feature Description

Now, I know the title of this issue is a bit odd, considering that the fuzzy matcher is already written in Rust. However a majority of the code is still written in lua, and thus prone to only get optimized at runtime. 

Now, you may or may not ask: 
So do you want me / us to port the majority of the code to rust and do everyrhing over the luajit ffi?

And the answer to that is actually no! You might already know this, but It is actually possible to write a neovim plugin in any language that compiles to a native binary, and that without even having to communicate with neovim via msgpack rpc. Instead you just call the neovim functions directly!

Now, for that you'd of course need bindings, however Rust actually has those already: https://github.com/noib3/nvim-oxi

The benefits, you might ask? If blink was rewritten in rust, you could take full advantage of the rust ecosystem. Also there might be performance to gain, since you could hook up the autocmds related to completion directly to Rust functions instead of taking a detour over lua.

However there are downsides too of course. You'd probably lose a portion of the contributors, and you also effectively scrap a big amout of progress. Furthermore the progress that has been made with the cmdline completions would also be lost.

**Comment by a-usr** [comment]
To clarify: I am aware that a full rewrite would be very time-consuming, which is why this probably is something that should be a low priority at best.

**Comment by a-usr** [comment]
> Funny you mention this, I almost rewrote the plugin in Rust early in development but decided against it:
> 
> * Fewer contributors
> * `vim.lsp` makes robust LSP handling quite easy
> * Inflexible configuration (i.e. we allow Lua functions for many config options for dynamic behavior, which would be difficult to support with a rust plugin afaict)
> 
> However, I am planning to rewrite one of my unreleased plugins in Rust ([blink.tree](https://github.com/Saghen/blink.nvim)) where the core of the plugin is async io and git ffi so keep an eye out for that :)

Totally understandable. However I'd like to mention that:
- Even if nvim-oxi doesnt have bindings for the `vim` global, you could still access it via the lua context (similar to how nvim-oxi does it for the vim.schedule function, whose c counterpart isnt exported by nvim)
- Considering that the types crate inside nvim-oxi has a functions type, I'd assume that allowing functions in the config wouldnt pose an issue.


However your point regarding fewer contributors most likely still stands, although I recon that the chances that more contributors join are about equal. Ultimately its your project of course, and I wish you all the best with it :) 

ps: 
Additionally, it is also very much a possibility to handle all the lsp related stuff in lua, since you can just `require` a correctly built rust plugin like any other lua module. Which gives me the idea to give you the suggestion to do that with the fuzzy matcher, instead of using the luajit ffi.

**Comment by Saghen** [comment]
That's super helpful, thank you! I think I'll keep this plugin mostly Lua since, like you mentioned, a rewrite would be a huge effort and the plugin is beginning to reach stability. Fyi, like `nvim-oxi`, we use `mlua` for loading the rust bits as a lua module. I ought to update the readme
