### ISSUE TITLE
Regression: spurious warnings regarding the new config

### ISSUE THREAD

**Issue by chrisgrieser** [Saghen/blink.cmp#427]
Basically the same issue as #370, just for the new config. (nice work on that btw, config feels more logical now)

![Pasted image 2024-12-02 at 21 45 52@2x](https://github.com/user-attachments/assets/88622198-b2a9-4d0c-9900-bc8cb5905608)

**Comment by Saghen** [comment]
Ah yep, sorry about that, I had meant to get to this before releasing. For anyone looking for a quick fix, you can throw in a `---@diagnostic disable missing-fields` (applies to the whole file)

**Comment by NStefan002** [comment]
@Saghen I don't know what your plans are regarding this issue (do you leave it for just before the release or ...), but if you want I'm willing to open a PR that closes this issue.

**Comment by Saghen** [comment]
A PR would be great, thanks! I want to keep all of the config required internally so we would need to copy all the config options into `blink.cmp.$typePartial` (i.e. `blink.cmp.SourceProviderConfigPartial`). Maybe we could have a single file in `/config` that houses all of these so they're not littered around the codebase

**Comment by Congee** [comment]
> Ah yep, sorry about that, I had meant to get to this before releasing. For anyone looking for a quick fix, you can throw in a `---@diagnostic disable: missing-fields` (applies to the whole file)

or use it with `---@diagnostic enable: missing-fields` to apply the rule to the file partially

**Comment by Saghen** [comment]
Yeah I prefer strict types in the individual files for visibility so `types_partial.lua` sounds good
