### ISSUE TITLE
Regression: Snippet reload function is broken

### ISSUE THREAD

**Issue by chrisgrieser** [Saghen/blink.cmp#428]
### Make sure you have done the following

- [X] I have updated to the latest version of `blink.cmp`
- [X] I have read the README

### Bug Description

The latest update seems to have broken the previously working snippet reload function `require('blink.cmp').sources.reload()` (a regression of the function breaking in #28)

It now throws the error `attempt to index field 'sources' (a nil value)`, I assume the function has moved somewhere else now.

### neovim version

NVIM v0.10.2

### `blink.cmp` version: branch, tag, or commit

0.7.1

**Comment by Saghen** [comment]
You'll want to use `require('blink.cmp.sources.lib').reload()` for now. I'll expose it at `require('blink.cmp').reload()` in the next release

**Comment by soifou** [comment]
As a side note, it might also be interesting to allow reloading only a specific provider, eg. `require('blink.cmp').reload('snippets')`.
