### ISSUE TITLE
[feature] some improvements for fuzzy search

### ISSUE THREAD

**Issue by kaiphat** [Saghen/blink.cmp#43]
I would like to have opportunity to change fuzzy search as described below. 
Several examples:

<img width="647" alt="image" src="https://github.com/user-attachments/assets/51cd2b3f-f9f9-4e4c-868c-805569009479">

Expectations:
- match `process` because shorter
- match `process` because both start from lowercase letter `p`

---

 <img width="404" alt="image" src="https://github.com/user-attachments/assets/dbaf9a6b-34d3-4ce0-b501-414a57a22efa">

Expectations:
- opportunity to see source for import
- optional: opportunity to skip the same completions

---

<img width="647" alt="image" src="https://github.com/user-attachments/assets/27d39947-e1ea-4978-a86c-08d815d6d1b9">

Expectations:
- i would like to see `import` word on first position.

---

<img width="647" alt="image" src="https://github.com/user-attachments/assets/53b793a9-6153-459b-b0f5-d2d234300b91">

Expectations:
- should match `Headers` because i started from capitalized letter `H`

Actually there are a lot of similar examples, i hope you are planning to develop that side.
Thank you! You are doing revolution:)

**Comment by Saghen** [comment]
The latest commit https://github.com/Saghen/blink.cmp/commit/63b7b2219f4595973225a13e6e664fc836ee305c includes a couple changes to [frizbee](https://github.com/Saghen/frizbee) to help with these cases:

- Delimiter bonuses have been fixed
- Added bonus for matching case

If you continue to run into any odd matches, please send them here!

**Comment by kaiphat** [comment]
Thank you! Will watch
