### ISSUE TITLE
Not showing all completions; popup docs window off in the wilderness

### ISSUE THREAD

**Issue by gwww** [Saghen/blink.cmp#436]
### Make sure you have done the following

- [X] I have updated to the latest version of `blink.cmp`
- [X] I have read the README

### Bug Description

Running 0.7.2 released just moments ago.

Edit a Lua file. Start typing and only one suggestion is shown. Type first letter of that suggestion and the rest show.

Using <C><Space> to popup docs. First doc shows in right spot. Second doc in spaced way out there. When cursor through the docs again they show up properly.

Video should be self explanatory:

https://github.com/user-attachments/assets/83dd6015-60ad-4797-9e63-ca6691257c73

### neovim version

NVIM v0.10.2 Build type: Release LuaJIT 2.1.1731601260

### `blink.cmp` version: branch, tag, or commit

0.7.2

**Comment by chrisgrieser** [comment]
I have the same issue. With 0.7.2, the menu window size is sometimes all over the place. This occurs when typing `local` in a lua file, with the default blink.cmp settings:

![Pasted image 2024-12-03 at 19 45 25](https://github.com/user-attachments/assets/7ec90bc5-1291-462c-8374-42e3b96795c3)
