### ISSUE TITLE
`completion.menu.draw.treesitter` should only affect items from the LSP source

### ISSUE THREAD

**Issue by chrisgrieser** [Saghen/blink.cmp#438]
### Feature Description

Just discovered the feature, and I quite like it. However, by applying it to *all* items, you also get a lot of spurious highlighting of words such as `in` or `file`, often used for example in names of snippets.

I think limiting the highlighting to items from the LSP source only would produce the best result by highlighting the correct things, while not highlighting things that are not are nor code.

![Pasted image 2024-12-03 at 19 48 48](https://github.com/user-attachments/assets/09cb8b7f-2e64-4f1b-8978-03d7beeb6f91)

**Comment by Saghen** [comment]
For anyone looking to implement this, the `treesitter` option should be changed to accept a table of `source_ids` that it applies to. The documentation should then recommend `treesitter = { "lsp" }`
