### ISSUE TITLE
Error while downloading blink.cmp pre-built binary: Unknown error while getting pre-built binary. Consider re-installing

### ISSUE THREAD

**Issue by idelice** [Saghen/blink.cmp#44]
Config

```lua
return {
  "saghen/blink.cmp",
  lazy = false, -- lazy loading handled internally
  -- optional: provides snippets for the snippet source
  dependencies = "rafamadriz/friendly-snippets",

  -- use a release tag to download pre-built binaries
  version = "v0.*",
  -- OR build from source, requires nightly: https://rust-lang.github.io/rustup/concepts/channels.html#working-with-nightly-rust
  -- build = 'cargo build --release',

....
```

**Comment by tarkin88** [comment]
You need to specify a version or use a nightly support. Change to: 
```
return {
  "saghen/blink.cmp",
  lazy = false,
  dependencies = "rafamadriz/friendly-snippets",
  v0.2.1

```

**Comment by hans-chrstn** [comment]
am i doing something wrong here? 
```
return {
  'saghen/blink.cmp',
  lazy = false, -- lazy loading handled internally
  dependencies = 'rafamadriz/friendly-snippets',
  version = 'v0.2.0',

  opts = {
    highlight = {
      use_nvim_cmp_as_default = true,
    },
    nerd_font_variant = 'normal',
  }
}
```
I've already tried using versions v0.2.0 and v0.2.1 with no luck. i'm using nixos if it helps

**Comment by idelice** [comment]
> You need to specify a version or use a nightly support. Change to:
> 
> ```
> return {
>   "saghen/blink.cmp",
>   lazy = false,
>   dependencies = "rafamadriz/friendly-snippets",
>   v0.2.1
> ```

Please see my attached config. It has already version defined, but somehow the error is gone now. Idk what's happening... i'm getting one error after another using this plugin

**Comment by Saghen** [comment]
@hans-chrstn I noticed nixvim in your config in which case you should be able to use the flake in the repo, rather than prebuilt binaries

@idelice Send over the `~/.local/share/nvim/lazy/blink.cmp` folder so I can have a look around. Also double check that neovim has access to `curl` and `git`

**Comment by Saghen** [comment]
Merging this with #68 since both are related to download failing
