### ISSUE TITLE
Support `nofile` buftypes

### ISSUE THREAD

**Issue by olimorris** [Saghen/blink.cmp#440]
I'm looking to add a source for my [plugin](https://github.com/olimorris/codecompanion.nvim), to blink.

For context, the buffer I would like blink to work in is a custom filetype but with a buftype of `nofile`. So with my custom source:

```lua
-- codecompanion.integrations.blink.init.lua
local M = {}

function M.new()
  return setmetatable({}, { __index = M })
end

function M:get_trigger_characters()
  return { "/" }
end

function M:enabled(context)
  if context then
    return vim.bo[context.bufnr].filetype == "codecompanion"
  end
  return true -- force this to be enabled for the purposes of this demo
end

function M:get_completions(context, callback)
  print("ENABLED")
end

return M
```

and my lazy config:

```lua
{
  "saghen/blink.cmp", -- Better completion
  build = "cargo build --release",
  event = "InsertEnter",
  opts = {
    sources = {
      compat = {},
      completion = {
        enabled_providers = { "lsp", "path", "snippets", "buffer", "codecompanion" },
      },
      providers = {
        codecompanion = {
          name = "CodeCompanion",
          module = "codecompanion.integrations.blink",
          enabled = true,
        },
      },
    },
  },
},
```

I will only ever see the printed message `enabled`, if I do `:set buftype=` and then hit the trigger character in the buffer.

**Comment by KarlEricsson** [comment]
A simple solution for this could be to add a setting alongside `blocked_filetypes` that overrides the check for buftype and always enables blink? Maybe something like `always_enable_in` or `always_enable_filetypes`. Most plugins I can think of that would need this functionality have their own filetype. I guess sources should be able to add their filetypes and maybe it should be a source setting? But if you want to limit the number of settings, or as temporary solution, you could just add the filetype override setting and instruct the user to add the plugin filetype in the install instructions of the source?

Really looking forward to having blink support in CodeCompanion, it's a great plugin!
