### ISSUE TITLE
Failed to get completions with error (fast event context)

### ISSUE THREAD

**Issue by soifou** [Saghen/blink.cmp#446]
### Make sure you have done the following

- [X] I have updated to the latest version of `blink.cmp`
- [X] I have read the README

### Bug Description

I intermittently get the following errors, often when I'm typing fast (eg. writing an email):

```
failed to get completions with error: ...are/nvim/lazy/blink.cmp/lua/blink/cmp/sources/buffer.lua:80: E5560: nvim_list_wins must not be called in a fast event context
failed to get completions with error: ...re/nvim/lazy/blink.cmp/lua/blink/cmp/sources/luasnip.lua:36: E5560: nvim_get_option_value must not be called in a fast event context
failed to get completions with error: vim/fs.lua:0: E5560: nvim_get_option_value must not be called in a fast event context
failed to get completions with error: /usr/local/share/nvim/runtime/lua/vim/lsp.lua:789: E5560: nvim_get_current_buf must not be called in a fast event context
failed to get completions with error: ...m/lazy/blink.cmp/lua/blink/cmp/sources/snippets/init.lua:18: E5560: nvim_get_option_value must not be called in a fast event context
failed to get completions with error: ...are/nvim/lazy/blink.cmp/lua/blink/cmp/sources/buffer.lua:80: E5560: nvim_list_wins must not be called in a fast event context
failed to get completions with error: ...re/nvim/lazy/blink.cmp/lua/blink/cmp/sources/luasnip.lua:36: E5560: nvim_get_option_value must not be called in a fast event context
failed to get completions with error: vim/fs.lua:0: E5560: nvim_get_option_value must not be called in a fast event context
failed to get completions with error: /usr/local/share/nvim/runtime/lua/vim/lsp.lua:789: E5560: nvim_get_current_buf must not be called in a fast event context
failed to get completions with error: ...m/lazy/blink.cmp/lua/blink/cmp/sources/snippets/init.lua:18: E5560: nvim_get_option_value must not be called in a fast event context
failed to get completions with error: vim/fs.lua:0: E5560: nvim_get_option_value must not be called in a fast event context
failed to get completions with error: vim/fs.lua:0: E5560: nvim_get_option_value must not be called in a fast event context
failed to get completions with error: vim/fs.lua:0: E5560: nvim_get_option_value must not be called in a fast event context
```

This seems related to the completion list that keeps popping up and performing some tasks that can't be fully processed. 

By reading this [issue](https://github.com/Saghen/blink.cmp/issues/402), I saw you implemented recently an `auto_show` for the menu, but what do you think of adding an `auto_show_delay_ms` similar to what you did with the documentation? On the one hand this would alleviate some unnecessary work (and probably avoid this issue), and on the other hand, it would, at least for me, be a bit more "intuitive" (appearing when really needed without the need to trigger it manually).

Blink is fast, sometimes too fast so I would love to experiment this kind of fine-tuning. 
Anyway thanks for the amazing plugin.

### neovim version

v0.11.0-dev+gab9cfc4dc3

### `blink.cmp` version: branch, tag, or commit

85f318b6db5

**Comment by vdegenne** [comment]
Could it be related: https://github.com/LazyVim/LazyVim/issues/4958

**Comment by soifou** [comment]
No I'm talking only here about the frequency of appearance for the completion menu when typing "fast". Please create an new issue for your specific snippet problem.

**Comment by Saghen** [comment]
Closed by https://github.com/Saghen/blink.cmp/commit/342c5ed6336d2850c59937747daccb4e880319e0

**Comment by soifou** [comment]
Thanks for considering it, yes I'll open an issue
