### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Saghen** [Saghen/blink.cmp#448]
Likely to be hosted on [gitbook](https://gitbook.com/) and needs an automated conversion to vim help. Some interesting things to include (to be expanded):

- Recipes
  - Copilot config: https://github.com/Saghen/blink.cmp/discussions/226#discussioncomment-11467053
  - Config for borders on all windows (maybe have a config option in `appearance`?)
  - Configuring icon providers (i.e. nvim-web-devicons and [mini.icons](https://github.com/Saghen/blink.cmp/discussions/458))
- Guide on how to write providers
  - Add note about `ctx` becoming stale during `execute`
- Environment setup for development and explanation of architecture
- Add instructions for minimal reproduction #485 

Feel free to post anything you think should be included in the docs

**Comment by groig** [comment]
> Feel free to post anything you think should be included in the docs

A guide on how to write providers maybe?

**Comment by the-fuckin-nobody** [comment]
>Feel free to post anything you think should be included in the docs

How to use external icon providers for kind icons like `nvim-web-devicons/mini.icons`? would also be a nice idea
