### ISSUE TITLE
Windows overlapping -> Cannot see signature help

### ISSUE THREAD

**Issue by stefanwatt** [Saghen/blink.cmp#45]
![image](https://github.com/user-attachments/assets/de4507d8-ce69-4baa-a658-2848a05ff9ef)
I could probably make a PR for this if you want me to.
IMO then window layout should be calculated something like this:

1. calculate max(autocomplete.height, documentation.height) -> they should start on the same row
2. add height of signature help -> combined height
3. calculate top of total layout based on cursor relative to viewport, in signature help windows bottom row should be one row above cursor row, the other two windows top row should be one row below cursor. 

But....what happens if there's not enough room in the viewport to fit the autocompletion window below the cursor?
It would have to be placed above. If that's the case then the signature help window would be placed awkwardly far above (or not displayed?).

**Comment by Saghen** [comment]
> calculate max(autocomplete.height, documentation.height) -> they should start on the same row

Totally agree

> But....what happens if there's not enough room in the viewport to fit the autocompletion window below the cursor?
It would have to be placed above. If that's the case then the signature help window would be placed awkwardly far above (or not displayed?).

I was thinking it would make sense to put the signature help in place of the documentation, and have the documentation only show up on manual trigger. Wdyt?

**Comment by stefanwatt** [comment]
I guess it's up to preference 🤷
I agree that displaying both signature help and autocompletion window is probably not gonna work.
So maybe add a field on `blink.cmp.WindowConfig` like `displayWhenOverlapping`.
Possible values `signature-help` and `autocompletion`. Default value `signature-help`

**Comment by patrick330602** [comment]
Also have the similar problem... but mine have the issue of also covering up the letter (there is a d under the signature help) ![Screenshot 2024-10-22 at 10 36 21](https://github.com/user-attachments/assets/e7c921dc-f0c6-4d8a-be3c-e9ce8925b6c3)

**Comment by idelice** [comment]
@Saghen  Any updates on this?

**Comment by Saghen** [comment]
There are still cases where the autocomplete covers the signature help so I'll keep it open

**Comment by Saghen** [comment]
The signature help will now move to the opposite side of the completion menu and the documentation window will not overlap it

![image](https://github.com/user-attachments/assets/4d3fa4c3-d8f7-4ab0-b52d-d9bb899f551d)

**Comment by calvinchoy** [comment]
Is there a configuration I need to set to prevent autocomplete overlapping the signature window?

When I autocomplete a function, the cursor moves inside the parentheses for inserting arguments. Without typing it shows the autocomplete menu while overlapping the signature float.
