### ISSUE TITLE
snippet expanding error in `auto_insert` mode

### ISSUE THREAD

**Issue by kewuaa** [Saghen/blink.cmp#456]
### Make sure you have done the following

- [X] I have updated to the latest version of `blink.cmp`
- [X] I have read the README

### Bug Description

When snippet prefix longer than preview text, snippet expanding will cause error. There is an extra string at the end of the expanded snippet.

Such as the snippet below:

![shot](https://github.com/user-attachments/assets/73be1cc7-691b-42ef-b2ec-d7e2460fb6bb)

will cause error like:

https://github.com/user-attachments/assets/d7aa975a-63e2-4692-999c-a44ed28d2c23

`blink.cmp` will use preview text "for" as range to expand snippet, while `undo_preview` function will replace "for" with "foreach". As a result, extract text "each" will appear behind the snippet.

Simply making the following modifications seems to fix the error:

![shot2](https://github.com/user-attachments/assets/897f0891-4f86-48d4-a6e3-f45dd5341a89)

### Relevant configuration

```lua
providers = {
    ......
    snippets = {
        enabled = function(ctx)
            return ctx ~= nil
            and ctx.trigger.kind ~= vim.lsp.protocol.CompletionTriggerKind.TriggerCharacter
        end,
        opts = {
            friendly_snippets = false,
            search_paths = {
                vim.fn.stdpath('config') .. '/snippets',
            },
            global_snippets = { 'all' },
            extended_filetypes = {
                cython = {"python"},
                cpp = {"c"},
                cs = {"c"},
                javascript = {"c"}
            },
            ignored_filetypes = {},
            get_filetype = function(context)
                return vim.bo.filetype
            end
        }
    },
    ......
},
completion = {
    list = {
        max_items = 100,
        selection = "auto_insert",
    },
                                              
    accept = {
        -- experimental auto-brackets support
        auto_brackets = {
            enabled = true,
        },
    },
},
```

### neovim version

NVIM v0.11.0-dev-1276+gae93c7f369

### `blink.cmp` version: branch, tag, or commit

main

**Comment by tmerse** [comment]
I can confirm this issue

**Comment by Saghen** [comment]
Appears to be solved on `main`, not sure when, lmk if you're still able to reproduce and I'll re-open

**Comment by YaQia** [comment]
Well, I still encounter this problem. In my opinion, the auto_insert for snippets might be only the snippet's name rather than trying to insert the snippet's inner text.
