### ISSUE TITLE
Completion with list.selection = "auto_insert" doesn't work properly

### ISSUE THREAD

**Issue by Goose97** [Saghen/blink.cmp#460]
### Make sure you have done the following

- [X] I have updated to the latest version of `blink.cmp`
- [X] I have read the README

### Bug Description

When using the option `list.selection = "auto_insert"`, it sometimes replace the in correct range when cycle through options. 

Look at this video:

https://github.com/user-attachments/assets/2c396a87-be03-4b6e-861c-c1db2f3ee8f3

When I cycle to the second option, it incorrectly replaces the quote and the closing bracket, creates an invalid text.

After some digging, here's my findings:

1. AFAIK, the way we implement auto_insert is that: every time users select new option, we apply the edit to the buffer. If there's a previous edit, we undo it ([source](https://github.com/Saghen/blink.cmp/blob/main/lua/blink/cmp/completion/list.lua#L100-L101))

2. The undo is not complete as we only recover the text but not the cursor position. This leads to another "bug" (not sure if this counts): when users cancel the selection while selecting, the cursor stays at the end instead of jumping back to the original position

https://github.com/user-attachments/assets/1c9a25b5-d07c-4412-a509-0410eff1053b

3. We rely on the cursor position [here](https://github.com/Saghen/blink.cmp/blob/main/lua/blink/cmp/lib/text_edits.lua#L116-L116) to get the correct range to edit

I did play around with this a little bit and had a small patch: 
- We extend the [preview function](https://github.com/Saghen/blink.cmp/blob/main/lua/blink/cmp/completion/accept/preview.lua) to return both the undo_text_edit and the prev_cursor_position
- When we undo, also set the cursor position back

It seems to fix my bug. I'm unsure if there's other regressions. If ok, I'm happy to make a PR.

### Relevant configuration

```lua
opts = {
  keymap = {
    ["<C-p>"] = { "snippet_backward", "select_prev", "fallback" },
    ["<C-n>"] = { "snippet_forward", "select_next", "fallback" },
    ["<C-c>"] = { "cancel", "fallback" },
    ["<CR>"] = { "select_and_accept", "fallback" },
  },
  completion = {
    keyword = {
      range = "full",
    },
    list = {
      selection = "auto_insert",
    },
  },
  menu = {
    border = "single",
    winhighlight = "Normal:BlinkCmpMenu,CursorLine:BlinkCmpMenuSelection,Search:None",
  },
  sources = {
    completion = {
      enabled_providers = { "lsp", "path", "luasnip", "buffer" },
    },
  },
},
```

### neovim version

0.10.2

### `blink.cmp` version: branch, tag, or commit

main

**Comment by Saghen** [comment]
Thanks for looking into this! A PR would be great
