### ISSUE TITLE
When a function is used as an argument, brackets should not be auto-completed

### ISSUE THREAD

**Issue by jheroy** [Saghen/blink.cmp#463]
### Feature Description

```go
func A(f func()) {
    f()
}

func B() {
}

func main() {
    // | is the cursor
    A(B|) // Expected
    A(B(|)) // Current
}

```

**Comment by Goose97** [comment]
But that would break this case 🤔 

```
func A(f func()) {
    f()
}

func B(a int, b int) {
  return func() {
    a + b
  }
}

func main() {
    A(B())
}
```

In this case, we would want to invoke the B function to get the callback.

**Comment by Saghen** [comment]
We'd need the type definition to know whether to call the function or not. I think I prefer consistently adding brackets since you can train muscle memory for i.e. `<Tab> + <Backspace>`
