### ISSUE TITLE
`snippet_backward` does not jump to the previous position when the cursor is at the last placeholder

### ISSUE THREAD

**Issue by the-fuckin-nobody** [Saghen/blink.cmp#464]
### Make sure you have done the following

- [X] I have updated to the latest version of `blink.cmp`
- [X] I have read the README

### Bug Description

Lets just take a simple `function()` snippet

> Given that, I have mapped `<Tab>` and `<S-Tab>` to `snippet_backward` and `sniipet_forward` respectively.

The snippet expands as:
```lua
function [1]([2]) -- [1,2,3] are the positions, where the cursor would go, if `snippet_backward/snippet_forward` is called
    [3]
end
```

When I press `<Tab>` till the cursor reaches at `[3]` and after that, press `<S-Tab>`, the desired behaviour should be that cursor jumps to `[2]` and then to `[1]`, but that does not happen. tabs are inserted instead after `[3]`. 

This did not happen in the case of `nvim-cmp`  `luasnip.jump(1|-1)` worked perfectly fine there.

Don't know if that's the intended behaviour or not so labelling as bug nonetheless :-)

### Relevant configuration

```lua
local blink_cmp = require("blink.cmp")
	local luasnip = require("luasnip")
	blink_cmp.setup({
		keymap = {
			["<m-k>"] = { "select_prev", "fallback" },
			["<m-j>"] = { "select_next", "fallback" },
			["<Tab>"] = {
				-- function(cmp)
				-- 	if cmp.snippet_active() then
				-- 		return cmp.accept()
				-- 	else
				-- 		return cmp.select_and_accept()
				-- 	end
				-- end,
				"snippet_forward",
				"fallback",
			},
			["<CR>"] = { "select_and_accept", "fallback" },
			["<S-Tab>"] = { "snippet_backward", "fallback" },
			["<m-f>"] = { "scroll_documentation_down", "fallback" },
			["<m-b>"] = { "scroll_documentation_up", "fallback" },
			["<m-c>"] = { "show", "cancel", "fallback" },
		},
		blocked_filetypes = {},
		snippets = {
			expand = function(snippet)
				luasnip.lsp_expand(snippet)
			end,
			active = function(filter)
				if filter and filter.direction then
					return luasnip.expandable() or luasnip.jumpable(filter.direction)
				end
				return luasnip.in_snippet()
			end,
			jump = function(direction)
				if luasnip.locally_jumpable(direction) then
				    luasnip.jump(direction)
				end
			end,
		},
```

### neovim version

NVIM v0.11.0-dev-1300+g1077843b9b Build type: Release LuaJIT 2.1.1732813678     system vimrc file: "$VIM/sysinit.vim"   fall-back for $VIM: "/usr/share/nvim"  Run :checkhealth for more info

### `blink.cmp` version: branch, tag, or commit

latest git

**Comment by the-fuckin-nobody** [comment]
I actually changed it from `jumpable()` to `locally_jumpable()`  and it does not work on both the cases.
However similar config yields the desired behaviour in `nvim-cmp`

**Comment by the-fuckin-nobody** [comment]
Also,  thanks for adding `cmdline` support, can now fully migrate from `nvim-cmp` to `blink`

**Comment by Saghen** [comment]
> I actually changed it from jumpable() to locally_jumpable() and it does not work on both the cases.

Have you tried without it? Here's the default config

```lua
expand = function(snippet) require('luasnip').lsp_expand(snippet) end,
active = function(filter)
  if filter and filter.direction then
    return require('luasnip').jumpable(filter.direction)
  end
  return require('luasnip').in_snippet()
end,
jump = function(direction) require('luasnip').jump(direction) end,
```

> Also, thanks for adding cmdline support, can now fully migrate from nvim-cmp to blink

My pleasure :)

**Comment by Saghen** [comment]
Continuing in #517
