### ISSUE TITLE
`sources.snippets.extended_filetypes` snippet configuration not being used

### ISSUE THREAD

**Issue by Drew-Daniels** [Saghen/blink.cmp#472]
### Make sure you have done the following

- [X] I have updated to the latest version of `blink.cmp`
- [X] I have read the README

### Bug Description

I recently upgraded to the latest version of `blink.cmp` and modified my config to the latest schema, but am noticing that setting `sources.snippets.extended_filetypes` seems to do nothing, and I do not see my `javascript` snippets loaded in `typescript` buffers, for example.

When I log `files` from this line I can see all of my custom snippets are loaded as search paths:

https://github.com/Saghen/blink.cmp/blob/765ee4cfb6d71e9d88a27f64f406251f3aa85fac/lua/blink/cmp/sources/snippets/scan.lua#L8

![Pasted Graphic](https://github.com/user-attachments/assets/4abdae28-5dd7-4337-a98d-db15332a1baa)

But when I log the configuration and default configuration here, I can see that my snippets config is `{}`, and while the default snippets config is as expected:

https://github.com/Saghen/blink.cmp/blob/765ee4cfb6d71e9d88a27f64f406251f3aa85fac/lua/blink/cmp/sources/snippets/registry.lua#L26

![Pasted Graphic](https://github.com/user-attachments/assets/1d5367c7-8859-434c-aa36-70472117164a)

Ex. of custom `TODO` snippet being loaded in a `javascript` file

![image](https://github.com/user-attachments/assets/417fdb56-09f1-40ab-b0cf-ec7b2d8aa9c0)

Ex. of this same `TODO` snippet _not_ being loaded in `typescript` file:

![image](https://github.com/user-attachments/assets/d6a1c8c8-89b5-458c-9b3e-61c4f85fac6d)

Here is my `nvim/snippets/package.json`:

```json
{
  "name": "my-snippets",
  "contributes": {
    "snippets": [
      {
        "language": "all",
        "path": "./all.json"
      },
      {
        "language": "lua",
        "path": "./lua.json"
      },
      {
        "language": "sh",
        "path": "./sh.json"
      },
      {
        "language": "yaml",
        "path": "./yaml.json"
      },
      {
        "language": "css",
        "path": "./css.json"
      },
      {
        "language": "ruby",
        "path": "./ruby.json"
      },
      {
        "language": "json",
        "path": "./json.json"
      },
      {
        "language": "fish",
        "path": "./fish.json"
      },
      {
        "language": "norg",
        "path": "./norg.json"
      },
      {
        "language": "javascript",
        "path": "./javascript.json"
      },
      {
        "language": "html",
        "path": "./html.json"
      },
      {
        "language": "toml",
        "path": "./toml.json"
      },
      {
        "language": "zsh",
        "path": "./zsh.json"
      }
    ]
  }
}
```

And my `nvim/snippets/javascript.json` file for example:

```json
{
  "TODO": {
    "body": "// TODO: ${0}",
    "prefix": "td"
  },
  "Debug Log": {
    "body": "console.log(\"${1}: \", ${0})",
    "prefix": "dl"
  },
  "Debugger": {
    "body": "debugger;",
    "prefix": "db"
  },
  "ESLint Disable": {
    "body": "/* eslint-disable */",
    "prefix": "ed"
  },
  "ESLint Ignore": {
    "body": "/* eslint-ignore ${0} */",
    "prefix": "ei"
  }
}
```

### Relevant configuration

```lua
require("blink-cmp").setup({
  keymap = {
    ["<C-u>"] = { "scroll_documentation_up" },
    ["<C-d>"] = { "scroll_documentation_down" },
    ["<C-n>"] = { "select_next" },
    ["<C-p>"] = { "select_prev" },
    ["<C-e>"] = { "accept" },
    ["<C-space>"] = { "show" },
    ["<C-q>"] = { "hide" },
    ["<C-k>"] = { "show_documentation" },
    ["<C-j>"] = { "snippet_forward" },
    ["<C-h>"] = { "snippet_backward" },
  },
  nerd_font_variant = "mono",
  highlight = {
    use_nvim_cmp_as_default = true,
  },
  windows = {
    documentation = {
      auto_show = true,
    },
  },
  sources = {
    completion = {
      enabled_providers = { "lsp", "path", "snippets", "buffer", "lazydev" },
    },
    providers = {
      lsp = { fallback_for = { "lazydev" } },
      lazydev = { name = "LazyDev", module = "lazydev.integrations.blink" },
    },
    snippets = {
      name = "Snippets",
      module = "blink.cmp.sources.snippets",
      score_offset = -3,
      opts = {
        friendly_snippets = true,
        search_paths = { vim.fn.stdpath("config") .. "/snippets" },
        global_snippets = { "all" },
        extended_filetypes = {
          eruby = { "ruby", "javascript" },
          typescript = { "javascript" },
          vue = { "javascript", "html", "css" },
        },
        ignored_filetypes = {},
        get_filetype = function(_)
          return vim.bo.filetype
        end,
      },
    },
  },
})
```

### neovim version

NVIM v0.11.0-dev-1301+ge8e3b443f8-Homebrew Build type: Release LuaJIT 2.1.1732813678 Run "nvim -V1 -v" for more info

### `blink.cmp` version: branch, tag, or commit

v0.7.3

**Comment by Saghen** [comment]
Looks like you placed the snippets configuration at `sources.snippets` instead of `sources.providers.snippets`

**Comment by Drew-Daniels** [comment]
Doh, that makes sense. Thanks for the help.
