### ISSUE TITLE
Allow adding providers add-hoc after blink.cmp has been setup

### ISSUE THREAD

**Issue by abeldekat** [Saghen/blink.cmp#475]
### Feature Description

Thanks for the plugin!

My [config](https://github.com/abeldekat/nvim_pde/blob/09c46381504492db475ad1b9f36ca7e69ac6572b/lua/ak/mini_deps.lua#L1) uses `mini.deps` and has support for `sql`, using `vim-dadbod-completion`.

However, I don't need it that often. As such, I only load `sql` plugins on a [key](https://github.com/abeldekat/nvim_pde/blob/09c46381504492db475ad1b9f36ca7e69ac6572b/lua/ak/deps/lang/extra.lua#L49) command that is available when the filetype of the buffer is `sql`.

Using [nvim-cmp](https://github.com/abeldekat/nvim_pde/blob/09c46381504492db475ad1b9f36ca7e69ac6572b/lua/ak/config/lang/sql/dadbod.lua#L37), I could add a new source dynamically:
```lua
local has_nvim_cmp, cmp = pcall(require, "cmp")
if has_nvim_cmp then cmp.setup.buffer({ sources = { { name = "vim-dadbod-completion" } } }) 
```

I did not discover such an option in `blink.cmp`, but it is [possible](https://github.com/abeldekat/nvim_pde/blob/09c46381504492db475ad1b9f36ca7e69ac6572b/lua/ak/config/lang/sql/dadbod.lua#L15):
```lua
    --
    -- HACK: There is no public method to add a provider once blink has been setup:
    --
    local new_provider_in_config = { name = "Dadbod", module = "vim_dadbod_completion.blink" }
    local new_provider_id = "dadbod"

    local config = require("blink.cmp.config")
    -- Add to config, otherwise internal checks fail:
    -- HACK: With this hack, do not configure enabled_providers as function in blink setup!
    ---@diagnostic disable-next-line: param-type-mismatch -- enabled_providers, function or string...
    table.insert(config.sources.completion.enabled_providers, new_provider_id)
    -- HACK: Adding to config directly bypasses validation for new_provider_in_config!
    config.sources.providers[new_provider_id] = new_provider_in_config
    -- Add to internal providers:
    local sources = require("blink.cmp.sources.lib")
    local provider = require("blink.cmp.sources.lib.provider")
    -- Line taken from blink.cmp.sources.lib.init, get_enabled_providers:
    -- ...initialize the provider if it hasn't been initialized yet...
    sources.providers[new_provider_id] = provider.new(new_provider_id, new_provider_in_config)

    -- Now the public function can be used. Only dadbod will be relaoded
    require("blink-cmp").reload(new_provider_id)
```

The difference in loading between `nvim-cmp` and `blink.cmp` is currently also observable in the `sql` extra in [LazyVim](https://github.com/LazyVim/LazyVim/blob/71ea193cf6ee9e8021be2e8c7f277f757779c1ac/lua/lazyvim/plugins/extras/lang/sql.lua#L31). Without the `blink.cmp` extra, `vim-dadbod-completion` is only added when the type of the buffer is `sql`. When the `blink.cmp` extra is activated, `vim-dadbod-completion` is always added when `blink.cmp` activates.

Would you be willing to add a public function to `blink.cmp` that registers and activates a new provider? If so, I would gladly submit a PR. I think the code above would be of use in the implementation.

Related:

- [Allow providers to disable themselves](https://github.com/Saghen/blink.cmp/issues/208 )
- [PR Sources v2](https://github.com/Saghen/blink.cmp/pull/465)

**Comment by Saghen** [comment]
Yeah, makes sense, I'll add it as part of sources v2

**Comment by abeldekat** [comment]
Thanks!

**Comment by Saghen** [comment]
You should be able to use `require('blink.cmp').add_provider(id, config)` to add providers at runtime now. There's also a new `sources.per_filetype` that could be useful for enabling just `dadbod` in `sql`. Lmk if you run into any issues

**Comment by abeldekat** [comment]
Thanks!
