### ISSUE TITLE
Allow configuring maximum length of buffer completions

### ISSUE THREAD

**Issue by kik4444** [Saghen/blink.cmp#478]
Hello, I am trying blink for the first time from LazyVim. This is the configuration I'm using with LazyVim at the time of writing: https://github.com/LazyVim/LazyVim/blob/v13.8.0/lua/lazyvim/plugins/extras/coding/blink.lua

However, I noticed that there seems to be a limit on the completion length of buffer items. For example, if I open a new empty file, write a long word on the first line, then attempt to autocomplete it on the second line, I get this:
```
Thisisalongwordthatwearetryingtoreach
Thisisalongwordthatwearetryingtor
```
The first line is manually written. The second was autocompleted by blink. It got cut off at the 33rd character.

This happens in other files too that have multiple completion sources. But it only happens with the `buffer` completion. If I have a long function name, then the LSP completion is full and not cut off.

I didn't find any settings for buffer length completions. Can you please make this configurable?

_Originally posted by @kik4444 in https://github.com/Saghen/blink.cmp/discussions/474_

**Comment by joshzcold** [comment]
Would like this as well. Some infrastructure as code work flows involve a lot of long buffer completions 👍

**Comment by Saghen** [comment]
Rather than making it configurable, I've increased it to 512 characters which should work for the large majority of cases I think
