### ISSUE TITLE
curl: (35) schannel: next InitializeSecurityContext failed: CRYPT_E_NO_REVOCATION_CHECK

### ISSUE THREAD

**Issue by adelarsq** [Saghen/blink.cmp#481]
### Make sure you have done the following

- [X] I have updated to the latest version of `blink.cmp`
- [X] I have read the README

### Bug Description

On Windows I got this error after the latest update:

![image](https://github.com/user-attachments/assets/6687c5b2-fcab-4fce-baf6-9f5ea16f6a85)

### neovim version

NVIM v0.11.0-dev-1325+g30726c778c

### `blink.cmp` version: branch, tag, or commit

v0.7.4

**Comment by Saghen** [comment]
That's bizarre, it's saying that the Github certificate has expired. It seems likely this is a transient issue on Github's side, are you still running into it?

**Comment by adelarsq** [comment]
@Saghen Nice! Thanks for the change. Just waiting for the next release so I can test this.
