### ISSUE TITLE
Option to remove "Text" as autocomplete source

### ISSUE THREAD

**Issue by uthmanmoh** [Saghen/blink.cmp#484]
### Feature Description

I'd like the functionality that `nvim-cmp` provides documented here: https://github.com/hrsh7th/nvim-cmp/blob/main/doc/cmp.txt#L659-L679.

Essentially I find it annoying to get "Text" sources for autocomplete and would like a way to disable that because in my opinion it is useless

<img width="984" alt="image" src="https://github.com/user-attachments/assets/cd148ce7-8c38-4281-9d5e-daf599424de0">

**Comment by Shougo** [comment]
You can disable `buffer` provider from `enabled_providers` config.

**Comment by Saghen** [comment]
You beat me to it :) It's worth noting, occasionally LSPs will return "Text" items. You could add a `transform_items` on the `LSP` source and filter them out there but you likely won't need that

**Comment by uthmanmoh** [comment]
That's what I thought too, I removed `"buffer"` and it still shows the same "Text" items. Here's my config:

```lua
return {
  {
    "saghen/blink.cmp",
    opts = {
      completion = {
        keyword = {
          range = 'full',
        },
        menu = {
          border = 'rounded',
          draw = {
            -- Show the type of the autocomplete
            columns = { { "label", "label_description", gap = 1 }, { "kind_icon", "kind" } },
          },
        },
        documentation = {
          window = {
            border = 'rounded',
          }
        },
        ghost_text = {
          -- Disable the preview text for each autocomplete option
          enabled = false,
        }
      },
      sources = {
        completion = {
          enabled_providers = { "lsp", "path", "snippets" },
        },
        providers = {
          snippets = {
            opts = {
              -- Disable the "all" snippets which gives useless stuff like the 'date' snippet
              global_snippets = {},
            }
          }
        },
      },
    }
  },
}
```

Still getting the same results:
<img width="931" alt="image" src="https://github.com/user-attachments/assets/a8f4c814-b98a-4162-a499-5436f67f493f">

**Comment by uthmanmoh** [comment]
For anyone curious in the future, I fixed this by adding a `transforms_items` for lsp as below:
```lua
      sources = {
        providers = {
          lsp = {
            transform_items = function (ctx, items)
              -- Remove the "Text" source from lsp autocomplete
              return vim.tbl_filter(function(item)
                return item.kind ~= vim.lsp.protocol.CompletionItemKind.Text
              end, items)
            end
          },
        },
      },
```

Honestly not really sure what the "buffer" source does. Haven't seen any differences in adding/removing it

**Comment by Saghen** [comment]
You can also do this for all sources by doing the transform_items at the top level

```lua
sources = {
  transform_items = function (ctx, items)
    -- Remove the "Text" source from lsp autocomplete
    return vim.tbl_filter(function(item)
      return item.kind ~= vim.lsp.protocol.CompletionItemKind.Text
    end, items)
  end
},

**Comment by xandris** [comment]
@uthmanmoh you already fixed it but I think this was the intended way to disable it? idk.

```lua
  {
    'saghen/blink.cmp',
    opts = {
      sources = {
        providers = {
          buffer = { enabled = false },
        },
      },
    },
  },
```
