### ISSUE TITLE
Curl likely does not overwrite

### ISSUE THREAD

**Issue by z3z1ma** [Saghen/blink.cmp#488]
https://github.com/Saghen/blink.cmp/blob/68ba8aeb8637b72205c8954ba6d08a37585acf76/lua/blink/cmp/fuzzy/download.lua#L130-L138

I am fairly certain that `curl` requires the `--clobber` option explicitly passed to be able to overwrite a file if it exists. 

Noting this here in case the issue of updating `blink` resulting in neovim crashing due to the file download failing is hitting this codepath. Such as in:

https://github.com/Saghen/blink.cmp/issues/115
https://github.com/Saghen/blink.cmp/issues/68

**Comment by Saghen** [comment]
It looks like `curl 8.11.0` will overwrite without asking for permission, tested with `curl --output test https://example.com`. If curl was failing, it should get caught by the `.code ~= 0` check
