### ISSUE TITLE
Disable auto completion on specific file types

### ISSUE THREAD

**Issue by nounder** [Saghen/blink.cmp#491]
### Feature Description

Ability to provide file types where auto completion will not be turned on.

This would be useful for writing prose, in Markdown or plain text files.

**Comment by Saghen** [comment]
You can use the `enabled` function to do this. There's an example in the default configuration section of the README

```lua
enabled = function()
  return not vim.tbl_contains({ "lua", "markdown" }, vim.bo.filetype) and vim.bo.buftype ~= "prompt"
end
```

**Comment by nounder** [comment]
Oh, that's great. Thank you!
