### ISSUE TITLE
Wrong completions in `lua-ls` annotations

### ISSUE THREAD

**Issue by kawre** [Saghen/blink.cmp#500]
### Make sure you have done the following

- [X] I have updated to the latest version of `blink.cmp`
- [X] I have read the README

### Bug Description

https://github.com/user-attachments/assets/b0ced911-7d91-4e4a-ab1a-2495cc78fb80

### neovim version

NVIM v0.11.0-dev-1287+g8f84167c30

### `blink.cmp` version: branch, tag, or commit

fe568eb568c178127ecc5eccbb2226dde6b41282

**Comment by Saghen** [comment]
The LSP is returning a text edit that doesn't include the last character, seems like a bug in `lua_ls`

**Comment by Saghen** [comment]
Would appreciate it if someone reported this upstream, seems like many people run into it
