### ISSUE TITLE
Too much padding in documentation window

### ISSUE THREAD

**Issue by euanlacy** [Saghen/blink.cmp#511]
### Make sure you have done the following

- [X] I have updated to the latest version of `blink.cmp`
- [X] I have read the README

### Bug Description

Markdown code tags display as blank lines in documentation window, which needlessly adds padding to the documentation, making it harder and more annoying to read. Perhaps it would be nice to add an option (enabled by default?) to skip rendering markdown code tags?

![image](https://github.com/user-attachments/assets/45b14edb-92ab-4122-9fad-dce8d099caa8)

### Relevant configuration

```lua
windows = {
  documentation = { auto_show = true },
}
```

### neovim version

NVIM v0.10.2 Build type: RelWithDebInfo LuaJIT 2.1.1720049189

### `blink.cmp` version: branch, tag, or commit

v0.7.6

**Comment by Saghen** [comment]
This looks like `K` menu which isn't managed by blink.cmp. We handle this for the `detail` (first section before separator) of the documentation of the window but not for the rest of it, although that should generally not be an issue. Neovim is working on a feature to support this case if you're interested in following: https://github.com/neovim/neovim/issues/25718
