### ISSUE TITLE
Add separate keymap settings for `cmdline` completions.

### ISSUE THREAD

**Issue by the-fuckin-nobody** [Saghen/blink.cmp#514]
### Feature Description

Since the addition of `cmdline` completions, it would be really nice to have separate keymap settings for `cmdline` completions as they may clash with keymaps for normal completions.

**Comment by stefanboca** [comment]
If/when this is implemented, it would be nice if `<Up>` and `<Down>` are left unmapped for cmdline by default, because those keys are used for history. More generally, it might be nice to have cmdline-specific overrides, at least for some settings. For instance I use `completion.menu.direction_priority = { "n", "s" }` but for my cmdline (noice popup) I'd always like the menu to be below.

**Comment by the-fuckin-nobody** [comment]
> If/when this is implemented, it would be nice if <Up> and <Down> are left unmapped for cmdline by default, because those keys are used for history.

yeah this would be nice too

**Comment by Saghen** [comment]
> For instance I use completion.menu.direction_priority = { "n", "s" } but for my cmdline (noice popup) I'd always like the menu to be below.

@stefanboca Is this because the menu starts below but eventually goes above when there's not many options? I'm thinking the solution could be to always pick the direction that can fit the maximum height

**Comment by stefanboca** [comment]
Yes, or when I manually trigger and there's less options than however many lines fit above.

> I'm thinking the solution could be to always pick the direction that can fit the maximum height

That should solve it. I also noticed in `completion.windows.menu` there's a `TODO: Don't switch directions if the context is the same` which might be related.

**Comment by Saghen** [comment]
Yeah, although that solution is wrong. We should pick the direction that can fit the max_height, falling back to the largest direction if none of them can fit the max_height
