### ISSUE TITLE
LuaSnip: some keys are blocked

### ISSUE THREAD

**Issue by vdegenne** [Saghen/blink.cmp#517]
### Make sure you have done the following

- [X] I have updated to the latest version of `blink.cmp`
- [X] I have read the README

### Bug Description

When entering a luasnip snippet, it is not possible to use Tab, or even type some letters (e.g. capital H), traveling is also a little bit broken. Here some examples:

Here, pressing Tab won't make the caret go to next placeholder, unless some characters are typed prior to pressing tab. Traveling using Tab and S-Tab will eventually stop having any effect:

https://github.com/user-attachments/assets/8bc4af10-9b73-472c-9e95-1098fc819ee3

In the following, we can see that snippets are having two versions of themselves (`if~` in this example), the two of which don't work.   
One appears to be the raw vscode snippet loaded from friendly-snippet which fails to enter selection mode when the snippet is selected (also Tab won't work).  
The other one appears to be processed from the version above, it seems to work better because at least it does enter select mode when it is selected, but of course Tab and other keys will fail:

https://github.com/user-attachments/assets/7b4a7f6b-046f-493c-b317-b7a8231e8a6a

### neovim version

NVIM v0.10.2

### `blink.cmp` version: branch, tag, or commit

0.7.6

**Comment by Parsifa1** [comment]
> Here, pressing Tab won't make the caret go to next placeholder, unless some characters are typed prior to pressing tab. Traveling using Tab and S-Tab will eventually stop having any effect:

i have the same issue

**Comment by vdegenne** [comment]
@Parsifa1 Was it working before? (I'm new to blink)

**Comment by Parsifa1** [comment]
Basically usable, but there are some minor issues(if dont input sth, you can't jump through `<Tab>` :(

**Comment by Saghen** [comment]
I'm not able to reproduce it on my config for some reason. The code for `snippet_forward`/`snippet_backward` is:

```lua
function cmp.snippet_forward()
  local snippets = require('blink.cmp.config').snippets
  if not snippets.active({ direction = 1 }) then return end
  vim.schedule(function() snippets.jump(1) end)
  return true
end

function cmp.snippet_backward()
  local snippets = require('blink.cmp.config').snippets
  if not snippets.active({ direction = -1 }) then return end
  vim.schedule(function() snippets.jump(-1) end)
  return true
end
```

It seems like your `snippets.active` is returning false but I'm not entirely sure why

**Comment by Parsifa1** [comment]
this is my snippet config:
```lua
        snippets = {
            expand = function(snippet)
                require("luasnip").lsp_expand(snippet)
            end,
            active = function(filter)
                if filter and filter.direction then
                    return require("luasnip").locally_jumpable()
                end
                return require("luasnip").in_snippet()
            end,
            jump = function(direction)
                require("luasnip").jump(direction)
            end,
        },

```

**Comment by Parsifa1** [comment]
oh, i first tested the default :)

**Comment by Saghen** [comment]
That's bizarre, can you confirm you're on v2.3.0 of LuaSnip?

**Comment by Parsifa1** [comment]
> That's bizarre, can you confirm you're on v2.3.0 of LuaSnip?

```
branch main
commit 1eda2b9
```

**Comment by vdegenne** [comment]
@Saghen I should have mentioned, I'm on LazyVim, so could there be something wrong in the intricacies of how it's being configured. Afaik It's using blink-compat. and master branch of LuaSnip

**Comment by Saghen** [comment]
I've confirmed it's working on v2.3 of LuaSnip but not on latest. It seems like it might be a bug on their end since the `jumpable` returns false for -1 when reaching the final placeholder. I'd recommend using the last tagged version

**Comment by vdegenne** [comment]
@Saghen I'm waiting for an update in LazyVim to be able to use main branch of blink but though downgrading LuaSnip to 2.3.0 have made things work a little better it haven't really completely fixed the Tab issue here. For instance, pressing Tab to accept a default value (from a multichoice placeholder) won't go to the next placeholder.
