### ISSUE TITLE
feature: disable trigger on type for certain filetypes

### ISSUE THREAD

**Issue by davidosomething** [Saghen/blink.cmp#52]
for certain filetypes i only want a completion PUM to appear if i manually `<C-Space>`

the use case is that i use coc.nvim for typescript (it is much faster and less likely to lock up neovim than built-in lsp client based ones), and it has its own PUM implementation

in nvim-cmp i was able to do this using
```lua
        cmp.setup.filetype({ 'typescript', 'typescriptreact' }, {
          completion = {
            -- Use <C-Space> to trigger nvim-cmp.
            -- E.g. for tailwindcss completion from nvim-cmp but regular
            -- completion from coc.nvim
            autocomplete = false,
          },
        })
```

**Comment by neochrome** [comment]
It would actually be nice to be able to switch off the autocomplete entirely and only trigger it manually, perhaps using a filetype of `*` or something.
