### ISSUE TITLE
`auto_insert` should probably be disabled for cmdline and search completion

### ISSUE THREAD

**Issue by djdv** [Saghen/blink.cmp#523]
### Make sure you have done the following

- [X] I have updated to the latest version of `blink.cmp`
- [X] I have read the README

### Bug Description

It seems like cycling the menu at all with `auto_insert` enabled, will cause chaos; entering each menu item as a command - as you cycle them.

In this video, I type `:O` and cycle with `<Tab>` once, then exit with `<Esc>`.
`:Oil` is invoked without me accepting the suggestions.
https://github.com/user-attachments/assets/4e14de9d-6391-4a22-a606-ea79cccb5320

I'd like to leave `auto_insert` and the cmdline completion both enabled, but this causes conflict with the cmdline.

### Relevant configuration

```lua
completion = { list = { selection = 'auto_insert' }}
keymap = {
	['<Tab>'] = { 'select_next', 'snippet_forward', 'fallback' },
	['<Esc>'] = {
		function(cmp)
			if not cmp.snippet_active() then
				return cmp.cancel()
			end
		end,
		'fallback'
	}
}
```

### neovim version

NVIM v0.11.0-dev-1345+g98027b8a71 Build type: Release LuaJIT 2.1.1732813678

### `blink.cmp` version: branch, tag, or commit

1eda2b9

**Comment by Saghen** [comment]
You weren't kidding about the chaos :D The latest commit is quite hacky for now, but seems to work well on my system. Lmk how it looks on your end!

**Comment by djdv** [comment]
Thanks :^]
The workaround seems fine for my config.
Using `manual` or `auto_insert` seem okay after the commit, but `selection = 'preselect'` seems to still have the issue.

---

As an aside, cycling through the cmdline suggestions has a significant delay for me.
This was the case prior to the patch as well (when using `manual` selection).
Suggestions in the buffer from sources like the LSP, etc. are no problem (fast).
I'm not sure the source of that issue though.

**Comment by djdv** [comment]
>cycling through the cmdline suggestions has a significant delay for me.

Some commit between [1eda2b9...f9b72e3](https://github.com/Saghen/blink.cmp/compare/1eda2b989213b54a66589b44236bfcb427c9a5fe...f9b72e3c1a1b61984b9128fb3e024fdf8a3d07fa) in blink, or some commit in neovim between `17383870dd...f9dd682621` seems to have fixed this for me. 🥳

**Comment by Saghen** [comment]
Sounds good!
