### ISSUE TITLE
keymap preset and cmdline completions

### ISSUE THREAD

**Issue by folke** [Saghen/blink.cmp#530]
### Feature Description

I really like the new cmdline completions, but they don't really work well with the `enter` preset.
I still like the `enter` preset, but for the cmdline these keymaps don't make sense.

Would be great to be able to set a different keymap preset for the cmdline.

As a simple example, if I want to do a quick `:e<CR>` then with the `enter` preset you're left in the cmdline with `:else`.
Same with searching. Enter preset also doesn't make sense there

**Comment by the-fuckin-nobody** [comment]
Implementing #514 would solve this too

**Comment by Saghen** [comment]
Duplicate of #514
