### ISSUE TITLE
How to install via Mini.Deps?

### ISSUE THREAD

**Issue by swahpy** [Saghen/blink.cmp#54]
Hi, is there a way to isntall the plugin via mini.deps? Thank you for any hints.

**Comment by swahpy** [comment]
```lua
add({
  source = "saghen/blink.cmp",
  depends = {
	  "rafamadriz/friendly-snippets",
  },
  checkout = "main",
  hooks = { post_checkout = function() vim.cmd('cargo build --release') end },
})
```

I tried above solution, but ended with below errors:
> 15:18:37 │ Error while downloading blink.cmp pre-built binary: Can't download from github due to not being on a git tag and no native_download.version set, but found no built version of the library. Either run `cargo build --release\` via your package manager, switch to a git tag, or set `native_download.version` in config. See the README for more info.

**Comment by lithammer** [comment]
Try something like this. Some notes:

- `vim.system()` wants `[]string`, not `string`.
- Set the correct `cwd` for `vim.system()`. Otherwise it will try to run in editor's `cwd` rather than the plugin directory.
- Disable downloading of prebuilt binaries.

```lua
add({
  source = 'Saghen/blink.cmp',
  hooks = {
    post_checkout = function(path)
      vim.system({ 'cargo', 'build', '--release' }, {
        cwd = path,
        on_exit = function(obj)
          if obj.code == 0 then
            vim.notify('blink.cmp compilation done', vim.log.levels.INFO)
          else
            vim.notify('blink.cmp compilation failed', vim.log.levels.ERROR)
          end
        end,
      })
    end,
  },
})
```

```lua
local later = MiniDeps.later

later(function()
  require('blink-cmp').setup({
    fuzzy = {
      prebuiltBinaries = {
        download = false, -- Always compile since we track 'main'
      },
    },
  })
end)
```

**Comment by lithammer** [comment]
Something like this with some extra bells and whistles:

```lua
local function build_blink(params)
  vim.notify('Building blink.cmp', vim.log.levels.INFO)
  local obj = vim.system({ 'cargo', 'build', '--release' }, { cwd = params.path }):wait()
  if obj.code == 0 then
    vim.notify('Building blink.cmp done', vim.log.levels.INFO)
  else
    vim.notify('Building blink.cmp failed', vim.log.levels.ERROR)
  end
end

add({
  source = 'Saghen/blink.cmp',
  hooks = {
    post_install = build_blink,
    post_checkout = build_blink,
  },
})
```

**Comment by swahpy** [comment]
Hi @lithammer, thank you so much for your quick answer. I just tried it out via downloading the pre-built binary and placed it in the right place. But when I using the plugin, I found the cursor would be at the end of the snippet, instead of the first position(like the func name) that needs to set. And the `Tab` key didn't walk though the parameters as well.(Not sure if it is due to my config issue.
So for the time being, I just stick to nvim-cmp and not switch. Thank you again.

**Comment by bockel** [comment]
You can also use the pre-built binary with mini.deps. You just need to pass the same version to both the `mini.deps.add(checkout)` and `blink.setup(fuzzy.prebuiltBinaries.forceVersion)`. You could also risk setting the tag to *latest* but risk the lua plugin and rust FFI getting out of sync.

```lua
local BLINKVER = 'v0.2.1'
MiniDeps.add({ ---@diagnostic disable-line:undefined-global
  source = 'Saghen/blink.cmp',
  checkout = BLINKVER,
})
require('blink.cmp').setup({
  fuzzy = {
    prebuiltBinaries = {
      download = true,
      forceVersion = BLINKVER,
    }
  }
}
```

**Comment by swahpy** [comment]
Hi all, 

Update: To install the plugin using `mini.deps` is quite straightforward. Just as below,
```lua
add({
  source = "saghen/blink.cmp",
  depends = {
	  "rafamadriz/friendly-snippets",
  },
  checkout = "v0.2.1",
})
```

The failure I met not long ago was because the network issue. 

Maybe an off-topic issue, I didn't figure out how to jump between the parameters need to change in a snippet? Someone meet the same issue and any hints? Thank you.
