### ISSUE TITLE
LSP source can slow other sources

### ISSUE THREAD

**Issue by ribru17** [Saghen/blink.cmp#540]
### Make sure you have done the following

- [X] I have updated to the latest version of `blink.cmp`
- [X] I have read the README

### Bug Description

I have created a [spell source for blink](https://github.com/ribru17/blink-cmp-spell) and while debugging it I noticed that the `marksman` LSP was slowing my completion results. When disabling the LSP source (or just running `LspStop`) there is a noticeable improvement

[Screencast_20241213_103930.webm](https://github.com/user-attachments/assets/d9e87919-10af-4d96-b993-89c6da98b835)

PS thanks for the awesome plugin :)

### Relevant configuration

```lua
sources = {
        default = { 'lsp', 'path', 'luasnip', 'spell' },
        providers = {
          spell = {
            name = 'Spell',
            module = 'blink-cmp-spell',
          },
        },
      },
```

### neovim version

NVIM v0.11.0-dev Build type: Release LuaJIT 2.1.1713773202

### `blink.cmp` version: branch, tag, or commit

2c826d9

**Comment by Saghen** [comment]
You could mark your LSP source as `async` so it doesn't block, perhaps conditionally

```
sources.providers.lsp.async = function()
  local clients = vim.lsp.get_clients({ bufnr = 0 })
  for _, client in ipairs(clients) do
    if client.name == 'marksman' then return true
  end
  return false
```

**Comment by ribru17** [comment]
Wonderful, that solves it. Thank you!
