### ISSUE TITLE
Slow LSP providers (again) and the async solution

### ISSUE THREAD

**Issue by soifou** [Saghen/blink.cmp#543]
### Make sure you have done the following

- [X] I have updated to the latest version of `blink.cmp`
- [X] I have read the README

### Bug Description

First sorry to open another issue but since the PR #465, I also notice in some cases a delay when showing the completion list, similar to #539 and #540. 

Below, I toggle the window inside a lua file, the completion seem instant. 
But when I am in a (luasnip) snippet, there is always a lag.

https://github.com/user-attachments/assets/84082272-fd8c-4708-b0c7-a1ae6e9da903

I don't get any rational behind this and before the PR was merged I had no issue of this kind so I suspect an underlying issue (or a misunderstanding from my side). 

So because of a slow `lua_ls` in a snippet or a `markman` that take ages to respond, I ended up to set `providers.lsp.async = true`, problem gone... But that feels like a hack to me.

Thoughts?

### neovim version

v0.11.0-dev+g668d2569b4

### `blink.cmp` version: branch, tag, or commit

main

**Comment by Saghen** [comment]
Thanks, I think I found the root cause to be the LSP client not running the callback when the response was nil. Does that fix the issue on your end?

**Comment by soifou** [comment]
A big YES, congrats :+1:
