### ISSUE TITLE
cmdline fallback for `<Esc>` sometimes invokes the command

### ISSUE THREAD

**Issue by djdv** [Saghen/blink.cmp#547]
### Make sure you have done the following

- [X] I have updated to the latest version of `blink.cmp`
- [X] I have read the README

### Bug Description

When I define
```lua
keymap = { cmdline = { ['<Esc>'] = { 'cancel', 'fallback' } } }
```
typing `:q`  followed by `<Esc><Esc>` will invoke `:q` for some reason.
When 'fallback' isn't used, this doesn't seem to happen but then you can't exit the command-line with Esc.

More detail: https://youtu.be/DBc5DhH0moA

### Relevant configuration

```lua
keymap = { cmdline = { ['<Esc>'] = { 'cancel', 'fallback' } } }
```

### neovim version

NVIM v0.11.0-dev-1351+gf9dd682621 Build type: Release LuaJIT 2.1.1732813678

### `blink.cmp` version: branch, tag, or commit

97989c8

**Comment by Saghen** [comment]
More context: https://github.com/neovim/neovim/issues/21585

Seems like no one knows why it works this way

**Comment by djdv** [comment]
Thanks for the info. That describes exactly what's going on here.

>Generally speaking, Neovim behaves as if `<Esc>` was mapped to `<CR>`, making it very difficult, if not impossible, to have a useful command mode mapping for the escape key (e.g. a conditional mapping such as: close the completion window if it is visible, otherwise abort the cmdline with `<Esc>` as if it had never been mapped in the first place).

(The command and/or key combinations I prefer tend to be haunted for one legacy reason or another 😆)

**Comment by Saghen** [comment]
Closing since it seems like there's nothing to do on our side

**Comment by ad-on-is** [comment]
With a little bit of help from my friend Claude, I was able to solve that.

```lua

 ["<esc>"] = {
            "cancel",
            function()
              if vim.fn.getcmdtype() ~= "" then
                vim.api.nvim_feedkeys(vim.api.nvim_replace_termcodes("<C-c>", true, true, true), "n", true)
                return
              end
            end,
          },


```

**Comment by a-usr** [comment]
slightly better solution that doesnt require a template:
```lua
keymap = {
  cmdline = {
    ["<ESC>"] = {
      function(cmp)
        if cmp.is_visible() then
          cmp.cancel()
        else
          vim.api.nvim_feedkeys(vim.api.nvim_replace_termcodes("<C-c>", true, true, true), "n", true)
        end
      end,
    },
  },
}
```

**Comment by qiine** [comment]
> slightly better solution that doesnt require a template:
> 
> keymap = {
>   cmdline = {
>     ["<ESC>"] = {
>       function(cmp)
>         if cmp.is_visible() then
>           cmp.cancel()
>         else
>           vim.api.nvim_feedkeys(vim.api.nvim_replace_termcodes("<C-c>", true, true, true), "n", true)
>         end
>       end,
>     },
>   },
> }

Just wanted to say thanks you so much !
I thought I was getting crazy

**Comment by jchenatcpacket** [comment]
> ["<ESC>"] = {
>       function(cmp)
>         if cmp.is_visible() then
>           cmp.cancel()
>         else
>           vim.api.nvim_feedkeys(vim.api.nvim_replace_termcodes("<C-c>", true, true, true), "n", true)
>         end
>       end,
>     },

this should be added to the blink doc
