### ISSUE TITLE
Feeding in a character / set of characters after completion is done

### ISSUE THREAD

**Issue by balpert89** [Saghen/blink.cmp#548]
### Feature Description

Hi,

thanks for this awesome work.

My use case is the following: when accepting an item from the completion list, based on the key I have used for accepting I would like to add a certain (set of) character(s) to the item.

An example in go:

A `struct` has the following fields:

```
type MyType struct {
    IntField int
    SliceField []string
}
```

Pseudo code
```
func main() {
    m := MyType{ IntField: 3, SliceField: []string{"a","b"}
    m.
}
```

Now the completion menu is triggered, showing
```
IntField Field
SliceField Field
```
Assume I have the following keymaps:
```
keymap = {
  ["<CR>"] = { "select_and_accept", "fallback" },
  ["."] = { {"select_and_accept_with_char", "."}, "fallback" }, -- this does not exist, just showing what I am attending to achieve
  ["["] = { {"select_and_accept_with_char", "[", "]"}, "fallback" }, -- this does not exist, just showing what I am attending to achieve
}
```

And further then accepting item `IntField` with the key `.`. The code will now show
```
func main() {
    m := MyType{ IntField: 3, SliceField: []string{"a","b"}
    m.IntField.
}
```

Or accepting item `SliceField` with the key `[`. The code would show 
```
func main() {
    m := MyType{ IntField: 3, SliceField: []string{"a","b"} }
    m.SliceField[]
}
```

Is this currently possible?

**Comment by Saghen** [comment]
These are called `commitCharacters` and I'm planning to support them when neovim 0.11 releases. In the meantime though, you could do this with

```lua
keymap = {
  ["."] = {
    return cmp.select_and_accept({
      callback = function()  vim.api.nvim_feedkeys('.', 'n', true) end,
    })
  }
}
```
