### ISSUE TITLE
Punctuation characters aren't removed after expansion

### ISSUE THREAD

**Issue by stevenxxiu** [Saghen/blink.cmp#559]
### Make sure you have done the following

- [X] I have updated to the latest version of `blink.cmp`
- [X] I have read the README

### Bug Description

In my *luasnip* config, I prefix the snippets with `;`. This way I know it's a snippet.

Snippets expand fine, but the `;` character isn't removed.

Another issue that might be from the same code, is that it seems all punctuation characters trigger my snippets starting with `;`.

### Relevant configuration

Just default settings with *luasnip* in the readme.

### neovim version

v0.10.2

### `blink.cmp` version: branch, tag, or commit

v0.7.6

**Comment by Saghen** [comment]
Duplicate of #46
