### ISSUE TITLE
Feature request: ctags support

### ISSUE THREAD

**Issue by netmute** [Saghen/blink.cmp#56]
I'm one of the weirdos who uses ctags instead of an lsp, and it would be nice to have them show up as completion candidates.

**Comment by Saghen** [comment]
Seems like this should be implemented as an external source, rather than being in-tree. Closing this but would encourage anyone implementing this to link it here

**Comment by netmute** [comment]
I tried to figure the API out by reading your internal source implementations.
It's rather simplistic at the moment, but it works: https://github.com/netmute/blink-cmp-ctags

**Comment by Saghen** [comment]
> Is there documentation or example code for external sources available?

Not yet, hoping to get around to this when the API stabilizes before v1.0

> [netmute/blink-cmp-ctags](https://github.com/netmute/blink-cmp-ctags)

That's great thanks! I've added it to the README under "Community Sources"

**Comment by leosmaia21** [comment]
Hello,
