### ISSUE TITLE
Cmdline wildcard completion results still have wildcards in them

### ISSUE THREAD

**Issue by RadicalTray** [Saghen/blink.cmp#561]
### Make sure you have done the following

- [X] I have updated to the latest version of `blink.cmp`
- [X] I have read the README

### Bug Description

When showing ** and * completion results,  the wildcards are still in the completion results and they are also added after accepting.

![completion results with wildcards](https://github.com/user-attachments/assets/19dcc6c4-9873-4da1-8901-cdaba7931fbc)

![completion result before accepting](https://github.com/user-attachments/assets/ead4b749-cfa2-492e-94ea-2859e957d948)

![cmdline result after accepting](https://github.com/user-attachments/assets/d8c4b271-2c71-475b-ad7d-27f6bdf7a519)

### neovim version

NVIM v0.11.0-dev-1351+gf9dd682621 Build type: RelWithDebInfo LuaJIT 2.1.1732813678 Run "nvim -V1 -v" for more info

### `blink.cmp` version: branch, tag, or commit

main

**Comment by the-fuckin-nobody** [comment]
I think its duplicate of #555, which is a duplicate of #541, which is a duplicate of #46 .

**Comment by RadicalTray** [comment]
ah sorry, ig i'll close this. thx
