### ISSUE TITLE
gcc is missing from build-plugin

### ISSUE THREAD

**Issue by DockterTeagle** [Saghen/blink.cmp#581]
### Make sure you have done the following

- [X] I have updated to the latest version of `blink.cmp`
- [X] I have read the README

### Bug Description

build-plugin will not run w/o gcc on system, this should be added to the flake

### neovim version

n/a

### `blink.cmp` version: branch, tag, or commit

latest commit

**Comment by DockterTeagle** [comment]
I dont want to make a fork cause then I will have to update it sorry I just added gcc to the packages in devShells.default

**Comment by Saghen** [comment]
What's your system triple?

**Comment by DockterTeagle** [comment]
let me clarify, I used the devshell just to add the gcc, after adding gcc to my system config it is fixed, but having compilers in system config is (I hear) not the best practice. Whats a system triple?

**Comment by Saghen** [comment]
Makes sense, thanks. A system triple would be i.e. `aarch64-linux-gnu`

**Comment by mamtaRaiTech** [comment]
It sounds like you're looking to avoid forking the repository to manage updates. Instead, you’ve added gcc to the devShells.default packages.

Regarding your question, could you clarify your system triple? Just a reminder that the build-plugin doesn’t utilize the dev shell.

Let me know if you need further assistance!
