### ISSUE TITLE
Conditionally or Optionally use a Source Only

### ISSUE THREAD

**Issue by kuro337** [Saghen/blink.cmp#582]
### Feature Description

Hey!

Great plugin :)

I had a request - to be able to only show completions for a source.

It might be doable - but I wasn't able to figure out how.

For example, the default config mentions:

```lua
['<C-space>'] = { function(cmp) cmp.show({ providers = { 'snips' } }) end        },
```

But, aren't all sources triggered by default? So I was trying to figure out how to only show this source I had defined - when I press this keymap

Currently my solution was quite hacky -

```lua
['<C-space>'] = {
          function(cmp)
            require('plugins.lsp.snip.blink_loader')._toggle(true)
            cmp.show({ providers = { 'snips' } })
          end,
        },

```

And then in my source I was using this

```lua
function M._toggle(on) M._disabled = on == nil end

function M:get_completions(ctx, callback)
  local cb = function(items)
    callback({
      context = ctx,
      is_incomplete_forward = true,
      is_incomplete_backward = true,
      items = items,
    })
  end

  if M._disabled then
    cb({})
    return function() end
  end
...

```

So I was wondering is there any way to define when to use which source?

For example i tried removing my source from here-

```lua
sources = {

        completion = {
          enabled_providers = { 'lsp', 'path', 'my_source', 'buffer' },
        },
```

But then the source is never shown

Would appreciate any pointers!

**Comment by kuro337** [comment]
Actually the hack doesn't work either, because get_completions() is called each time upon typing, so as soon as I type, it will stay disabled - unless I keep track of when I exit the menu, and keep track of the state

**Comment by sohanemon** [comment]
@kuro337 have you tried with `completion.auto_show`?

**Comment by milanglacier** [comment]
I tried this config and it just works:

```lua
                    ['<A-y>'] = {
                        function(cmp)
                            cmp.show { providers = { 'minuet' } }
                        end,
                    },

```

However, note that `cmp.show` respects `min_keyword_length` even with customized sources.

This means that it will not popup when I want to manually invoke the completion at the beginning of line. I think when the user want to invoke the completion manually via a keybinding, then it makes sense to show the completion popup immediately, regardless of `min_keyword_length`?

**Comment by Saghen** [comment]
> I think when the user want to invoke the completion manually via a keybinding, then it makes sense to show the completion popup immediately, regardless of `min_keyword_length`?

@milanglacier Totally agree, do you mind opening a separate issue for this? 

> So I was wondering is there any way to define when to use which source?

@kuro337 It sounds like you're looking for

```lua
sources.default = function()
  -- return anything here based on the behavior you want
  return { 'lsp', 'path', 'my_source', 'buffer' }
end
```
