### ISSUE TITLE
Add to cmdline attributes such as min_keyword_length

### ISSUE THREAD

**Issue by lbiaggi** [Saghen/blink.cmp#585]
### Make sure you have done the following

- [X] I have updated to the latest version of `blink.cmp`
- [X] I have read the README

### Bug Description

I noticed that if I try to specify to `cmdline source` that I want it to complete only after two characters, I can't as I would do for any other standard source.

What happens: it ignores my definition and switches back to 0, the current workaround is to define `min_keyword_length` as 2 in `sources` 

### Relevant configuration

```lua
sources = {
          cmdline = {
            min_keyword_length = 2,
          },
        }
```

### neovim version

NVIM v0.11.0-dev-1358+g01a97d2ad7

### `blink.cmp` version: branch, tag, or commit

main HEAD

**Comment by Saghen** [comment]
You should be able to do

```lua
sources = {
  min_keyword_length = function(ctx)
    if ctx.mode == 'cmdline' then return 2 end
    return 0
  end
}
```

and in case you only want this min_keyword_length to apply to the initial command, and not arguments afterwards, you could do (untested)

```lua
sources = {
  min_keyword_length = function(ctx)
    if ctx.mode == 'cmdline' and ctx.cursor[2] <= 2 then return 2 end
    return 0
  end
}
```

**Comment by lbiaggi** [comment]
Ah, yes, I reached to the first solution earlier by myself. I was expecting the sources to have the same interface, and was surprised that it wasn't the case.

Anyway thanks!

**Comment by lbiaggi** [comment]
BTW, the second option works quite well!

**Comment by JulianH99** [comment]
Is there any way to disable cmd line completion all together?
