### ISSUE TITLE
Show type of property

### ISSUE THREAD

**Issue by ChristopherK95** [Saghen/blink.cmp#61]
Would be nice to show property type for fields
![image](https://github.com/user-attachments/assets/77f49444-fc8b-4389-afe9-a8f7b0ea910f)

Example from nvim-cmp
![image](https://github.com/user-attachments/assets/ee98ec61-836b-47b1-8d40-134813bf6768)

**Comment by Saghen** [comment]
Sounds like you're looking for `windows.autocomplete.draw = 'reversed'

**Comment by ChristopherK95** [comment]
My issue is about the documentation window which for some reason won't show for certain fields as shown on the first image.
