### ISSUE TITLE
Path source: path completion not working on Windows

### ISSUE THREAD

**Issue by marovira** [Saghen/blink.cmp#612]
### Make sure you have done the following

- [X] I have updated to the latest version of `blink.cmp`
- [X] I have read the README

### Bug Description

In Windows, path completion doesn't work when a path starts with a drive letter, e.g. `C:/`. 
To reproduce:
* Open nvim on an empty buffer in Windows.
* Enter `C:/` and see that no path completion sources are shown.

Note: behaviour is the same if `C:\` is used instead.

Using `nvim-cmp` with [cmp-async-path](https://codeberg.org/FelipeLema/cmp-async-path) works correctly as shown below
![image](https://github.com/user-attachments/assets/7449f914-cc17-498e-95fc-3d0e21b31f66)

And this is blink:
![image](https://github.com/user-attachments/assets/159e3cbd-3dc8-415d-98ff-913878422ff8)

### Relevant configuration

```lua
{
        "saghen/blink.cmp",
        lazy = false,
        dependencies = {
            { "saghen/blink.compat", lazy = true, config = true },
            { "f3fora/cmp-spell" },
            { "hrsh7th/cmp-omni" },
        },
        version = "v0.*",
        opts = {
            keymap = {
                preset = "enter",
                ["<Tab>"] = { "select_next", "fallback" },
                ["<S-Tab>"] = { "select_prev", "fallback" },
            },
            completion = {
                list = {
                    selection = "auto_insert",
                },
                documentation = { auto_show = true },
            },
            signature = { enabled = true },
            sources = {
                completion = {
                    enabled_providers = { "lsp", "path", "buffer" },
                },
            },
        },
    },
```

### neovim version

NVIM v0.10.2

### `blink.cmp` version: branch, tag, or commit

v0.76

**Comment by Saghen** [comment]
I'm on Linux so if someone on Windows could take a look at this, it'd be much appreciated
