### ISSUE TITLE
LuaSnip custom snippets from add_snippets does not show up on completion list

### ISSUE THREAD

**Issue by RiwEZ** [Saghen/blink.cmp#615]
### Make sure you have done the following

- [X] I have updated to the latest version of `blink.cmp`
- [X] I have read the README

### Bug Description

[LuaSnip](https://github.com/L3MON4D3/LuaSnip) `require("luasnip").add_snippets(filetype, snippets)` did not show up on completion list. Can reproduce by the configuration below with lazy.nvim.

![Screenshot 2567-12-17 at 15 50 30](https://github.com/user-attachments/assets/6bc88d2f-c709-4f1e-8546-4dcb395a8f75)

### Relevant configuration

```lua
  {
    'saghen/blink.cmp',
    lazy = false,
    {
      "L3MON4D3/LuaSnip",
      version = "v2.*",
      config = function()
        local ls = require("luasnip")
        local t = ls.text_node
        local i = ls.insert_node
        local s = ls.snippet

        -- custom snippets
        ls.add_snippets("markdown", {
          s("figure", {
            t({
              "<figure>",
              '<img src="" loading="lazy" />',
              "<figcaption>",
              "<center>",
            }),
            i(1, "Lorem"),
            t({
              "</center>",
              "</figcaption>",
              "</figure>",
            }),
          }),
        })
      end,
    },

    version = 'v0.*',

    ---@module 'blink.cmp'
    ---@type blink.cmp.Config
    opts = {
      keymap = { preset = 'enter' },
      snippets = {
        expand = function(snippet) require('luasnip').lsp_expand(snippet) end,
        active = function(filter)
          if filter and filter.direction then
            return require('luasnip').jumpable(filter.direction)
          end
          return require('luasnip').in_snippet()
        end,
        jump = function(direction) require('luasnip').jump(direction) end,
      },
      appearance = {
        use_nvim_cmp_as_default = false,
        nerd_font_variant = 'mono'
      },
      sources = {
        default = { 'luasnip' },
      },
    },
    opts_extend = { "sources.default" }
  },
```

### neovim version

NVIM v0.11.0-dev-1357+gcc38630d39 Build type: RelWithDebInfo LuaJIT 2.1.1732813678

### `blink.cmp` version: branch, tag, or commit

v0.7.6

**Comment by Saghen** [comment]
Fixed on `main`, not sure when :)

**Comment by gennaro-tedesco** [comment]
It seems that in order to activate completion sources the right option syntax is
```lua
 sources = {
      completion = {
        enabled_providers = { 'lsp', 'path', 'luasnip', 'buffer' },
      },
    },
```
and not 
```lua
sources = {
      default = { 'lsp', 'path', 'luasnip', 'buffer' },
    },
```
as stated in the [README](https://github.com/Saghen/blink.cmp?tab=readme-ov-file#luasnip), or am I wrong? I have been seeing the same problem and have accidentally come across [this issue](https://github.com/Saghen/blink.cmp/issues/603) where the above configuration was mentioned.

**Comment by Saghen** [comment]
Click the note at the top of the readme to go to the latest release. The configurations for sources was moved on main, but it hasn't been released yet
