### ISSUE TITLE
unable to set <c-e> to select previous item

### ISSUE THREAD

**Issue by s1n7ax** [Saghen/blink.cmp#617]
### Make sure you have done the following

- [X] I have updated to the latest version of `blink.cmp`
- [X] I have read the README

### Bug Description

Following keymap does not work. I use `<c-n>` and `<c-e>` for next and prev keys. I've been using this with nvim-cmp from the beginning but seems it's broken in blink.

```
['<c-e>'] = { 'select_prev', 'fallback' }
```

### Relevant configuration

```lua
keymap = {
  preset = 'enter',
  ['<c-e>'] = { 'select_prev', 'fallback' }
}
```

### neovim version

NVIM v0.11.0-dev

### `blink.cmp` version: branch, tag, or commit

v0.7.6

**Comment by Saghen** [comment]
There was a bug where keymaps were case sensitive, resolved in #599. You can use `'<C-e>'` in the mean time
