### ISSUE TITLE
Support for LuaSnip as snippets engine

### ISSUE THREAD

**Issue by alienman5k** [Saghen/blink.cmp#62]
The request is to add support for LuaSnip engine to provide snippets. It seems to me that only friendly-snippets is supported but I don't see how to integrate with LuaSnip.

**Comment by Saghen** [comment]
LuaSnip seems out of scope for the built-in snippets provider, which supports `vim.snippet` and vscode-style snippet definitions. I'll leave this to the community to implement as an external provider

**Comment by alienman5k** [comment]
Any documentation on how to build different providers available? Or is that a future feature?

**Comment by Saghen** [comment]
Not yet but it'll be done before 1.0

**Comment by leiserfg** [comment]
The problem is that having only a provider will make it so lsp snippets will use the internal engine, therefore mappings won't work the same.

**Comment by Saghen** [comment]
Using this issue to track support for an `accept.expand_snippet` function

**Comment by Saghen** [comment]
Closed by #286
