### ISSUE TITLE
Minimum text length to buffer complete

### ISSUE THREAD

**Issue by viktor21minds** [Saghen/blink.cmp#635]
### Feature Description

I dont see a way to NOT include "buffer words completion" until some amount of characters was typed. I want lsp ones to be from first character, but buffer ones from 3rd lets say.

**Comment by Saghen** [comment]
Sounds like you're looking for `min_keyword_length`

**Comment by viktor21minds** [comment]
my bad, it looked like a global option ..but apparently you can specify it at source level. Thanks
