### ISSUE TITLE
`#![feature]` may not be used on the stable release channel error on NixOS

### ISSUE THREAD

**Issue by s1n7ax** [Saghen/blink.cmp#637]
### Make sure you have done the following

- [X] I have updated to the latest version of `blink.cmp`
- [X] I have read the README

### Bug Description

I'm using NixOS so to use main branch in Lazyvim, I added following config

Plugin was updated to the latest version but nix flake seems to be using the stable of rust compiler.

```
           Compiling crossbeam-queue v0.3.11
           Compiling quote v1.0.37
           Compiling synchronoise v1.0.1
           Compiling syn v2.0.87
           Compiling page_size v0.6.0
           Compiling parking_lot v0.12.3
           Compiling mlua-sys v0.6.5
           Compiling regex-automata v0.4.9
           Compiling smith_waterman_macro v0.1.0 (https://github.com/saghen/frizbee#78aa7729)
           Compiling frizbee v0.1.0 (https://github.com/saghen/frizbee#78aa7729)
        error[E0554]: `#![feature]` may not be used on the stable release channel
         --> /home/s1n7ax/.cargo/git/checkouts/frizbee-1ed2b540d015bc70/78aa772/src/lib.rs:1:1
          |
        1 | #![feature(portable_simd)]
          | ^^^^^^^^^^^^^^^^^^^^^^^^^^

        For more information about this error, try `rustc --explain E0554`.
        error: could not compile `frizbee` (lib) due to 1 previous error
        warning: build failed, waiting for other jobs to finish...
```

### Relevant configuration

```lua
return {
	'saghen/blink.cmp',
	opts = {
		signature = { enabled = true },
		build = 'nix run .#build-plugin',
	},
}
```

### neovim version

NVIM v0.11.0-dev

### `blink.cmp` version: branch, tag, or commit

046a2af7580ba90cda9ffebbab3f1fe68ca1fa59

**Comment by s1n7ax** [comment]
I use `github:oxalica/rust-overlay` overlay to use nightly rust in my projects.

**Comment by Saghen** [comment]
This project requires nightly rust, the flake should set it up automatically via fenix

**Comment by s1n7ax** [comment]
It was the misplaced build option. cargo build was running on stable rust.

**Comment by theoparis** [comment]
It would be nice if stable rust can be supported

**Comment by sharpchen** [comment]
I've met the same issue. Build failed in neovim but succeeded manually in shell
