### ISSUE TITLE
Missing required fields in the config

### ISSUE THREAD

**Issue by blyedev** [Saghen/blink.cmp#642]
### Make sure you have done the following

- [X] I have updated to the latest version of `blink.cmp`
- [X] I have read the README

### Bug Description

Seems to be a duplicate of #427. I assume however it was resolved and thus I'm rereporting. I'm installing for the first time and I'm getting missing fields errors, not as in the previous report
![image](https://github.com/user-attachments/assets/e9c35911-ae5e-4a44-9af3-b6e1511237dc)

### neovim version

NVIM v0.10.2 Build type: RelWithDebInfo LuaJIT 2.1.1731601260

### `blink.cmp` version: branch, tag, or commit

    ● blink.cmp 5.16ms  start         dir     /home/blyedev/.local/share/nvim/lazy/blink.cmp         url     https://github.com/saghen/blink.cmp         version 0.7.6         tag     v0.7.6         branch  main         commit  ae5a4ce         readme  README.md

**Comment by Saghen** [comment]
It was resolved but hasn't gone out in a release yet

**Comment by blyedev** [comment]
> It was resolved but hasn't gone out in a release yet

Ah my bad thanks for the update
