### ISSUE TITLE
Disable auto_show completion menu for vim cmd

### ISSUE THREAD

**Issue by hikamaree** [Saghen/blink.cmp#644]
### Feature Description

Is there a way to turn off auto_show for the completion menu when I type vim commands. The problem is that I don't want to use completions for some short commands like ```:wq``` and then click enter twice to accept and run the command.

Here is my blink.cmp config:

```lua
return {
	"saghen/blink.cmp",
	build = "cargo build --release",
	event = { "InsertEnter", "CmdLineEnter" },
	opts = {
		keymap = {
			preset = "enter",
			['<ESC>'] = { 'hide', 'fallback' },
		},
		completion = {
			documentation = {
				auto_show = true,
				auto_show_delay_ms = 0,
				window = {
					border = "single",
				}
			},
			menu = {
				border = "single",
				winhighlight = "Normal:Normal",
				draw = {
					columns = { { 'kind_icon' }, { 'label' } },
				}
			},
		},
	}
}
```

**Comment by soifou** [comment]
Yes! This has been answered [here](https://github.com/Saghen/blink.cmp/issues/585#issuecomment-2546004795)
