### ISSUE TITLE
Buffer words not initially available in buffers with an LSP

### ISSUE THREAD

**Issue by GNOMES** [Saghen/blink.cmp#645]
### Make sure you have done the following

- [X] I have updated to the latest version of `blink.cmp`
- [X] I have read the README

### Bug Description

I am coming from using nvim-cmp + cmp-buffer today, so not sure if this is an intentional difference in the goal of this project. 

When an LSP is attached to a buffer, Blink's autocomplete does not seem to match buffer words initially, and instead wants to use LSP recommendations (and friendly-snippets). Continuing autocomplete on a partial string will suggest buffer words. This is not a problem in new files

**-- Buffer words in new file (working as expected)**
1. Open a new empty file
2. Type a test string. Ex. `water`
3. Navigate to a different line
4. Start typing the test string, Blink will suggest auto completing the string. Ex. `water` will be suggestion after the letter `w`

**-- Buffer words in a file with LSP (not working as expected)**
1. Open a new file with an LSP started (I lazily start nvim-lspconfig on filetype). Ex. `nvim test.sh`
2. Type a test string. Ex. `water`
3. Navigate to a different line
4. Start typing the test string, Blink will suggest LSP suggestions. Ex. `water` will not appear as a suggestion
5. Stop typing once string is partially entered. Ex. `wat`
6. Stop the autocomplete suggestions in one of these two ways:
   a. Use space to "leave" the partial string, and hit backspace back to incomplete word
   b. Hit escape to return to normal mode + A to return to insert mode at the end of incomplete word
7. Continue to enter the next letters to finish string, Blink will suggest test string as an autocomplete option. Ex. `water` will be a suggestion after typing `e` at the end of `wat`

I tried playing with reordering the Sources thinking the sources might be processed in order or weighted, but this has no impact.

### Relevant configuration

```lua
return {
    'saghen/blink.cmp',
    event = { "InsertEnter", "CmdLineEnter" },
    dependencies = 'rafamadriz/friendly-snippets',
    version = 'v0.*',
    opts = {
        -- 'default' for mappings similar to built-in completion
        -- 'super-tab' for mappings similar to vscode (tab to accept, arrow keys to navigate)
        -- 'enter' for mappings similar to 'super-tab' but with 'enter' to accept
        -- see the "default configuration" section below for full documentation on how to define
        -- your own keymap.
        keymap = { preset = 'super-tab' },

        appearance = {
            -- Sets the fallback highlight groups to nvim-cmp's highlight groups
            -- Useful for when your theme doesn't support blink.cmp
            -- will be removed in a future release
            use_nvim_cmp_as_default = true,
            -- Set to 'mono' for 'Nerd Font Mono' or 'normal' for 'Nerd Font'
            -- Adjusts spacing to ensure icons are aligned
            nerd_font_variant = 'mono'
        },

        -- default list of enabled providers defined so that you can extend it
        -- elsewhere in your config, without redefining it, via `opts_extend`
        sources = {
            default = { 'buffer', 'lsp', 'path', 'snippets' },
        },
        completion = {
            menu = {
                border = "single",
                scrollbar = false,
            },
            documentation = {
                auto_show = true,
                window = {
                    border = "single",
                },
            },
        },
        signature = { enabled = true },
    },
    -- allows extending the providers array elsewhere in your config
    -- without having to redefine it
    opts_extend = { "sources.default" }
}
```

### neovim version

NVIM v0.10.2

### `blink.cmp` version: branch, tag, or commit

v0.7.6, commit ae5a4ce

**Comment by Saghen** [comment]
I'm not sure I'm understanding correctly, but you might want to set `sources.providers.lsp.fallbacks = {}` so that the buffer source always shows, regardless of whether the LSP is showing or not

**Comment by Ask-786** [comment]
While using ts_ls, it seems to be there is an issue mentioned above. But in lua files, there is no such issue found.
I didn't test any other files by the way.

**Comment by antoinemadec** [comment]
@GNOMES the [doc online](https://cmp.saghen.dev/configuration/general.html) says:
```lua
 sources = {
    -- Remove 'buffer' if you don't want text completions, by default it's only enabled when LSP returns no items
    default = { 'lsp', 'path', 'snippets', 'buffer' },
```

So it seems it is a feature rather than a bug: as soon as the LSP source returns more than 1 item, no buffer items are displayed.

I would very much like to enable the buffer source even when the LSP has suggestions.  
@Saghen is there an option to do this?

**Comment by Saghen** [comment]
Solution is to set `sources.providers.lsp.fallbacks = {}` so that it doesn't block the buffer source from appearing

**Comment by goolord** [comment]
it would be nice if you could set the fallback to a score threshold rather than a number of items, because the lsp I'm using is very aggressive with its suggestions so it never falls back to buffer completions

**Comment by goolord** [comment]
this seems to have broken at some point, with `sources.providers.lsp.fallbacks = {}` I am still not seeing buffer completions
