### ISSUE TITLE
Mapping accept completion to enter remove enter functionality in insert mode

### ISSUE THREAD

**Issue by Rahmyeon** [Saghen/blink.cmp#649]
### Make sure you have done the following

- [X] I have updated to the latest version of `blink.cmp`
- [X] I have read the README

### Bug Description

When mapping enter to accept completion to enter in insert mode, it overrides the default enter behaviour of making a new line. You cannot map accept completion to space> and retain the space bar's normal behaviour. This is on windows

### Relevant configuration

```lua
opts = {
  keymap = {
    ['C-k'] = { 'select_prev' },
    ['C-j'] = { 'select_next' },
    select_and_accept = { '<CR>', '<space>' },
   }
}
```

### neovim version

10.2

### `blink.cmp` version: branch, tag, or commit

v0.76

**Comment by Saghen** [comment]
```
keymap = {
  ['<CR>'] = { 'select_and_accept', 'fallback' }
}
```
Check the default configuration section of the readme for more info
