### ISSUE TITLE
Cannot accept selection with Go

### ISSUE THREAD

**Issue by dahn510** [Saghen/blink.cmp#651]
### Make sure you have done the following

- [X] I have updated to the latest version of `blink.cmp`
- [X] I have read the README

### Bug Description

Plugin: Mason
LSP: gopls (v0.17.0)
Go code:
```Go
package main

import "fmt"

func main() {
    fmt.P
}
```
Then select `Printf` and accept with `<C-y>`.
Result: `...are/nvim/lazy/blink.cmp/lua/blink/cmp/lib/text_edits.lua:73: bad argument #2 to 'str_byteindex' (number expected, got string)`

### Relevant configuration

```lua
{
  'saghen/blink.cmp',
  dependencies = 'rafamadriz/friendly-snippets',

  version = 'v0.*',

  opts = {
    sources = {
      default = { 'lsp', 'path', 'snippets', 'buffer' },
      -- optionally disable cmdline completions
      -- cmdline = {},
    },

    keymap = {
      preset = 'default',
    },

    appearance = {
      use_nvim_cmp_as_default = true,
      nerd_font_variant = 'mono',
    },
    signature = { enabled = true },

    completion = {
      accept = {
        auto_brackets = {
          enabled = false,
        },
      },
      documentation = {
        auto_show = true,
      },
    },
  },
  opts_extend = { 'sources.default' },
}
```

### neovim version

NVIM v0.11.0-dev

### `blink.cmp` version: branch, tag, or commit

main

**Comment by Saghen** [comment]
Try updating your neovim

**Comment by dahn510** [comment]
Built and updated neovim from the source and it works! Thank you!
