### ISSUE TITLE
Issues when writing front-end code

### ISSUE THREAD

**Issue by CSYYDS** [Saghen/blink.cmp#655]
### Make sure you have done the following

- [X] I have updated to the latest version of `blink.cmp`
- [X] I have read the README

### Bug Description

Currently, when I am writing front-end code, I feel that the user experience is not good.

1. When I name functions starting with "catch," I encounter this kind of situation.

https://github.com/user-attachments/assets/16d064f8-e278-44e5-a528-8d9c1e3639f6

2. When I am writing Tailwind CSS, an error occurs when I type "/".

https://github.com/user-attachments/assets/38775425-3586-46e8-b2f6-ae688a1c607d

3. It's frustrating when code completion pops up every time I type or switch from normal mode to insert mode.

The code completion doesn't disappear when I keep pressing the `Enter key`.

https://github.com/user-attachments/assets/8fb13095-b949-4a9e-bef6-eae65b162bc3

When I set these two properties, the issue was resolved. Would it be better if we changed the default values of these two triggers to false?

```lua
{
  trigger = { show_on_accept_on_trigger_character = false, show_on_insert_on_trigger_character = false }
}
```

### Relevant configuration

```lua
https://www.lazyvim.org/extras/coding/blink
```

### neovim version

NVIM v0.10.2

### `blink.cmp` version: branch, tag, or commit

version = not vim.g.lazyvim_blink_main and "*",

**Comment by Saghen** [comment]
1. I get the same snippet recommendation but my snippet expands correctly when accepting. It seems like LazyVim uses a custom snippet expansion so it might be worth raising that over there. If you don't want that snippet to show, you could either disable snippets via `sources.providers.snippets.enabled = false` or filter out the specific snippets you dont want with `sources.providers.snippets.transform_items`. Eventually it would be great if we could pick whether to show snippets more intelligently but that's a stretch goal :)
2. Unfortunately, we won't have a solution for this for a while, opened an issue for it #657
3. Should be fixed on `main`
