### ISSUE TITLE
Add Support for Auto-Complete in Macros

### ISSUE THREAD

**Issue by Jusoaresg** [Saghen/blink.cmp#656]
### Feature Description

Currently, when executing macros, the auto-complete feature does not work as expected. The macro playback does not interact with or retrieve suggestions from the auto-complete, which limits the automation capabilities when using macros.

https://github.com/user-attachments/assets/9a55ad7a-e896-4fa7-8ed8-a58071a17bdf

**Comment by Shougo** [comment]
I think it would be better to provide a specific example since it's not clear how it doesn't work.

**Comment by Saghen** [comment]
Afaik, this would get solved by #182

**Comment by Saghen** [comment]
Duplicate of #182
