### ISSUE TITLE
LuaSnip Source Cache Is Not Cleared When Snippets Are Updated

### ISSUE THREAD

**Issue by Sahas-Ananth** [Saghen/blink.cmp#662]
### Make sure you have done the following

- [X] I have updated to the latest version of `blink.cmp`
- [X] I have read the README

### Bug Description

Currently, when LuaSnippets are added or modified in their respective files, the internal cache of the `luasnip` source is not automatically cleared. This necessitates either a manual call to the API's `reload` function or a full Neovim restart to reflect the updated snippets. This behavior disrupts workflow and reduces usability.  

LuaSnip provides the following events:  
- **`LuasnipSnippetsAdded`**: Triggered when snippets are added or modified.  
- **`LuasnipCleanup`**: Triggered when all snippets need to be cleared.

However, the cache is not automatically refreshed upon emitting these events, which prevents users from seeing updated snippets.

While related issues (#603 and #615) have discussed this problem, the existing fix still requires manual intervention or a restart, which does not fully resolve the issue.  

I have addressed this issue in my fork. If you're interested, I can submit a PR with the fix.

### Relevant configuration

```lua
{
  'saghen/blink.cmp',
  version = 'v0.*',
  -- !Important! Make sure you're using the latest release of LuaSnip
  -- `main` does not work at the moment
  dependencies = { 'L3MON4D3/LuaSnip', version = 'v2.*' },
  opts = {
    snippets = {
      expand = function(snippet) require('luasnip').lsp_expand(snippet) end,
      active = function(filter)
        if filter and filter.direction then
          return require('luasnip').jumpable(filter.direction)
        end
        return require('luasnip').in_snippet()
      end,
      jump = function(direction) require('luasnip').jump(direction) end,
    },
    sources = {
      default = { 'lsp', 'path', 'luasnip', 'buffer' },
    },
  }
}
```

### neovim version

v0.10.1

### `blink.cmp` version: branch, tag, or commit

Branch: main, Commit: 07665c3

**Comment by Saghen** [comment]
Pr would be great, thanks!

**Comment by Sahas-Ananth** [comment]
Great just made the PR check it out!
