### ISSUE TITLE
Completion not working properly with clangd and friendly-snippets active

### ISSUE THREAD

**Issue by allpandasarecute** [Saghen/blink.cmp#67]
This is example of completion not working with clangd with active friendly-snippets (first picture - with snippets, second - without (removed as a dependency))
It's not showing `print` function, declared just before `main`

config (`lazy.nvim`):
```lua
return {
    {
        "Saghen/blink.cmp",
        lazy = false,
        dependencies = "rafamadriz/friendly-snippets",
        version = "v0.*",
        opts = {
            highlight = {
                use_nvim_cmp_as_default = true,
            },
            keymap = {
                show = "<C-space>",
                hide = "<C-e>",
                accept = "<Tab>",
                select_prev = "<C-l>",
                select_next = "<C-k>",
                scroll_documentation_up = "<C-u>",
                scroll_documentation_down = "<C-d>",
            },
            windows = {
                autocomplete = { border = "rounded" },
                documentation = { border = "rounded" },
                signature_help = { border = "rounded" },
            },
        },
    },
}
```

![2024-10-09_21-28](https://github.com/user-attachments/assets/c5e11581-2c13-4350-94dc-e67526b98bdd)
![2024-10-09_21-37](https://github.com/user-attachments/assets/7ce213f2-2c28-401c-9d77-d81becefde0d)

**Comment by Saghen** [comment]
Unable to reproduce on `main` so it appears to have been solved at some point, but not sure when
