### ISSUE TITLE
Failed to run healthcheck for "blink.cmp" plugin

### ISSUE THREAD

**Issue by ViniciusSantos19** [Saghen/blink.cmp#676]
### Make sure you have done the following

- [X] I have updated to the latest version of `blink.cmp`
- [X] I have read the README

### Bug Description

                         Failed to run `config` for blink.cmp

...share/nvim/lazy/blink.cmp/lua/blink/cmp/config/utils.lua:10: completion.menu.draw.treesitter: expected table, got boolean

# stacktrace:
  - /blink.cmp/lua/blink/cmp/config/utils.lua:10 _in_ **validate**
  - /blink.cmp/lua/blink/cmp/config/completion/menu.lua:163 _in_ **validate**
  - /blink.cmp/lua/blink/cmp/config/completion/init.lua:37 _in_ **validate**
  - /blink.cmp/lua/blink/cmp/config/init.lua:41 _in_ **validate**
  - /blink.cmp/lua/blink/cmp/config/init.lua:52 _in_ **merge_with**
  - /blink.cmp/lua/blink/cmp/init.lua:18 _in_ **setup**
  - /LazyVim/lua/lazyvim/plugins/extras/coding/blink.lua:163 _in_ **config**
  - /LazyVim/lua/lazyvim/plugins/lsp/init.lua:181 _in_ **config**
  - lua/config/lazy.lua:9
  - init.lua:2

 ERROR Failed to run healthcheck for "blink.cmp" plugin. Exception:
  ...local/share/nvim/lazy/blink.cmp/lua/blink/cmp/health.lua:27: bad argument #1 to 'fs_stat' (string expected, got nil)

### neovim version

0.10.2

### `blink.cmp` version: branch, tag, or commit

  "blink.cmp": { "branch": "main", "commit": "ca05bb33eb071d916d33af08cae8034c3d8002b5" },

**Comment by Saghen** [comment]
Update your LazyVim

**Comment by zulian-dev** [comment]
Some error here, All plugins and lazyVim updated...
Only NVIM(v0.10.2) not updated

**Comment by coreymaher** [comment]
I'm seeing the same error:
```
nvim --version
NVIM v0.10.2
Build type: Release
LuaJIT 2.1.1732813678
```
```
lazy.nvim ~
- {lazy.nvim} version `11.16.2`
- OK {git} `version 2.39.3 (Apple Git-145)`
```

```
blink.cmp healthcheck ~
- OK curl is installed
- OK git is installed
- OK Your system is supported by pre-built binaries (aarch64-apple-darwin)
- ERROR Failed to run healthcheck for "blink.cmp" plugin. Exception:
  ...local/share/nvim/lazy/blink.cmp/lua/blink/cmp/health.lua:27: bad argument #1 to 'fs_stat' (string expected, got nil)
```

**Comment by pfries** [comment]
Looks like #629 missed a change to https://github.com/Saghen/blink.cmp/pull/629/files#diff-614107bada9591b618feafcaf463f86068afc46c7aa1c9e313f8a260d3684ff2L27

**Comment by jmandel1027** [comment]
I'm getting the same thing 😢 

```
blink.cmp: require("blink.cmp.health").check()

blink.cmp healthcheck ~
- OK curl is installed
- OK git is installed
- OK Your system is supported by pre-built binaries (aarch64-apple-darwin)
- ERROR Failed to run healthcheck for "blink.cmp" plugin. Exception:
  ...local/share/nvim/lazy/blink.cmp/lua/blink/cmp/health.lua:27: bad argument #1 to 'fs_stat' (string expected, got nil)
```

```
  "blink-cmp-copilot": { "branch": "main", "commit": "c38d3e4201b135ab290c7ad126a9720cf76c788c" },
  "blink.cmp": { "branch": "main", "commit": "ca05bb33eb071d916d33af08cae8034c3d8002b5" },
...
  "lazy.nvim": { "branch": "main", "commit": "7e6c863bc7563efbdd757a310d17ebc95166cef3" },
```

```
  $  nvim --version
NVIM v0.10.2
Build type: Release
LuaJIT 2.1.1734355927
Run "nvim -V1 -v" for more info
```
