### ISSUE TITLE
menu.max_width unexpected field?

### ISSUE THREAD

**Issue by adudenamedruby** [Saghen/blink.cmp#680]
### Make sure you have done the following

- [X] I have updated to the latest version of `blink.cmp`
- [X] I have read the README

### Bug Description

I'm getting this error message on startup since I updated blink today.

<img width="1344" alt="Screenshot 2024-12-20 at 4 21 34 PM" src="https://github.com/user-attachments/assets/6381a059-e8be-49aa-83df-1b8d6bf457aa" />

I only have 2 `max_width` configs in blink:

<img width="644" alt="Screenshot 2024-12-20 at 4 22 24 PM" src="https://github.com/user-attachments/assets/bcb96266-f8d7-4282-9568-1c65b60cf588" />

This was not happening previously.

### neovim version

0.10.2

### `blink.cmp` version: branch, tag, or commit

0.8.0

**Comment by Saghen** [comment]
Yep, it's no longer supported

**Comment by zivkovicn** [comment]
I'm experiencing this as well, just I'm using lazyvim and here is my config:

```
return {
  "saghen/blink.cmp",
  opts = {
    completion = {
      snippet = {
        enabled = false,
      },
      ghost_text = {
        enabled = false,
      },
      menu = {
        draw = {
          treesitter = true,
          columns = { { "label", "label_description", gap = 1 }, { "kind_icon", "kind" } },
        },
      },
    },
    sources = {
      default = { "lsp", "buffer", "path" },
    },
    keymap = {
      preset = "enter",
      ["<Tab>"] = {
        LazyVim.cmp.map({ "ai_accept" }),
        "fallback",
      },
    },
  },
}
```

https://www.lazyvim.org/extras/coding/blink#blinkcmp

I don't see it set by @folke in his default config, any hint?
