### ISSUE TITLE
Occasional error when accepting items

### ISSUE THREAD

**Issue by julienvincent** [Saghen/blink.cmp#69]
I am seeing the below error while trying to accept items from the typescript LSP:

<img width="1468" alt="Screenshot 2024-10-09 at 16 37 51" src="https://github.com/user-attachments/assets/e9ec9b98-f020-429f-bf4f-5dc553b6392d">

To reproduce I just do the following:

```js
"abc".toS|
;; trigger autocomplete and accept
```

It fails to accept and throws the above error

**Comment by Saghen** [comment]
Which LSP are using for Typescript? I'm unable to reproduce on tsserver (`ts_ls` in lspconfig)

**Comment by julienvincent** [comment]
Hmm.. I re-ran `cargo build --release` and now I can't reproduce it anymore. But this was using tsserver and in a javascript file (not ts). But oh well I'll close this one and re-open if I notice it again.

**Comment by Saghen** [comment]
My best guess is you ran into the same issue as #21
