### ISSUE TITLE
Flickering of completion menu with 2 LSPs

### ISSUE THREAD

**Issue by arztareef** [Saghen/blink.cmp#691]
### Make sure you have done the following

- [X] I have updated to the latest version of `blink.cmp`
- [X] I have read the README

### Bug Description

sample specifying the bug:

https://github.com/user-attachments/assets/62875d36-fa9b-4849-b4c3-dfa8c8fdd67d

As the recording suggests, blinking (no pun intended) occurs with the menu.
This only occured to me when I am writing property for a CSS selector with using the LSP (cssls and emmet-language-server)

### Relevant configuration

```lua
--- Not sure what could be the relevant config for this matter, pasting the one for the menu in here:
{
  completion = {
    list = {
      max_items = 50,
      selection = 'manual',
    },
    menu = {
      max_height = 100,
      scrolloff = 999,
    },
  },
}
```

### neovim version

NVIM v0.11.0-dev-1388+g39781be14b

### `blink.cmp` version: branch, tag, or commit

v0.*

**Comment by emnnipal** [comment]
I’m experiencing the same issue as well, but with `emmet-language-server`.


https://github.com/user-attachments/assets/8123858e-df09-4519-9f68-9ed174531c6d

**Comment by arztareef** [comment]
i forgot to mention, i used emmet-language-server as well alongside cssls

**Comment by Saghen** [comment]
For anyone looking to fix this, we show the menu as soon as any LSP returns a response, with the motivation being to prevent slow LSPs from blocking all the LSPs. We should instead make this configurable since it shouldn't be necessary in most cases. In the future, it would be ideal if we could detect slow LSPs explicitly
