### ISSUE TITLE
Many shorthand notation not showing up in the cmdline completion menu

### ISSUE THREAD

**Issue by saitharun14** [Saghen/blink.cmp#692]
### Make sure you have done the following

- [X] I have updated to the latest version of `blink.cmp`
- [X] I have read the README

### Bug Description

Many shorthand notations of commands aren't showing up in cmdline completion menu. Shorthand notations like
w, q, e, clo, sp to name a few aren't showing up where as wq is showing.
<img width="581" alt="image" src="https://github.com/user-attachments/assets/1029e49f-722a-493b-8fab-e3dd45292a63" />
<img width="573" alt="image" src="https://github.com/user-attachments/assets/dc9d305e-8758-4161-9fde-83d3eefc735e" />
<img width="563" alt="image" src="https://github.com/user-attachments/assets/0eae2f65-2300-46c3-ba80-ef2a110e5739" />

Since the first options for w, q, e are different from there intended command on clicking enter wrong commands are being selected

### neovim version

NVIM v0.10.2 Build type: Release LuaJIT 2.1.1734355927

### `blink.cmp` version: branch, tag, or commit

v0.8.0

**Comment by Shougo** [comment]
It is feature.  The shorthand notation is not listed in command line completion list.
You can check it with `nvim --clean`.

**Comment by saitharun14** [comment]
Thanks for clarification. Keep up the great work !!
