### ISSUE TITLE
Weird highlights caused by blink with html (html-ls and emmet-language-server)

### ISSUE THREAD

**Issue by arztareef** [Saghen/blink.cmp#693]
### Make sure you have done the following

- [X] I have updated to the latest version of `blink.cmp`
- [X] I have read the README

### Bug Description

sample of this problem is given below:

https://github.com/user-attachments/assets/488d1af1-89b0-4ebf-9cb8-bab1cae5a790

LSPs used:
html-ls, emmet-language-server

Note: ! is an emmet abbreviation for a basic html structure which generates boilerplate html

Using ! causes random highlights throughout the code (note that these highlights aren't connected with snippets), after formatting the file (i used prettier for this case), it causes even a bigger highlight all over the code and it doesn't remove away even after i go into insert mode:

![image](https://github.com/user-attachments/assets/a0f0effc-3370-413c-bb77-bbafc4b1cdb5)

### Relevant configuration

```lua
--- using default config with tweaks to keymaps and icons
```

### neovim version

NVIM v0.11.0-dev-1388+g39781be14b

### `blink.cmp` version: branch, tag, or commit

v0.*

**Comment by terxxz** [comment]
![wezterm-gui_5tMIMAawMg](https://github.com/user-attachments/assets/69fa450a-5d33-4a41-932e-0e37d4e57b32)
Same thing

**Comment by Saghen** [comment]
Those highlights are caused by the built-in snippets (`vim.snippet.expand`) and it seems to be working as normal. You could try switching to LuaSnip if you prefer its behavior
