### ISSUE TITLE
feat: manual border overriding with symbol option

### ISSUE THREAD

**Issue by arztareef** [Saghen/blink.cmp#694]
### Feature Description

I like to use this set of unicode to set borders for telescope and other border related widgets available with neovim:

```lua 
border = { '▄', '▄', '▄', '█', '▀', '▀', '▀', '█' },
```

example (screenshot from a past completion plugin I used to use):
![image](https://github.com/user-attachments/assets/f7919c70-a8b6-43c4-9195-2953f037a5a3)

I would really appreciate it, if the author could add a feature related with configuring custom borders with unicodes/symbols of choice. Thank you for reading this.

**Comment by soifou** [comment]
You can already do it since blink.cmp use `nvim_open_win` for completion, documentation and signature. 
I'm using myself a very similar set of unicode for this :)

Might be worth to add a section in the new documentation though.

**Comment by arztareef** [comment]
> You can already do it since blink.cmp use `nvim_open_win` for completion, documentation and signature. I'm using myself a very similar set of unicode for this :)
> 
> Might be worth to add a section in the new documentation though.

Thanks a lot!
