### ISSUE TITLE
`ctx` param is always nil in `enabled` function of a provider specific opts after v0.8.0

### ISSUE THREAD

**Issue by nowaylifer** [Saghen/blink.cmp#695]
### Make sure you have done the following

- [X] I have updated to the latest version of `blink.cmp`
- [X] I have read the README

### Bug Description

wasn't an issue prior to v0.8.0

### Relevant configuration

```lua
sources = {
  providers = {
    lsp = {
      enabled = function(ctx)
        vim.print(ctx) -- always nil
        return true
      end,
    },
  },
}
```

### neovim version

v0.10.2 

### `blink.cmp` version: branch, tag, or commit

v0.8.0

**Comment by Saghen** [comment]
That's intentional, I may add it back in the future but it's unlikely
