### ISSUE TITLE
Windows support?

### ISSUE THREAD

**Issue by linrongbin16** [Saghen/blink.cmp#7]
Looks like the releases doesn't contain any windows platform.

Is there a plan to support it as well? Or please document it so windows users won't get confused.

**Comment by benlubas** [comment]
#3 would support windows afaik

**Comment by adelarsq** [comment]
I was able to build the project on Windows, but shows this message on start:

```
Error while downloading blink.cmp pre-built binary: Can't download from github due to not being on a git tag and no native_download.version set, but found no built version of the library. Either run `cargo build --release` via your package manager, switch to a git tag, or set `native_download.version` in config. See the README for more info.
```

So would be just needed to add a setup for the generated `dll` file.

**Comment by Saghen** [comment]
@adelarsq after #74, that issue should be fixed

**Comment by adelarsq** [comment]
@Saghen Cool! I will take a look.

**Comment by scottmckendry** [comment]
@Saghen any change we can push a release through to get the windows binary generated?
