### ISSUE TITLE
Accepting cmdline completion inserts excess `-- ` when using `selection = "auto_insert"`

### ISSUE THREAD

**Issue by chrisgrieser** [Saghen/blink.cmp#702]
### Make sure you have done the following

- [X] I have updated to the latest version of `blink.cmp`
- [X] I have read the README

### Bug Description

1. press `/`
2. type something
3. select first item with `<C-n>`
4. accept with `<C-y>`
5. the accepted item has a leading `-- ` in there

---

somewhat related, the `enter` keymap preset together with the default `select = "preselect"` is also not ideal. It's technically not buggy, but pressing enter often selects an item, even though you intend to search for what you have currently typed.

### Relevant configuration

```lua
opts = {
	completion = {
		list = {
			selection = "auto_insert",
		},
	},
},
```

### neovim version

NVIM v0.10.2

### `blink.cmp` version: branch, tag, or commit

0.8.0

**Comment by itse4elhaam** [comment]
I dont know if this is related or not, but when I am writing a command in Neovim, it is automatically popping up the suggestions but it was not like this before the recent update.

How can I disable it? It should only appear on Tab like it used to.

**Comment by Saghen** [comment]
@itse4elhaam Sounds like you'll want to wait for #697 so you can disable `auto_show` in cmdline mode

**Comment by Saghen** [comment]
@chrisgrieser I'm unable to reproduce this, could you provide an example file and maybe a video of it happening?

**Comment by itse4elhaam** [comment]
Hey @Saghen, Can something like this work as a temporary workaround?



```
-- NOTE: not working right now in the current state

vim.api.nvim_create_autocmd("CmdlineEnter", {
  callback = function()
    require("blink.cmp").opts.completion.menu.auto_show = false
  end,
})

vim.api.nvim_create_autocmd("CmdlineLeave", {
  callback = function()
    require("blink.cmp").opts.completion.menu.auto_show = true
  end,
})
```

**Comment by Saghen** [comment]
Yes! Very hacky so it might break in the future :)

**Comment by itse4elhaam** [comment]
That did not work so I implemented this:

```
vim.api.nvim_create_autocmd("CmdlineEnter", {
  callback = function()
    vim.api.nvim_set_keymap('c', '<CR>', '<CR>', { noremap = true, silent = true })
  end,
})

```

For some context:  I have remapped my enter and tab both for completion but in the command line it just execs my current command instead of going to the selection.

Just for reference:

```
      keymap = {
        preset = "super-tab",
        ["<CR>"] = { "accept", "fallback" },
      }
```

**Comment by chrisgrieser** [comment]
@Saghen 

https://github.com/user-attachments/assets/d1e7f1f9-670a-401a-8e5e-73f6ef854333

**Comment by itse4elhaam** [comment]
@Saghen 

I know this was merged but I am finding it hard to figure out how to implement this?

Can you help?

Thanks!
