### ISSUE TITLE
Support reapplying documentation syntax when reshowing existing doc

### ISSUE THREAD

**Issue by mikavilpas** [Saghen/blink.cmp#703]
### Feature Description

When working with the custom documentation rendering implemented in  https://github.com/Saghen/blink.cmp/pull/650, I implemented regex based highlighting in https://github.com/mikavilpas/blink-ripgrep.nvim/pull/65.

I just noticed that if I hide and reshow the documentation, the syntax highlighting is reset: 

https://github.com/user-attachments/assets/07793221-fc83-49cd-b310-c54c401f562b

This seems to be happening due to the window's filetype gets reset here https://github.com/Saghen/blink.cmp/blob/5a71e8e01f44084de9f7351f1e2bef74cdc0c450/lua/blink/cmp/lib/window/init.lua?plain=1#L111

I think it happens because the `:syntax on` regex based higlighting depends on the filetype (not completely sure).

I wanted to ask if you have an idea about how this could be supported. It looks like disabling the setting of the filetype fixes it, but that is probably a breaking change and problematic.

For example, I could add a `reopen` hook where I could set this in blink-ripgrep 
![image](https://github.com/user-attachments/assets/be9d4cf0-820c-49cb-9b2d-d1a64b14ec4d)

![image](https://github.com/user-attachments/assets/d24149cc-aadf-4e38-89ef-fc9699d697de)

**Comment by Saghen** [comment]
Maybe the simplest solution would be to redraw the window when reshowing the window
