### ISSUE TITLE
completion does not replace user input but append to it

### ISSUE THREAD

**Issue by shaozi** [Saghen/blink.cmp#705]
### Make sure you have done the following

- [X] I have updated to the latest version of `blink.cmp`
- [X] I have read the README

### Bug Description

When completing, the complete item is appended to the string user typed instead of replacing it. This causes extra letters in front of the final result. For example, when type `dir` and the completion is `direction`, it insert `dirdirection` when press Enter. See video attached.

https://github.com/user-attachments/assets/3b480731-8397-4897-b1ef-8df963a85ab3

### neovim version

NVIM v0.10.2 Build type: Release LuaJIT 2.1.1731601260

### `blink.cmp` version: branch, tag, or commit

v0.8.0 commit ca05bb3

**Comment by Saghen** [comment]
Does this happen on all LSPs and what LSP is this?

**Comment by shaozi** [comment]
It is golang. Not sure which is being used. Gofumpt, goimports, and gopls

**Comment by shaozi** [comment]
Just tested Markdown and it is working there. So seems golang specific

**Comment by shaozi** [comment]
gopls: v0.17.1

**Comment by shaozi** [comment]
Ha! just found that it is caused by a mis-spell of the "switch" keyword, it was spelled as "swith", missing an "c". So this bug only appears when the "switch" is mis-spelled. After fixing it works.

**Comment by Saghen** [comment]
Haha nice, might be worth reporting that upstream to gopls
