### ISSUE TITLE
Add configure option for padding top and bottom

### ISSUE THREAD

**Issue by Kaiser-Yang** [Saghen/blink.cmp#710]
Thank you for contribution to this amazing plugin!

### Feature Description

Is there any posibility to configure the padding at those positons?

![image](https://github.com/user-attachments/assets/ce119d0c-99f1-4427-bcb5-a197214e9c4c)

**Comment by Saghen** [comment]
You can pass an array for the border that controls the symbols on all sides. You could add a space to the border on those sides

`:h api-win_config`

**Comment by Kaiser-Yang** [comment]
> You can pass an array for the border that controls the symbols on all sides. You could add a space to the border on those sides
> 
> `:h api-win_config`

Could you just give me more details, I just want to remove the empty space at the top and bottom.

BTW, could you just give me the configuration for the demo video, I think the menu style in the demo video is what I really want.
