### ISSUE TITLE
Option function for updating documentation

### ISSUE THREAD

**Issue by Kaiser-Yang** [Saghen/blink.cmp#712]
Thak you for your contributions for this amazing plugin.

### Feature Description

I want to know if it possible to add a configuration function to update the contents of documentation.

Actually, I just want to make some sources' documentation not visible, I've tried this in transform_items, but it seems that the documentation is not requested when calling function transform_items.

**Comment by Saghen** [comment]
`transform_items` now gets called for resolved items so you should be able to achieve this
