### ISSUE TITLE
Key map with suffix not work

### ISSUE THREAD

**Issue by Kaiser-Yang** [Saghen/blink.cmp#713]
### Make sure you have done the following

- [X] I have updated to the latest version of `blink.cmp`
- [X] I have read the README

### Bug Description

I've mapped `;<space>` to some functionality in insert mode, then I update the `keymap` to accept the second item.

I can not accept the second item unless I remove the `;<space>` keymap:

Input something first:

![image](https://github.com/user-attachments/assets/fd478f0e-5035-4d47-95de-760d7318a248)

Input `;`, it seems to waif for `updatetime` to determine it's single key or continuous key:

![image](https://github.com/user-attachments/assets/4173b000-525f-435f-a623-3faba17e1024)

After that, nothing happend, event the `;` is not inserted:

![image](https://github.com/user-attachments/assets/06537049-9918-4b3c-94b6-480c8ea21a30)

### Relevant configuration

```lua
local mapped_punc = {
    [','] = '，',
    ['.'] = '。',
    [':'] = '：',
    [';'] = '；',
    ['?'] = '？',
    ['\\'] = '、'
}
local function feed_key_helper(k, v)
    if v == nil or k == v then
        feedkeys(k, 'n')
    else
        feedkeys(v, 'm')
    end
end
            map.set({ 'i' }, k .. '<space>', function()
                feed_key_helper(v, v)
            end, opts())

keymap = {
                [';'] = {
                    -- FIX: can not work when binding ;<space> to other key
                    function(cmp)
                        if not vim.g.rime_enabled then return false end
                        local items = require('blink.cmp.completion.list').items
                        local rime_item_index = get_n_rime_item_index(2, items)
                        if #rime_item_index ~= 2 then return false end
                        return cmp.accept({ index = rime_item_index[2] })
                    end, 'fallback' },
}
```

### neovim version

NVIM v0.10.1

### `blink.cmp` version: branch, tag, or commit

v0.8.1

**Comment by Kaiser-Yang** [comment]
This should be fixed after https://github.com/Saghen/blink.cmp/pull/487

**Comment by Saghen** [comment]
I'm not able to reproduce this

```lua
vim.keymap.set('i', ';<space>', '<cmd>echo "foo"<cr>', { noremap = false, silent = true })
```

```lua
keymap = {
  [';'] = { function() return false end, 'fallback' }
}
```

**Comment by Kaiser-Yang** [comment]
> I'm not able to reproduce this
> 
> ```lua
> vim.keymap.set('i', ';<space>', '<cmd>echo "foo"<cr>', { noremap = false, silent = true })
> ```
> 
> ```lua
> keymap = {
>   [';'] = { function() return false end, 'fallback' }
> }
> ```

Return false will not reprodue, use this minimal below:

```lua
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not (vim.uv or vim.loop).fs_stat(lazypath) then
    vim.fn.system({
        "git",
        "clone",
        "--filter=blob:none",
        "https://github.com/folke/lazy.nvim.git",
        "--branch=stable", -- latest stable release
        lazypath,
    })
end
vim.opt.rtp:prepend(lazypath)
require('lazy').setup({
    spec = {
        {

            'saghen/blink.cmp',
            version = '*',

            ---@module 'blink.cmp'
            ---@type blink.cmp.Config
            opts = {
                keymap = {
                    preset = 'none',
                    [';'] = {
                        function(cmp)
                            return cmp.accept()
                        end, 'fallback' },
                },
            },
            opts_extend = { "sources.default" }
        },
    }
})
vim.keymap.set({ 'i' }, ';<space>', '；', { silent = true, remap = false })
```

**Comment by Saghen** [comment]
This is quite the edge case :D It seems like the keymap never gets called by neovim, so there's not much we can do on our side. You might want to want to wait for #487 which may resolve this
