### ISSUE TITLE
Auto completion in command line suggesting strange options

### ISSUE THREAD

**Issue by nathanjcollins** [Saghen/blink.cmp#715]
### Make sure you have done the following

- [X] I have updated to the latest version of `blink.cmp`
- [X] I have read the README

### Bug Description

<img width="340" alt="Screenshot 2024-12-22 at 06 54 46" src="https://github.com/user-attachments/assets/5f6e0116-7aa7-4259-b4b2-a13956576ffb" />

While trying to do `:w` I always get `:wNext` as an option, and because I'm using `enter` as my accept key, I try to do `:w` -> `enter` for a quick save, but then end up with `:wNext` in my cmd line and have to manually delete it. This happens with all commands, I try to do `:<cmd>` `enter` but end up with some command I don't want.

Maybe this is a config issue?

### Relevant configuration

```lua
opts = {
    completion = {
      -- experimental auto-brackets support
      accept = { auto_brackets = { enabled = false } },
    },

    keymap = { preset = 'enter' },

    signature = {
      enabled = true,
    },
  },
```

### neovim version

0.10.2

### `blink.cmp` version: branch, tag, or commit

0.8.1

**Comment by aj3423** [comment]
Same here, looking for an option to not pre-select the first item.

**Comment by tigion** [comment]
In this case, I use `auto_insert` to not select by default during list selection and also limit `min_keyword_length` to 2:

```lua
opts ={
  completion = {
    list = {
      selection = 'auto_insert',
    },
  },

  sources = {
    cmdline = {
      min_keyword_length = 2,
    },
  }
}
```

It would be better if you could set the behavior of `selection` for cmdline separately from other sources.

**Comment by Parsifa1** [comment]
try this:

```lua
init = function()
        -- FIX: Temporary for not being able to set auto_insert for cmdline
        local orig_list_selection = nil
        vim.api.nvim_create_autocmd("CmdlineEnter", {
            callback = function()
                local list = require "blink.cmp.completion.list"
                orig_list_selection = list.config.selection
                list.config.selection = "auto_insert"
            end,
        })
        vim.api.nvim_create_autocmd("CmdlineLeave", {
            callback = function()
                if orig_list_selection then
                    local list = require "blink.cmp.completion.list"
                    list.config.selection = orig_list_selection
                end
            end,
        })
    end,
```


ref https://github.com/Saghen/blink.cmp/pull/532#issuecomment-2551888386

**Comment by aj3423** [comment]
> In this case, I use `auto_insert` to not select by default during list selection and also limit `min_keyword_length` to 2:
> 
> ```lua
> opts ={
>   completion = {
>     list = {
>       selection = 'auto_insert',
>     },
>   },
> 
>   sources = {
>     cmdline = {
>       min_keyword_length = 2,
>     },
>   }
> }
> ```
> 
> It would be better if you could set the behavior of `selection` for cmdline separately from other sources.

This works well, thanks.
