### ISSUE TITLE
[Question] How to pretty render documentation preview

### ISSUE THREAD

**Issue by youwen5** [Saghen/blink.cmp#73]
In `nvim-cmp`, the preview popup is rendered (afaik) as markdown which cleans it up and adds treesitter highlighting for code snippets.
![image](https://github.com/user-attachments/assets/856e521c-210e-4cba-8591-93fe44eb11d1)
Is there a way I can have the preview buffer rendered? 
![image](https://github.com/user-attachments/assets/897b7661-fd09-48ce-8a9d-ae903b1a1cc2)

**Comment by dsully** [comment]
Are you using `noice.nvim`? As it also cleans up the markdown. It might be a good idea to use that code in blink.

**Comment by youwen5** [comment]
Not using noice, I'm in the middle of redoing my config from scratch so this should be a fairly minimal setup

**Comment by DaniBedz** [comment]
Please let me know if you manage to get this working - having the same issue here with markdown being displayed.

**Comment by sudo-tee** [comment]
I was able to get it to work with the render-markdown plugin with the following config
```lua
{
      'MeanderingProgrammer/render-markdown.nvim',
      ---@module 'render-markdown'
      ---@type render.md.UserConfig
      opts = {
        file_types = { 'markdown', 'Avante' },
        log_level = 'debug',
        overrides = {
          buftype = {
            nofile = {
              render_modes = { 'n', 'c', 'i' },
              debounce = 5,
            },
          },
          filetype = {},
        },
      },
      ft = { 'markdown', 'Avante' },
    }
```

**Comment by Biggybi** [comment]
@sudo-tee nice one!

Also, one might want to undo paddings to avoid wrapping lines:

    overrides = {
      buftype = {
        nofile = {
          render_modes = { "n", "c", "i" },
          debounce = 5,
          code = {
            left_pad = 0,
            right_pad = 0,
            language_pad = 0,
          },
        },
      },
      filetype = {},
    },

**Comment by Saghen** [comment]
I've added `vim.lsp.util.stylize_markdown` to the window, lmk if that works for styling without external plugins

**Comment by Saghen** [comment]
Closing this, please let me know if you're still running into unstyled windows (with the `markdown` treesitter parse installed) and I'll re-open
