### ISSUE TITLE
Cmdline error when immediately exiting after opening

### ISSUE THREAD

**Issue by lost22git** [Saghen/blink.cmp#738]
### Make sure you have done the following

- [X] I have updated to the latest version of `blink.cmp`
- [X] I have read the README

### Bug Description

i map `qq` -> `:q\<CR>` to quit neovim. 
when i `qq`, an error from blink.cmp always bothers me like this:

![Screenshot_20241224-041348](https://github.com/user-attachments/assets/f322b444-771f-46c7-8950-bd39d3ba485c)

### Relevant configuration

```lua
return {
  "saghen/blink.cmp",
  enabled = vim.g.cmp == "blink",
  lazy = false,
  dependencies = { "rafamadriz/friendly-snippets" },
  version = "*",

  opts = {
    keymap = {
      ["<M-j>"] = { "select_next", "fallback" },
      ["<M-k>"] = { "select_prev", "fallback" },
      ["<Tab>"] = { "select_and_accept", "fallback" },
      ["<C-c>"] = { "hide", "fallback" },
      ["<M-Space>"] = { "show", "show_documentation", "hide_documentation" },
      ["<C-u>"] = { "scroll_documentation_up", "fallback" },
      ["<C-d>"] = { "scroll_documentation_down", "fallback" },
    },
    appearance = {
      use_nvim_cmp_as_default = true,
      nerd_font_variant = "mono",
    },
    sources = {
      default = { "lsp", "path", "snippets", "buffer" },
    },
    signature = { enabled = true },
  },
  opts_extend = { "sources.default" },
}
```

### neovim version

NVIM v0.10.3 Build type: Release LuaJIT 2.1.1731601260 Run "nvim -V1 -v" for more info

### `blink.cmp` version: branch, tag, or commit

version 0.8.1 , tag: v0.8.1, branch: main, commit: a9a0f96

**Comment by Saghen** [comment]
Do you mind sharing your full code for the mapping? I'm not able to reproduce this

**Comment by lost22git** [comment]
just this:

```lua
vim.keymap.set("n", "qq", ":q<CR>", { silent = true })
```

but i `zz` to quit neovim, no errror, everything well

**Comment by Saghen** [comment]
I'm not able to reproduce, do you mind sharing a minimal repro? https://lazy.folke.io/developers#reprolua

**Comment by lost22git** [comment]
It works well now after upgrading plugin.

Thanks！
