### ISSUE TITLE
Trigger menu when deleting character after trigger character

### ISSUE THREAD

**Issue by ruslanSorokin** [Saghen/blink.cmp#745]
### Feature Description

Currently, trigger characters don't work if we happen to be at one after removing a character from the right.

Current behavior: `x.f|` => `<BS>` => `x.|` - completion menu _**not triggered**_
Desired behavior: `x.f|` => `<BS>` => `x.|` - completion menu _**triggered**_

**Comment by ruslanSorokin** [comment]
> Currently, trigger characters don't work if we happen to be at one after removing a character from the right

I might be wrong in that, but I couldn't configure it the way I've outlined.

**Comment by alex35mil** [comment]
Is there a way to trigger completion on <BS> regardless of trigger character?
