### ISSUE TITLE
Tab doesn't work when copilot.lua is configured (even with accept suggestion mapped to other source)

### ISSUE THREAD

**Issue by leonnardo** [Saghen/blink.cmp#749]
### Make sure you have done the following

- [X] I have updated to the latest version of `blink.cmp`
- [X] I have read the README

### Bug Description

Tab does not work as it should (add the `\t` character to the editor, expanding or not to spaces) when running blink.cmp side by side with copilot.lua.

When copilot.lua is turned off, blink works fine!

### Relevant configuration

```lua
keymap = {
	preset = "enter",
	["<Tab>"] = {
		"fallback",
	},
}
```

### neovim version

v0.10.2

### `blink.cmp` version: branch, tag, or commit

main

**Comment by Saghen** [comment]
Are you setting your `copilot.lua` to use `<Tab>`?

**Comment by leonnardo** [comment]
> Are you setting your `copilot.lua` to use `<Tab>` for any of the keymaps? It may be overriding our keymaps, in which case, this would be a duplicate of #406

No, I'm not, I changed copilot.lua `accept` keymap to `C-i`

**Comment by Saghen** [comment]
I'm not able to reproduce this, if you're able to reproduce it with https://lazy.folke.io/developers#reprolua, I'll take another look but it seems that blink's keymaps are getting overridden
