### ISSUE TITLE
No way to show menu when `ghost_text` enabled and `auto_show` disabled

### ISSUE THREAD

**Issue by frangio** [Saghen/blink.cmp#762]
### Make sure you have done the following

- [X] I have updated to the latest version of `blink.cmp`
- [X] I have read the README

### Bug Description

If `menu.auto_show` is disabled and `ghost_text` is enabled there seems to be no way to manually pull up the completion menu. `<C-Space>` in the default keymap preset does nothing in this case.

### Relevant configuration

```lua
keymap = { preset = 'default' },
completion = {
  ghost_text = { enabled = true },
  menu = { auto_show = false },
}
```

### neovim version

NVIM v0.10.3 Build type: Release LuaJIT 2.1.1713484068

### `blink.cmp` version: branch, tag, or commit

v0.8.2

**Comment by jessevdp** [comment]
I can confirm this!

I too run a config with `auto_show = false` and recently played around with ghost text.

I can open the completion menu when there is no ghost text visible yet.. So just after entering insert mode but when I haven't typed anything yet.

But after there is a completion with ghost text I can no long trigger `show`.

I can cycle to other completions using `select_next` and `_prev` just fine. (So there are other completions available!).

**Comment by jessevdp** [comment]
It might be this:

https://github.com/Saghen/blink.cmp/blob/8a092ce8630a885ba8b3e60c85fd06a6930d3af1/lua/blink/cmp/init.lua#L41-L42

https://github.com/Saghen/blink.cmp/blob/8a092ce8630a885ba8b3e60c85fd06a6930d3af1/lua/blink/cmp/init.lua#L35-L38

`show()` seems to have a guard clause that prevents it from being re-run if `is_visible()`. But `is_visible()` returns `true` when there is ghost text on the screen.

This was recently changed in 1006662ad53c92adf9ae6f2d05cee38f613d08ff. Also see the [CHANGELOG for `v0.8.0`](https://github.com/Saghen/blink.cmp/blob/8a092ce8630a885ba8b3e60c85fd06a6930d3af1/CHANGELOG.md#080-2024-12-20): 

> include ghost text in is_visible ([1006662](https://github.com/Saghen/blink.cmp/commit/1006662ad53c92adf9ae6f2d05cee38f613d08ff))
