### ISSUE TITLE
Bug(accept/brackets): cursor moves to semantically unrelated brackets 

### ISSUE THREAD

**Issue by ruslanSorokin** [Saghen/blink.cmp#764]
### Make sure you have done the following

- [X] I have updated to the latest version of `blink.cmp`
- [X] I have read the README

## Assuming
`Enter` - bind to `'accept'`
`uuid` - package or namespace/crate/module - something that is semantically not callable with ()
`NewV4` - callable function

## Current behavior
`blink.cmp.completion.accept` shifts cursor into brackets in front from any item, even if the item semantically cannot be used with these brackets, e.g. namespaces, value-fields, etc.

### Example
````
val, ok := uu|()
````
`Enter`
````
val, ok := uuid(|)
````

## Correct behavior
if these brackets in front don't actually relate to the item, then we should not shift the cursor into them

### Example
````
val, ok := uu|()
````
`Enter`
````
val, ok := uuid|()
````
`.Ne`
````
val, ok := uuid.Ne|()
````
`Enter`
````
val, ok := uuid.NewV4(|)
````

### Relevant configuration

```lua
keymap = {
  ["<CR>"] = { "accept", "fallback" },
},
completion = {
  accept = {
    auto_brackets = {
      enabled = true,
      default_brackets = { "(", ")" },
      kind_resolution = { enabled = false },
      semantic_token_resolution = { enabled = false },
    },
  },
},
```

### neovim version

NVIM v0.10.2 Build type: Release LuaJIT 2.1.1713773202 Run "nvim -V1 -v" for more info

### `blink.cmp` version: branch, tag, or commit

v0.8.1

**Comment by ruslanSorokin** [comment]
I have [fork](https://github.com/ruslanSorokin/blink.cmp) with this issue fixed, but I'm still testing it with different languages

**Comment by Saghen** [comment]
It sounds like your LSP is setting the semantic token to a function or method. Not sure if it was a typo, but the `accept` config is in `completion.accept`. Maybe setting `accept.auto_brackets.semantic_token_resolution.enabled = false` (or blocking it for just this filetype) would fix it

**Comment by ruslanSorokin** [comment]
> Not sure if it was a typo, but the `accept` config is in `completion.accept`

Apologies for that. I've corrected the configuration, but I included it mostly because I'm testing cursor shifts by toggling these brackets-related parameters on and off. None of these, as I believe, cannot prevent cursor shifting that happening up here: <https://github.com/Saghen/blink.cmp/blob/85fc2e71ed980720f2fdb78bb430217f840a9575/lua/blink/cmp/completion/brackets/kind.lua#L07-L20>
