### ISSUE TITLE
Name collision with nvim `vim.api.keyset.keymap`

### ISSUE THREAD

**Issue by yowu** [Saghen/blink.cmp#767]
### Make sure you have done the following

- [X] I have updated to the latest version of `blink.cmp`
- [X] I have read the README

### Bug Description

The locally defined class `vim.api.keyset.keymap` has a name collision with the original nvim version. This results in diagnostic errors when `blink.cmp` is added to the workspace library. 

https://github.com/Saghen/blink.cmp/blob/85fc2e71ed980720f2fdb78bb430217f840a9575/lua/blink/cmp/keymap/fallback.lua#L4

https://github.com/neovim/neovim/blob/master/runtime/lua/vim/_meta/api_keysets.lua#L189

### neovim version

v0.10.3

### `blink.cmp` version: branch, tag, or commit

v0.8.2

**Comment by mikavilpas** [comment]
Looks like they were added in 8b553f65419d051fe84eeeda3e2071e104c4f272

I wonder if this is specific to some version of neovim. What are the errors you see? Where do you see them?

**Comment by yowu** [comment]
This is a diagnostic error, not a real one. I use AstroNvim and it uses nvim built in `vim.api.keyset.keymap` to type some fields in it.

https://github.com/AstroNvim/astrocore/blob/ecaf7c76484d3313b966856c2c29672a6abbc3f4/lua/astrocore/config.lua#L12

The name collision happens if I include `blink.cmp` in my Lua workspace library. Then there are bunch of diagnostics errors from lua_ls as it tries to map my config entries to blink defined one.


It's a minor issue and I haven't checked other Neovim versions. But I believe the one in blink should be named within its own namespace to avoid conflicts with Neovim's built-in names.
