### ISSUE TITLE
Source - completion - copilot suggestion (when disabled)

### ISSUE THREAD

**Issue by zivkovicn** [Saghen/blink.cmp#770]
### Make sure you have done the following

- [X] I have updated to the latest version of `blink.cmp`
- [X] I have read the README

### Bug Description

Hello,

I keep seeing this odd behaviour when I have copilot disabled in the completion list.

In 90% of time I don't have the copilot in the dropdown (completion list), but in other 10% I have it.

Screenshot when it is working correctly:
<img width="554" alt="Screenshot 2024-12-25 at 10 22 19 AM" src="https://github.com/user-attachments/assets/2946afde-67fa-4617-b069-ff068f31214a" />

Screenshot when it is appearing in the list:
<img width="752" alt="Screenshot 2024-12-25 at 10 17 12 AM" src="https://github.com/user-attachments/assets/87a219c9-731d-4089-a620-f844aa3f5792" />

I don't think that this behaviour is related with the latest release ([v0.8.2](https://github.com/Saghen/blink.cmp/releases/tag/v0.8.2)) I saw this in earlier versions if it is important.

and I'm using lazyvim - if matters.

The desired behaviour is that copilot works like inline suggestions, while in the dropdown (completion list) I get only LSP suggestions - without copilot.

Thanks!

### Relevant configuration

```lua
here are my sources config:


    sources = {
      default = { "lsp", "path", "buffer" },
      -- disable cmd completion
      cmdline = {},
      -- disable snippets
      transform_items = function(_, items)
        return vim.tbl_filter(function(item)
          return item.kind ~= require("blink.cmp.types").CompletionItemKind.Snippet
        end, items)
      end,
    },
```

here is my copilot config:

```
return {
  "zbirenbaum/copilot.lua",
  cmd = "Copilot",
  event = "InsertEnter",
  opts = {
    panel = { enabled = false },
    suggestion = {
      enabled = true,
      auto_trigger = true,
    },
  },
}
```
```


### neovim version

NVIM v0.10.3 Build type: Release LuaJIT 2.1.1734355927 

### `blink.cmp` version: branch, tag, or commit

v0.8.2

**Comment by zivkovicn** [comment]
ok I've figure it out, needed to update the providers in sources:
```
    sources = {
      default = { "lsp", "path", "buffer" },
      -- disable cmd completion
      cmdline = {},
      -- disable snippets
      transform_items = function(_, items)
        return vim.tbl_filter(function(item)
          return item.kind ~= require("blink.cmp.types").CompletionItemKind.Snippet
        end, items)
      end,
      providers = {
        lsp = { enabled = true },
        path = { enabled = true },
        buffer = { enabled = true },
        copilot = { enabled = false },
      },
    },
```

the reason for that was lazyvim config `lazyvim/plugins/extras/ai/copilot.lua` it has:
```
        {
          "saghen/blink.cmp",
          optional = true,
          dependencies = { "giuxtaposition/blink-cmp-copilot" },
          opts = {
            sources = {
              default = { "copilot" },
              providers = {
                copilot = {
                  name = "copilot",
                  module = "blink-cmp-copilot",
                  kind = "Copilot",
                  score_offset = 100,
                  async = true,
                },
              },
            },
          },
        },

```

which was causing the issues. Will test out further and update if I see any issues, so far everything is good.

**Comment by mertkaradayi** [comment]
@zivkovicn 
I am trying to achieve the enable ghost text like editors Cursor and Windsurf.
And disable the blink cmp suggestion because seeing the copilot as a first suggestion really distracts me.
I couldn't find a way to do it.
Do you have any suggestions ?
