### ISSUE TITLE
Error after installing the plugin

### ISSUE THREAD

**Issue by nlvratna** [Saghen/blink.cmp#783]
### Make sure you have done the following

- [X] I have updated to the latest version of `blink.cmp`
- [X] I have read the README

### Bug Description

![image](https://github.com/user-attachments/assets/59fc42ed-400a-4750-970b-7b80b658b1d3)
I just installed the plugin everytime I try to do something this error popups   but I am not solve this issue

### Relevant configuration

```lua
return {
	{
	"saghen/blink.cmp",
		-- optional: provides snippets for the snippet source
		version = "*",
		dependencies = "rafamadriz/friendly-snippets",
opts = {
	keymap = { preset = "default" },
appearance = {
 use_nvim_cmp_as_default = true,
 nerd_font_variant = "mono",
			
},
-- signature = { enabled = true },
	},
},
}

lspconfig
local capabilities = vim.lsp.protocol.make_client_capabilities()
capabilities vim.tbl_deep_extend("force", capabilities, require("blink.cmp").get_lsp_capabilities())
```

### neovim version

NVIM v0.10.2 Build type: Release LuaJIT 2.1.1713484068

### `blink.cmp` version: branch, tag, or commit

*

**Comment by krovuxdev** [comment]
The error in require indicates that a plugin called cmp-nvim-lsp is missing or not found. It seems like you might have referenced it in your configuration, but it’s either not installed or not properly set up.
