### ISSUE TITLE
Incorrect documentation about completion.menu.draw

### ISSUE THREAD

**Issue by Yuyu-1115** [Saghen/blink.cmp#786]
### Make sure you have done the following

- [X] I have updated to the latest version of `blink.cmp`
- [X] I have read the README

### Bug Description

According to the doc [here](https://cmp.saghen.dev/configuration/reference.html#completion), `treesitter` is just a boolean, but that doesn't seem to be correct. When I look into [the code](https://github.com/Saghen/blink.cmp/blob/main/lua/blink/cmp/config/completion/menu.lua), It seems to be a table( I don't know much about lua, so please correct me if I'm wrong).

### Relevant configuration

```lua
completion = {
      documentation = {
        auto_show = true,
        auto_show_delay_ms = 500,
        treesitter_highlighting = true,
      },
      ghost_text = {
        enabled = true,
      },
      menu = {
        draw = {
          treesitter = {
            -- I'm not sure about this, I add this as other modules are enabled by this argument
            enabled = true
          }
        }
      }
```

### neovim version

0.10.3

### `blink.cmp` version: branch, tag, or commit

v0.8.2

**Comment by MrConnorKenway** [comment]
> When I look into [the code](https://github.com/Saghen/blink.cmp/blob/main/lua/blink/cmp/config/completion/menu.lua), It seems to be a table( I don't know much about lua, so please correct me if I'm wrong).

That's true. See f99b03c and https://github.com/Saghen/blink.cmp/issues/438.

**Comment by Yuyu-1115** [comment]
> > When I look into [the code](https://github.com/Saghen/blink.cmp/blob/main/lua/blink/cmp/config/completion/menu.lua), It seems to be a table( I don't know much about lua, so please correct me if I'm wrong).
> 
> That's true. See [f99b03c](https://github.com/Saghen/blink.cmp/commit/f99b03c756b32680eea28e89f95e3c6987cc6c80) and #438.

Thanks for pointing out! I was wondering why it is a String[]
