### ISSUE TITLE
blink.cmp not working for Marksman lsp

### ISSUE THREAD

**Issue by chenxin-yan** [Saghen/blink.cmp#787]
### Make sure you have done the following

- [X] I have updated to the latest version of `blink.cmp`
- [X] I have read the README

### Bug Description

blink.cmp does not provide path completion for markdown links generated by Marksman.

Expected behavior: After typing "[[", a menu should open, displaying the completion  from the LSP.

I suspect this issue may be caused by a blocking character in the completion menu.

### neovim version

v0.10.3

### `blink.cmp` version: branch, tag, or commit

v0.82

**Comment by mikavilpas** [comment]
This works for me in LazyVim

lspconfig info:

```
- Client: `marksman` (id: 4, bufnr: [170])
  root directory:    ~/git/blink.cmp/
  filetypes:         markdown, markdown.mdx
  cmd:               ~/.local/share/nvim/mason/bin/marksman server
  version:           `1.0.0-8299f11+8299f11dfad36a9162e010245b380ba25001b15c`
  executable:        true
  autostart:         true
```


https://github.com/user-attachments/assets/688f1c8e-05f8-4f0c-9eec-1bd851108be8

https://www.lazyvim.org/extras/coding/blink

**Comment by chenxin-yan** [comment]
I figured it out. It has nothing to do with blink. By default, Marksman links using header 1 instead of the markdown filename as reference.
