### ISSUE TITLE
Wrong snippet selection part

### ISSUE THREAD

**Issue by Kaiser-Yang** [Saghen/blink.cmp#794]
### Make sure you have done the following

- [X] I have updated to the latest version of `blink.cmp`
- [X] I have read the README

### Bug Description

Use the configuration for luasnip from blink's document.

The snippet is:

```json
    "h1": {
        "prefix": "h1",
        "body": [
            "# $1",
            "",
            "${0:<++>}"
        ],
        "description": "Heading 1"
    },
```

I've tested this worked in vs-code.

In nvim, accept this snippet by inputing 'h1' then use `<cr>` to confirm:

![image](https://github.com/user-attachments/assets/04587721-eead-40e8-9a3e-bd34a6e56ef3)

Input someting, then use `<tab>` to next position:

![image](https://github.com/user-attachments/assets/efb9d956-dcf5-4d78-86d9-bd5bb6c2a167)

The content in the rectangle is selected  not the `<++>`, for example if I input 'x':

![image](https://github.com/user-attachments/assets/8a36fc8c-bbd1-494d-9393-471ac56fbf94)

### neovim version

NVIM v0.10.1

### `blink.cmp` version: branch, tag, or commit

v0.8.2

**Comment by Saghen** [comment]
Sounds like an issue with your snippet engine rather than with blink
