### ISSUE TITLE
Stuck in `:!` when inputting the first letter

### ISSUE THREAD

**Issue by Kaiser-Yang** [Saghen/blink.cmp#795]
### Make sure you have done the following

- [X] I have updated to the latest version of `blink.cmp`
- [X] I have read the README

### Bug Description

When use `:!` to execute system commands, after inputting the first letter ( for example `!:e` to run `echo`) , it will stuck for a while ( about ten seconds) and I can not input during this time , after the completion list shows up, I can continue to input.

Shell: fish

System: WSL2 with Ubuntu 22.04 LTS

### neovim version

NVIM v0.10.1

### `blink.cmp` version: branch, tag, or commit

v0.8.2

**Comment by Saghen** [comment]
I don't experience any lag, are you able to create a minimal reproduction of this? Maybe it's due to having a large PATH? I'm not sure there's much we can do here, beyond re-implementing the completions for this, since we're using the built in completions

**Comment by Kaiser-Yang** [comment]
> I don't experience any lag, are you able to create [a minimal reproduction of this](https://lazy.folke.io/developers#reprolua)? Maybe it's due to having a large PATH? I'm not sure there's much we can do here, beyond re-implementing the completions for this, since we're using the built in completions

You are right, after I remove some paths from PATH, it will no long lag.

**Comment by Kaiser-Yang** [comment]
This is mainly caused by the wsl. wsl adds the PATH of windows to Linux's PATH. After I added those below to `/etc/wsl.conf`, and restarted wsl, the lag disapeared:

```
[interop]
appendWindowsPath=false
```

**Comment by Violettica** [comment]
Is there a way to simply turn off reading PATH for `:!` and similar commands? Removing the windows path from my WSL would break my workflow, disabling shell completion is preferable.

**Comment by Saghen** [comment]
I've opened a separate issue for that #1029 @Violettica
