### ISSUE TITLE
Auto-Completion for CSS Inside Astro Files

### ISSUE THREAD

**Issue by Foparty** [Saghen/blink.cmp#797]
### Make sure you have done the following

- [X] I have updated to the latest version of `blink.cmp`
- [X] I have read the README

### Bug Description

while on an .astro file, inside the <style> tag, ready to write some CSS, it never suggests correctly anything until you write a "-". 
if not and you hit C-y, will always try to create an HTML tag

https://github.com/user-attachments/assets/9d833a1e-d6b0-4a65-8bdf-cce52aac2252

### neovim version

NVIM v0.10.2 Build type: Release LuaJIT 2.1.1732813678

### `blink.cmp` version: branch, tag, or commit

main

**Comment by Saghen** [comment]
Unable to reproduce, perhaps you're missing LSP capabilities? https://cmp.saghen.dev/installation.html#lazy-nvim

I'll take another look if you can reproduce it with https://lazy.folke.io/developers#reprolua
