### ISSUE TITLE
snippets: option to have `$CLIPBOARD` copy from `+` register, not unnamed register

### ISSUE THREAD

**Issue by chrisgrieser** [Saghen/blink.cmp#800]
### Feature Description

In a snippet, when you use `$CLIPBOARD`, it only inserts the unnamed register, but not the system clipboard. However, for many snippets, it is actually more useful to copy from the system clipboard, e.g., when inserting URLs.

**Comment by Saghen** [comment]
Untested so lmk if you run into any issues
