### ISSUE TITLE
Matching error for words with special characters and words with less than 3 characters

### ISSUE THREAD

**Issue by TM10YMhp** [Saghen/blink.cmp#801]
### Make sure you have done the following

- [X] I have updated to the latest version of `blink.cmp`
- [X] I have read the README

### Bug Description

Words starting with `&`, `$`, `#`, `_`, `__`, `--`, `-`. are not matching correctly. In addition, words that have less than 3 characters are also not matching properly.

https://github.com/user-attachments/assets/a18475bd-6c2f-4a06-8d4c-c3ae2a44b3e8

### neovim version

NVIM v0.10.3

### `blink.cmp` version: branch, tag, or commit

v0.8.2

**Comment by Saghen** [comment]
We intentionally don't include words shorter than 3 characters from the buffer source, since they're too short to be useful imo. We don't match on any of the characters listed currently, you'll want to wait for #657

**Comment by TM10YMhp** [comment]
Including words of less than three characters from the buffer source is not very useful when the language server (LSP) is active. Without an active LSP, this can be cumbersome. Would it be possible to add an option to set the minimum number of characters from the buffer source?
