### ISSUE TITLE
Execute command after `cmp.show`

### ISSUE THREAD

**Issue by aidancz** [Saghen/blink.cmp#806]
namely, this setup does not work:

```
require("blink.cmp").setup({
	completion = {
		menu = {
			auto_show = false,
		},
		list = {
			selection = "auto_insert",
		},
	},
	keymap = {
		preset = "none",
		["<down>"] = {
			function(cmp)
				cmp.show()
				cmp.select_next()
			end,
		},
	},
})
```

I have this ugly hack as a workaround..

```
		["<down>"] = {
			function(cmp)
				cmp.show()
				vim.defer_fn(function()
					cmp.select_next()
				end, 1)
			end,
		},
```

**Comment by Saghen** [comment]
On `main`, you can now do `cmp.show({ callback = functino() cmp.select_next() end })`

**Comment by aidancz** [comment]
Thank you for the prompt fix! However, this doesn't seem to work.

with this setup:

```
require("blink.cmp").setup({
	completion = {
		menu = {
			auto_show = false,
		},
		list = {
			selection = "auto_insert",
		},
	},
	keymap = {
		preset = "none",
		["<down>"] = {
			function(cmp)
				cmp.show({
					callback = function()
						vim.print(cmp.is_visible())
						cmp.select_next()
					end,
				})
			end,
		},
	},
})
```

I still can't show the menu and immediately select the first candidate when I press the <down> key for the first time.

since when the callback function invokes, `cmp.is_visible()` will return `false`

---

Is there a more general way to connect two commands?

I want to chain `cancel` and `show` too

should I use `require('blink.cmp.completion.list').undo_preview()` in my config?

**Comment by Saghen** [comment]
This one was a bit tricky because the internals use events for most communication, but I've worked out a semi hacky solution that seems to work well. I've also added callbacks to `.cancel` and `.hide`
