### ISSUE TITLE
Recently updated and am facing "Please use a 'config()' function instead with the default settings.

### ISSUE THREAD

**Issue by leet0rz** [Saghen/blink.cmp#813]
### Make sure you have done the following

- [X] I have updated to the latest version of `blink.cmp`
- [X] I have read the README

### Bug Description

Lua module not found for config of blink.cmp. Please use a `config()` function instead.

As far as I know the default config should not be containing a config() function at all? Below is the config I've used and should be the default one. Any ideas how I could fix this issue? Thanks.

### Relevant configuration

```lua
return {
	{
		"saghen/blink.cmp",
		version = "*",
		opts = {
			keymap = { preset = "default" },
			appearance = {
				use_nvim_cmp_as_default = true,
				nerd_font_variant = "mono",
			},
			sources = {
				default = { "lsp", "path", "snippets", "buffer" },
			},
		},
		opts_extend = { "sources.default" },
	},
}
```

### neovim version

NVIM v0.11.0-dev-1392+g725d3e25a3 Build type: RelWithDebInfo LuaJIT 2.1.1734355927 Run "nvim -V1 -v" for more info

### `blink.cmp` version: branch, tag, or commit

0.8.2

**Comment by Saghen** [comment]
Maybe try reinstalling, sounds like an issue with lazy,nvim

**Comment by leet0rz** [comment]
> Maybe try reinstalling, sounds like an issue with lazy,nvim

Thanks for making me do it again, I already did but removed the wrong blink folder when trying to get it to reinstall, this time I removed the right one and it reinstalled and works fine now. Strange.
