### ISSUE TITLE
When in snippet completion mode, press backspace to enter normal mode

### ISSUE THREAD

**Issue by shellRaining** [Saghen/blink.cmp#830]
### Make sure you have done the following

- [X] I have updated to the latest version of `blink.cmp`
- [X] I have read the README

### Bug Description

https://github.com/user-attachments/assets/9d26692e-6f42-4d2a-9ed3-397f2cbc4861

as shown above

### Relevant configuration

```lua
keymap = {
      preset = "super-tab",
      ["<C-k>"] = {
        function(blink_cmp)
          if blink_cmp.is_visible() then
            blink_cmp.hide()
          else
            blink_cmp.show()
          end
        end,
      },
    },
```

### neovim version

NVIM v0.10.3

### `blink.cmp` version: branch, tag, or commit

0.8.2

**Comment by Saghen** [comment]
This doesn't seem to be an issue with blink.cmp, we're using the built-in `vim.snippet` so you should be able to reproduce with a `vim.snippet.expand(some_snippet)`

**Comment by shellRaining** [comment]
thank you, I found this is vim feature, the mode will change from select to normal after press backspace, so I set a keymap

```lua
vim.keymap.set("s", "<bs>", "<C-g>c", { desc = "delete selection in insert mode" })
```

now it can work properly
