### ISSUE TITLE
You may have forgot the file blink/cmp/sources/path/regex.lua on commit: 8df826f

### ISSUE THREAD

**Issue by arpangreat** [Saghen/blink.cmp#834]
### Make sure you have done the following

- [X] I have updated to the latest version of `blink.cmp`
- [X] I have read the README

### Bug Description

As mentioned in the title in commit: 8df826f
you have changed the regex matching and called regex as a module living in sources/path/regex.lua unfortunately that file is missing.

### neovim version

NVIM v0.11.0-dev-1448+ga389dc2f9 Build type: RelWithDebInfo LuaJIT 2.1.1734355927

### `blink.cmp` version: branch, tag, or commit

main

**Comment by Saghen** [comment]
Indeed I did, thanks :)

**Comment by arpangreat** [comment]
No problem mate :) 

Happy New Year :heart:  and thanks for this great plugin :smile:
