### ISSUE TITLE
Feature Request: Smart In-word completion

### ISSUE THREAD

**Issue by adaszko** [Saghen/blink.cmp#88]
It'd be nice if completion candidates were filtered not only based on the prefix but also consider the suffix if completing in the middle of a word (e.g. `foo_<TAB>_baz`).  If there's a space after the cursor, this feature doesn't apply.

Behavior specification:

Let's assume I'm completing `foo_|_baz` with the cursor positition indicated by `|`.

Case 1. I have `foo_bar_baz` somewhere in completion sources.  The completion should result in `foo_bar_baz`.
Case 2. I don't have anything matching the wildcard `foo_*_baz` in the completion sources but have `foo_quux`.  The completion should then fallback to matching just the prefix and result in completing to `foo_quux_baz`.

**Comment by Saghen** [comment]
This one has been moved from `config.fuzzy.keyword_range` to `config.trigger.completion.keyword_range`

**Comment by galou** [comment]
I cannot the documentation for `keyword_range`. Was the parameter renamed?

**Comment by adaszko** [comment]
https://cmp.saghen.dev/configuration/completion#keyword

The docs say its name is `range` :)

**Comment by nyncral** [comment]
It would be nice if there was at least an option to replace the suffix as well when accepting a selection
_(I say "at least" because imo it should be by default, I don't see the use of range=full not replacing suffix as well)_

**Comment by adaszko** [comment]
> It would be nice if there was at least an option to replace the suffix as well when accepting a selection

What specific case do you mean?  You're gonna have to give some examples.

**Comment by nyncral** [comment]
> > It would be nice if there was at least an option to replace the suffix as well when accepting a selection
> 
> What specific case do you mean? You're gonna have to give some examples.

sry if it wasn't clear enough
example with "MonoBehaviour" in c#
When I type "Mno", go back between the "M" and "n", type the "o" it proposes "MonoBehaviour" correctly, but when I accept it what is written on that line is "MonoBehaviourno" (the suffix even if taken into account for the auto-completion suggestion, doesn't get replaced by the suggestion like the prefix does)
what I'd like is if I have my cursor like this: "MonoB|eha" and accept "MonoBehaviour" it writes "MonoBehaviour" on that line and not "MonoBehavioureha"
