### ISSUE TITLE
Display style

### ISSUE THREAD

**Issue by lopi-py** [Saghen/blink.cmp#9]
Is there any way to have the default cmp display style?

`nvim-cmp`
![image](https://github.com/user-attachments/assets/3aa94b1f-4a5c-4119-8bad-3bbc85900951)

`blink.cmp`
![image](https://github.com/user-attachments/assets/4c70c23b-9138-45ee-9a8d-7c68d748b89a)

**Comment by Jlchong3** [comment]
Add this to the opts
```lua
windows = {
    autocomplete = {
        draw = 'reversed'
    }
}
```
Hope that helps
