### ISSUE TITLE
fuzzy failed with status 2

### ISSUE THREAD

**Issue by sjava** [Saghen/blink.cmp#90]
Error executing vim.schedule lua callback: ...al/share/nvim/lazy/blink.cmp/lua/blink/cmp/fuzzy/ffi.lua:377: fuzzy failed with status 2
stack traceback:
	[C]: in function 'error'
	...al/share/nvim/lazy/blink.cmp/lua/blink/cmp/fuzzy/ffi.lua:377: in function 'fuzzy'
	...l/share/nvim/lazy/blink.cmp/lua/blink/cmp/fuzzy/init.lua:57: in function 'filter_items_with_cache'
	.../.local/share/nvim/lazy/blink.cmp/lua/blink/cmp/init.lua:47: in function <.../.local/share/nvim/lazy/blink.cmp/lua/blink/cmp/init.lua:46>

nvim version: v0.10.2
blink.cmp: commit 526f786

**Comment by kid** [comment]
I'm having the same issue, with a slightly different message, probably because of `nixvim`:
```
Error executing vim.schedule lua callback: ...ovimPackages/start/blink-cmp/lua/blink/cmp/fuzzy/ffi.lua:0: fuzzy failed with status 2
stack traceback:
	[C]: in function 'error'
	...ovimPackages/start/blink-cmp/lua/blink/cmp/fuzzy/ffi.lua: in function 'fuzzy'
	...vimPackages/start/blink-cmp/lua/blink/cmp/fuzzy/init.lua: in function 'filter_items_with_cache'
	.../myNeovimPackages/start/blink-cmp/lua/blink/cmp/init.lua: in function <.../myNeovimPackages/start/blink-cmp/lua/blink/cmp/init.lua:0>
```
This seems to be caused by #22 as the commit before that works

**Comment by 0xJWLabs** [comment]
You can use my fork from https://github.com/neovim-plugin/blink.cmp for a while. It fixed the problems while still keeps detecting characters with a length greater than 256.

**Comment by tarkin88** [comment]
Thanks! Are you open a PR for this fix?
