### ISSUE TITLE
Adding this plugin to nixpkgs

### ISSUE THREAD

**Issue by Balssh** [Saghen/blink.cmp#96]
Hey there, I'm curious if you have in plan to add this to nixpkgs as I see you already have a flake ready. If not, I'm willing to try to add it (I'm still quite new to nix(os) and this would be my first contribution to nixpkgs).

**Comment by Saghen** [comment]
> I'm willing to try to add it

That'd be great! Let me know if you need anything from me

**Comment by pwnwriter** [comment]
LFG LFG !!!

**Comment by Balssh** [comment]
Opened this one: https://github.com/NixOS/nixpkgs/pull/348105
What I'd like is either a review or some guidance on how to properly test this locally. I'm not sure I declared the rust dependencies right. Thanks!

**Comment by Balssh** [comment]
Ok, after some learning, I got the PR ready for review/merge, as the plugin builds and runs.

**Comment by redxtech** [comment]
Thank you for working on this!

I've left a review on the PR, and can add an approval as soon as it's ready!

**Comment by Balssh** [comment]
With the above PR merged to master, I'll proceed with https://github.com/nix-community/nixvim/pull/2404 for adding blink to nixvim too.

**Comment by Balssh** [comment]
Blink is now both in nixpkgs and in nixvim. Closed this issue.

**Comment by Saghen** [comment]
Thanks for all your work on this!
